"""Additive storage for family story contributions, books and conversations."""
from sqlalchemy import (CheckConstraint, Column, ForeignKey, Index, Integer,
                        LargeBinary, Table, Text, UniqueConstraint)


def add_collaboration_tables(metadata):
    contributions = Table('access_memory_contributions', metadata,
        Column('id', Text, primary_key=True, nullable=False),
        Column('story_id', Text, ForeignKey('access_memory_stories.id'), nullable=False),
        Column('library_id', Text, ForeignKey('access_libraries.id'), nullable=False),
        Column('author_id', Text, ForeignKey('access_accounts.id'), nullable=False),
        Column('kind', Text, nullable=False),
        Column('original_text', Text),
        Column('original_audio', LargeBinary),
        Column('language', Text, nullable=False),
        Column('byline', Text, nullable=False),
        Column('sha256', Text, nullable=False),
        Column('duration_ms', Integer),
        Column('local_processing_consent', Integer, nullable=False),
        Column('chapter_id', Text),
        Column('base_story_revision', Integer, nullable=False),
        Column('state', Text, nullable=False),
        Column('mutation_id', Text, nullable=False),
        Column('request_digest', Text, nullable=False),
        Column('created_at', Integer, nullable=False),
        Column('reviewed_by_id', Text, ForeignKey('access_accounts.id')),
        Column('reviewed_at', Integer),
        UniqueConstraint('author_id', 'mutation_id', name='uq_memory_contribution_mutation'),
        CheckConstraint("kind IN ('text','audio')", name='ck_memory_contribution_kind'),
        CheckConstraint("language IN ('zh','en','mixed','und')", name='ck_memory_contribution_language'),
        CheckConstraint('local_processing_consent IN (0,1)', name='ck_memory_contribution_consent'),
        CheckConstraint('base_story_revision > 0', name='ck_memory_contribution_base_revision'),
        CheckConstraint("state IN ('pending','accepted','declined')", name='ck_memory_contribution_state'),
        CheckConstraint("(kind='text' AND original_text IS NOT NULL AND length(CAST(original_text AS BLOB)) BETWEEN 1 AND 8192 AND original_audio IS NULL AND duration_ms IS NULL) OR (kind='audio' AND original_text IS NULL AND original_audio IS NOT NULL AND length(original_audio) BETWEEN 1 AND 2097152 AND duration_ms IS NOT NULL AND duration_ms BETWEEN 1 AND 30000)",
                        name='ck_memory_contribution_original'),
        CheckConstraint('length(CAST(byline AS BLOB)) <= 256', name='ck_memory_contribution_byline'),
        CheckConstraint('(reviewed_by_id IS NULL) = (reviewed_at IS NULL)',
                        name='ck_memory_contribution_review_pair'))
    Index('ix_memory_contribution_story_state', contributions.c.story_id,
          contributions.c.state, contributions.c.created_at, contributions.c.id)
    Index('ix_memory_contribution_author_library', contributions.c.author_id,
          contributions.c.library_id, contributions.c.created_at)

    derivations = Table('access_memory_contribution_derivations', metadata,
        Column('contribution_id', Text,
               ForeignKey('access_memory_contributions.id', ondelete='CASCADE'),
               primary_key=True, nullable=False),
        Column('revision', Integer, primary_key=True, nullable=False),
        Column('state', Text, nullable=False),
        Column('transcript', Text),
        Column('polished_text', Text),
        Column('tags', Text, nullable=False, server_default='[]'),
        Column('provider', Text),
        Column('model', Text),
        Column('error_code', Text),
        Column('lease_id', Text),
        Column('lease_until', Integer),
        Column('created_at', Integer, nullable=False),
        Column('updated_at', Integer, nullable=False),
        CheckConstraint('revision > 0', name='ck_memory_contribution_derivation_revision'),
        CheckConstraint("state IN ('waiting','running','ready','failed','cancelled')",
                        name='ck_memory_contribution_derivation_state'),
        CheckConstraint('(lease_id IS NULL) = (lease_until IS NULL)',
                        name='ck_memory_contribution_derivation_lease_pair'),
        CheckConstraint('transcript IS NULL OR length(CAST(transcript AS BLOB)) <= 8192',
                        name='ck_memory_derivation_transcript'),
        CheckConstraint('polished_text IS NULL OR length(CAST(polished_text AS BLOB)) <= 8192',
                        name='ck_memory_derivation_wording'),
        CheckConstraint('length(CAST(tags AS BLOB)) <= 4096', name='ck_memory_derivation_tags'))
    Index('ix_memory_contribution_derivation_queue', derivations.c.state,
          derivations.c.updated_at, derivations.c.contribution_id)

    books = Table('access_memory_books', metadata,
        Column('id', Text, primary_key=True, nullable=False),
        Column('library_id', Text, ForeignKey('access_libraries.id'), nullable=False),
        Column('author_id', Text, ForeignKey('access_accounts.id'), nullable=False),
        Column('revision', Integer, nullable=False),
        Column('content', Text, nullable=False),
        Column('created_at', Integer, nullable=False),
        Column('updated_at', Integer, nullable=False),
        CheckConstraint('revision > 0', name='ck_memory_book_revision'),
        CheckConstraint('length(CAST(content AS BLOB)) <= 65536', name='ck_memory_book_content'))
    Index('ix_memory_book_library_updated', books.c.library_id,
          books.c.updated_at, books.c.id)

    book_revisions = Table('access_memory_book_revisions', metadata,
        Column('book_id', Text, ForeignKey('access_memory_books.id', ondelete='CASCADE'),
               primary_key=True, nullable=False),
        Column('revision', Integer, primary_key=True, nullable=False),
        Column('editor_id', Text, ForeignKey('access_accounts.id'), nullable=False),
        Column('mutation_id', Text, nullable=False),
        Column('request_digest', Text, nullable=False),
        Column('content', Text, nullable=False),
        Column('occurred_at', Integer, nullable=False),
        UniqueConstraint('editor_id', 'mutation_id', name='uq_memory_book_editor_mutation'),
        CheckConstraint('revision > 0', name='ck_memory_book_revision_number'),
        CheckConstraint('length(CAST(content AS BLOB)) <= 65536', name='ck_memory_book_revision_content'))
    Index('ix_memory_book_revision_mutation', book_revisions.c.editor_id,
          book_revisions.c.mutation_id, unique=True)

    conversations = Table('access_memory_conversations', metadata,
        Column('id', Text, primary_key=True, nullable=False),
        Column('library_id', Text, ForeignKey('access_libraries.id'), nullable=False),
        Column('actor_id', Text, ForeignKey('access_accounts.id'), nullable=False),
        Column('story_id', Text, ForeignKey('access_memory_stories.id')),
        Column('book_id', Text, ForeignKey('access_memory_books.id')),
        Column('created_at', Integer, nullable=False),
        Column('expires_at', Integer, nullable=False),
        CheckConstraint('(story_id IS NOT NULL) != (book_id IS NOT NULL)',
                        name='ck_memory_conversation_one_parent'),
        CheckConstraint('expires_at > created_at AND expires_at <= created_at + 2592000', name='ck_memory_conversation_expiry'))
    Index('ix_memory_conversation_library_created', conversations.c.library_id,
          conversations.c.created_at, conversations.c.id)
    Index('ix_memory_conversation_actor_created', conversations.c.actor_id,
          conversations.c.created_at)
    Index('ix_memory_conversation_expiry', conversations.c.expires_at)

    jobs = Table('access_memory_jobs', metadata,
        Column('id', Text, primary_key=True, nullable=False),
        Column('library_id', Text, ForeignKey('access_libraries.id'), nullable=False),
        Column('actor_id', Text, ForeignKey('access_accounts.id'), nullable=False),
        Column('story_id', Text, ForeignKey('access_memory_stories.id')),
        Column('book_id', Text, ForeignKey('access_memory_books.id')),
        Column('conversation_id', Text,
               ForeignKey('access_memory_conversations.id', ondelete='CASCADE')),
        Column('kind', Text, nullable=False),
        Column('state', Text, nullable=False),
        Column('mutation_id', Text, nullable=False),
        Column('request_digest', Text, nullable=False),
        Column('base_revision', Integer, nullable=False),
        Column('source_fingerprint', Text, nullable=False),
        Column('input_json', Text, nullable=False),
        Column('output_json', Text),
        Column('error_code', Text),
        Column('lease_id', Text),
        Column('lease_until', Integer),
        Column('created_at', Integer, nullable=False),
        Column('updated_at', Integer, nullable=False),
        Column('expires_at', Integer, nullable=False),
        UniqueConstraint('actor_id', 'mutation_id', name='uq_memory_job_actor_mutation'),
        CheckConstraint('(story_id IS NOT NULL) != (book_id IS NOT NULL)',
                        name='ck_memory_job_one_parent'),
        CheckConstraint("kind IN ('narrative','chat')", name='ck_memory_job_kind'),
        CheckConstraint("state IN ('queued','running','ready','failed','cancelled','stale')",
                        name='ck_memory_job_state'),
        CheckConstraint('base_revision > 0', name='ck_memory_job_base_revision'),
        CheckConstraint('(lease_id IS NULL) = (lease_until IS NULL)',
                        name='ck_memory_job_lease_pair'),
        CheckConstraint('expires_at > created_at AND expires_at <= created_at + 2592000', name='ck_memory_job_expiry'),
        CheckConstraint('length(CAST(input_json AS BLOB)) <= 16384', name='ck_memory_job_input'),
        CheckConstraint('output_json IS NULL OR length(CAST(output_json AS BLOB)) <= 65536', name='ck_memory_job_output'))
    Index('ix_memory_job_queue', jobs.c.state, jobs.c.created_at, jobs.c.id)
    Index('ix_memory_job_library_actor', jobs.c.library_id, jobs.c.actor_id,
          jobs.c.created_at)
    Index('ix_memory_job_expiry', jobs.c.expires_at)

    turns = Table('access_memory_turns', metadata,
        Column('id', Text, primary_key=True, nullable=False),
        Column('conversation_id', Text,
               ForeignKey('access_memory_conversations.id', ondelete='CASCADE'),
               nullable=False),
        Column('sequence', Integer, nullable=False),
        Column('mutation_id', Text, nullable=False),
        Column('request_digest', Text, nullable=False),
        Column('input_text', Text, nullable=False),
        Column('reply_text', Text),
        Column('reply_kind', Text),
        Column('job_id', Text, ForeignKey('access_memory_jobs.id', ondelete='SET NULL')),
        Column('created_at', Integer, nullable=False),
        UniqueConstraint('conversation_id', 'sequence', name='uq_memory_turn_sequence'),
        UniqueConstraint('conversation_id', 'mutation_id', name='uq_memory_turn_mutation'),
        CheckConstraint('sequence > 0', name='ck_memory_turn_sequence'),
        CheckConstraint('length(CAST(input_text AS BLOB)) BETWEEN 1 AND 4096', name='ck_memory_turn_input'),
        CheckConstraint('reply_text IS NULL OR length(CAST(reply_text AS BLOB)) <= 4096', name='ck_memory_turn_reply'))
    Index('ix_memory_turn_conversation_created', turns.c.conversation_id,
          turns.c.created_at, turns.c.sequence)

    deletion_state = Table('access_original_deletion_state', metadata,
        Column('id', Integer, primary_key=True, nullable=True),
        Column('namespace', Text, nullable=False),
        Column('applied_seq', Integer, nullable=False),
        Column('applied_digest', Text, nullable=False),
        CheckConstraint('id=1', name='ck_original_deletion_singleton'),
        CheckConstraint('length(namespace)=36', name='ck_original_deletion_namespace'),
        CheckConstraint('applied_seq >= 0', name='ck_original_deletion_sequence'),
        CheckConstraint("length(applied_digest)=64 AND applied_digest NOT GLOB '*[^0-9a-f]*'",
                        name='ck_original_deletion_digest'))

    return contributions, derivations, books, book_revisions, conversations, jobs, turns, deletion_state
