package dev.photohouse.connected.core

import kotlinx.serialization.json.*
import org.junit.Assert.*
import org.junit.Test

/** Responses generated by the pinned backend on disposable synthetic storage. */
class ProtectedStoryWorkspaceBackendFixtureTest {
    private fun fixture(): JsonObject = javaClass.classLoader!!
        .getResourceAsStream("story-workspace-contract/examples.json")!!.use {
            Json.parseToJsonElement(it.readBytes().toString(Charsets.UTF_8)).jsonObject
        }
    private fun JsonElement.bytes() = toString().toByteArray(Charsets.UTF_8)

    @Test fun pinnedBackendPreviewAndTitlesDecodeWithoutSourceRewriting() {
        val example = fixture()
        assertEquals("f282472a29d291a8b7ffae1cf6c6ccddd07dc15a", example.getValue("backend_source").jsonPrimitive.content)
        val selected = example.getValue("asset_ids").jsonArray.map { it.jsonPrimitive.content }
        val draft = ProtectedStoryWorkspaceWire.decodePreview(example.getValue("preview").bytes(),
            "family-a", selected, expectedTheme = "trip", expectedLanguage = "zh")
        assertEquals(listOf("video", "image"), draft.items.map { it.asset.kind })
        assertNull(draft.items.first().asset.taken_at)
        assertEquals("filename", draft.items.first().asset.date_hint?.source)
        assertEquals("我们一起种花。\r\n这是合成资料。", draft.items.last().evidence.first().text)
        assertFalse(ProtectedStoryWorkspaceWire.decodeTitleCapabilities(example.getValue("title_capabilities_off").bytes()).enabled)
        assertTrue(ProtectedStoryWorkspaceWire.decodeTitleCapabilities(example.getValue("title_capabilities_on").bytes()).enabled)
        val titles = ProtectedStoryWorkspaceWire.decodeTitles(example.getValue("titles").bytes(), draft)
        assertEquals("一起种花的回忆", titles.single().text)
        assertEquals(listOf("family-11111111-1111-4111-8111-111111111111", "draft-chapter-1"), titles.single().sourceIds)
    }

    @Test fun nativeRequestsMatchActualBackendAcceptedStringFieldsExactly() {
        val example = fixture()
        val selected = example.getValue("asset_ids").jsonArray.map { it.jsonPrimitive.content }
        assertEquals(example.getValue("preview_request"), Json.parseToJsonElement(
            ProtectedStoryWorkspaceWire.encodePreviewRequest(selected, "trip", "zh", "")))
        val request = example.getValue("title_request").jsonObject
        val chapters = Json.parseToJsonElement(request.getValue("chapters").jsonPrimitive.content).jsonArray.map {
            ProtectedStoryWorkspaceChapterInput(it.jsonObject.getValue("id").jsonPrimitive.content,
                it.jsonObject.getValue("narration").jsonPrimitive.content)
        }
        assertEquals(request, Json.parseToJsonElement(ProtectedStoryWorkspaceWire.encodeTitleRequest(selected,
            "trip", "zh", request.getValue("selection_revision").jsonPrimitive.content, chapters)))
    }
    @Test fun createsFromActualBackendDraftAndRetriesWithoutDuplicateOrOldProse() {
        val example = fixture()
        val ids = example.getValue("asset_ids").jsonArray.map { it.jsonPrimitive.content }
        val draft = ProtectedStoryWorkspaceWire.decodePreview(example.getValue("preview").bytes(), "family-a", ids)
        val request = example.getValue("create_request").jsonObject
        val edited = draft.chapters.map { it.copy(narration = "我们一起种花，这是家人留下的回忆。") }
        assertEquals(request, Json.parseToJsonElement(ProtectedStoryWorkspaceCreateWire.encode(draft,
            request.getValue("title").jsonPrimitive.content, edited,
            request.getValue("mutation_id").jsonPrimitive.content)))
        val created = ProtectedMemoryStoriesWire.decode(example.getValue("created").bytes(), "family-a", ids)
        val retry = ProtectedMemoryStoriesWire.decode(example.getValue("create_retry").bytes(), "family-a", ids)
        val later = ProtectedMemoryStoriesWire.decode(example.getValue("create_retry_after_edit").bytes(), "family-a", ids)
        assertEquals(created, retry)
        assertEquals(created.id, later.id)
        assertEquals(2L, later.revision)
        assertEquals("家人修改后的标题", later.title)
        assertEquals(401, example.getValue("viewer_create_status").jsonPrimitive.int)
    }

}
