'use strict';
/* Focused real-browser -> closed ASGI -> a0 SQLite contribution-ref journey. */
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {createInterface}=require('node:readline');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../..'),artifacts=process.env.PH_BROWSER_ARTIFACTS||fs.mkdtempSync(path.join(os.tmpdir(),'photohouse-story-refs-'));
fs.mkdirSync(artifacts,{recursive:true});
const bridge=spawn(process.env.PH_BROWSER_PYTHON||path.join(root,'.venv/bin/python'),[path.join(__dirname,'browser_bridge.py')],{cwd:root,stdio:['pipe','pipe','pipe']});
let serial=0,readyResolve,readyReject;const pending=new Map(),ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
bridge.stderr.on('data',chunk=>process.stderr.write(chunk));createInterface({input:bridge.stdout}).on('line',line=>{const value=JSON.parse(line);if(value.ready){readyResolve();return;}const request=pending.get(value.id);if(request){pending.delete(value.id);request.resolve(value);}});
bridge.on('exit',code=>{if(code){readyReject(new Error('Browser bridge failed'));for(const item of pending.values())item.reject(new Error('Browser bridge failed'));}});
const rpc=message=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});bridge.stdin.write(JSON.stringify({...message,id})+'\n');});
const checks=[],requests=[],errors=[],external=[];let browser,ctx,dropOptin=false,proposalFixture=null,storyId=null,savedStoryPayload=null,holdDetail=false,resolveDetail,arriveDetail,holdRefs=false,resolveRefs,arriveRefs,malformedNextRefs=false;const writes=[];
const pass=name=>{checks.push(name);console.log('PASS '+name);};
(async()=>{
  await ready;browser=await chromium.launch({headless:true,...(process.env.PH_BROWSER_EXECUTABLE?{executablePath:process.env.PH_BROWSER_EXECUTABLE}:{}),args:['--disable-background-networking','--disable-component-update','--no-first-run','--host-resolver-rules=MAP * ~NOTFOUND']});
  ctx=await browser.newContext({viewport:{width:1280,height:960},serviceWorkers:'block'});
  await ctx.addInitScript(()=>{let Constructor;Object.defineProperty(window,'PhotoHouseStoryWorkspace',{configurable:true,get:()=>Constructor,set:value=>{Constructor=config=>{const instance=value(config);window.__storyWorkspaceTest=instance;return instance;};}});});
  await ctx.route('**/*',async route=>{
    const req=route.request(),url=new URL(req.url());if(url.origin!=='https://photohouse.test'){external.push(url.origin);await route.abort();return;}
    const requestRecord={method:req.method(),path:url.pathname+url.search,body:req.postData()};requests.push(requestRecord);
    if(proposalFixture&&req.method()==='GET'&&url.pathname===`/memory-community/v1/jobs/${proposalFixture.job.id}`){await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(proposalFixture.job)});return;}
    if(malformedNextRefs&&req.method()==='GET'&&url.pathname.endsWith('/contribution-refs')){malformedNextRefs=false;requestRecord.status=200;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:1,id:storyId,library_id:'family-a',revision:'2',chapters:[{chapter_id:'chapter-1',contribution_ids:[]}]})});return;}
    const headers=await req.allHeaders();delete headers['content-length'];if(!headers['sec-fetch-site'])headers['sec-fetch-site']=new URL(req.frame().url()).origin===url.origin?'same-origin':'none';requestRecord.headers=headers;
    if(['POST','PUT'].includes(req.method())&&url.pathname.startsWith('/memory-stories'))writes.push({method:req.method(),path:url.pathname+url.search,body:req.postData()});
    const result=await rpc({method:req.method(),path:url.pathname+url.search,headers,body:(req.postDataBuffer()||Buffer.alloc(0)).toString('base64')});requestRecord.status=result.status;requestRecord.response=Buffer.from(result.body,'base64').toString();
    if(req.method()==='GET'&&/^\/memory-stories\/[0-9a-f-]{36}$/.test(url.pathname)&&result.status===200){savedStoryPayload=JSON.parse(Buffer.from(result.body,'base64').toString());storyId=savedStoryPayload.id;}
    if(holdDetail&&req.method()==='GET'&&/^\/memory-community\/v1\/stories\/[0-9a-f-]+\/contributions\/[0-9a-f-]+$/.test(url.pathname)){holdDetail=false;arriveDetail();await new Promise(resolve=>resolveDetail=resolve);}
    if(holdRefs&&req.method()==='GET'&&url.pathname.endsWith('/contribution-refs')){holdRefs=false;arriveRefs();await new Promise(resolve=>resolveRefs=resolve);}
    if(dropOptin&&req.method()==='PUT'&&url.searchParams.get('contribution_refs')==='1'){dropOptin=false;await route.abort('failed');return;}
    const output={...result.headers};delete output['content-length'];delete output['content-encoding'];
    try{await route.fulfill({status:result.status,headers:output,body:Buffer.from(result.body,'base64')});}catch(error){if(!/closed|handled|cancel|Invalid InterceptionId/.test(error.message))throw error;}
  });
  const page=await ctx.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());await page.goto('https://photohouse.test/ui');await page.locator('#auth').waitFor();await page.locator('#phone').fill('+12025550100');await page.locator('#password').fill('Synthetic family passphrase!');await page.locator('#auth-submit').click();await page.locator('#grid .asset').first().waitFor();
  await rpc({command:'mutate',scenario:'many-assets'});
  await page.locator('#memory-create').click();await page.locator('#story-workspace-title').fill('一家人的湖边散步');await page.locator('#story-build').click();await page.locator('.story-chapter-card').first().waitFor();
  assert.equal((await page.locator('.story-contribution-references').allTextContents()).join(''),'','new unsaved chapters do not claim a source lookup failed');
  await page.locator('.story-chapter-card textarea').first().fill('我们沿湖边慢慢走。');await page.locator('#story-save-memory').click();await page.waitForFunction(()=>document.querySelector('#story-workspace-status').textContent.includes('已保存到'));
  assert.equal(writes.at(-1).method,'POST');assert.equal(new URL(writes.at(-1).path,'https://photohouse.test').searchParams.has('contribution_refs'),false,'new stories never opt into nonempty refs');
  await page.locator('#story-workspace-close').click();await page.locator('.saved-memory-cover').click();await page.locator('#story-reader').waitFor({state:'visible'});await page.waitForTimeout(100);assert(requests.some(item=>item.path.includes('/contribution-refs?')&&new URL(item.path,'https://photohouse.test').searchParams.has('revision')),'reader load requested the authorized current-revision references');
  assert(savedStoryPayload&&storyId,'reopen obtained the authorized story draft through the normal UI');
  await rpc({command:'mutate',scenario:'enable-story-source-detail-fixture'});
  const chapterId='chapter-1';const seeded=await rpc({command:'mutate',scenario:'story-ref-contributions',story_id:storyId,chapter_id:chapterId});assert.equal(seeded.ok,true);const contributionId=seeded.contribution_id,audioContributionId=seeded.audio_contribution_id;
  const chapterData=await page.evaluate(()=>window.__storyWorkspaceTest?true:false);assert.equal(chapterData,true);
  const proposalJobId='c0000000-0000-4000-8000-000000000099';
  // Chapter IDs and prose come from the protected saved-story response.
  proposalFixture={job:{id:proposalJobId,state:'ready',kind:'narrative',base_revision:'1',result:null}};
  const proposal={story_id:storyId,revision:'1',job_id:proposalJobId,chapters:[],source_refs:[]};
  // Use a known two-chapter outline from the real save response stored by the harness.
  proposal.chapters=savedStoryPayload.chapters.map((chapter,index)=>({id:chapter.id,narration:index===0?'这是经核对后采用的建议。':chapter.narration}));
  proposal.source_refs=proposal.chapters.map((chapter,index)=>({chapter_id:chapter.id,source_ids:index===0?[`contribution-${contributionId}`,`contribution-${audioContributionId}`]:[]}));
  proposalFixture.job.result={version:1,title:'一家人的湖边散步',needs_review:true,chapters:proposal.chapters.map((chapter,index)=>({...chapter,source_ids:proposal.source_refs[index].source_ids}))};
  await page.evaluate(value=>window.__storyWorkspaceTest.acceptProposal(value),proposal);await page.locator('#story-workspace').waitFor({state:'visible'});
  assert.equal(await page.locator('.story-proposal-reference-note').count(),0,'supported contribution reference is preserved instead of warned as lost');
  dropOptin=true;await page.locator('#story-save-memory').click();await page.waitForFunction(()=>document.querySelector('#story-workspace-status').textContent.includes('保存结果尚未确认'));
  const firstRetry=writes.at(-1);assert.equal(new URL(firstRetry.path,'https://photohouse.test').searchParams.get('contribution_refs'),'1');const firstBody=JSON.parse(firstRetry.body);assert.equal(typeof firstBody.contribution_refs,'string');assert.deepEqual(JSON.parse(firstBody.contribution_refs),[{chapter_id:'chapter-1',contribution_ids:[contributionId,audioContributionId]}]);
  const firstRetryRequest=requests.findLast(item=>item.method==='PUT'&&item.body===firstRetry.body);const newerBody={...firstBody,revision:'2',mutation_id:'e0000000-0000-4000-8000-000000000044',contribution_refs:JSON.stringify([{chapter_id:'chapter-1',contribution_ids:[audioContributionId,contributionId]}])};const newerWrite=await rpc({method:'PUT',path:firstRetry.path,headers:firstRetryRequest.headers,body:Buffer.from(JSON.stringify(newerBody)).toString('base64')});assert.equal(newerWrite.status,200,'a second mutation creates a newer server revision before the uncertain retry');assert.equal(JSON.parse(Buffer.from(newerWrite.body,'base64').toString()).revision,'3');
  let postSaveRefsArrivedResolve;const postSaveRefsArrived=new Promise(resolve=>postSaveRefsArrivedResolve=resolve);holdRefs=true;arriveRefs=postSaveRefsArrivedResolve;
  await page.locator('#story-save-memory').click();await page.waitForFunction(()=>document.querySelector('#story-workspace-status').textContent.includes('最新版本'),{timeout:7000}).catch(async()=>{throw new Error(`newer idempotent retry did not open the latest server revision; status=${await page.locator('#story-workspace-status').textContent()} recent=${JSON.stringify(requests.slice(-4))}`);});assert.equal(writes.at(-1).body,firstRetry.body,'uncertain retry preserves the exact same mutation body');await Promise.race([postSaveRefsArrived,page.waitForTimeout(5000).then(()=>{throw new Error('newer-revision reference refresh did not reach the delayed-response fence');})]);
  const raceRefs=page.locator('.story-chapter-card[data-chapter-id="chapter-1"] .story-contribution-references');assert.equal(await raceRefs.locator('[data-contribution-id]').count(),0,'pending-body refs are not seeded as current after idempotent retry returns a newer revision');assert.equal(await raceRefs.locator('.story-contribution-refs-status').count(),1,'newer revision remains unverified until its authorized reference read returns');resolveRefs();await page.waitForFunction(()=>document.querySelectorAll('.story-chapter-card[data-chapter-id="chapter-1"] .story-contribution-references [data-contribution-id]').length===2);assert.equal(await raceRefs.locator('[data-contribution-id]').nth(0).getAttribute('data-contribution-id'),audioContributionId);assert.equal(await raceRefs.locator('[data-contribution-id]').nth(1).getAttribute('data-contribution-id'),contributionId,'the authorized current-revision response replaces pending-body order');
  let verifiedRefsArrivedResolve;const verifiedRefsArrived=new Promise(resolve=>verifiedRefsArrivedResolve=resolve);holdRefs=true;arriveRefs=verifiedRefsArrivedResolve;await page.locator('#story-save-memory').click();await page.waitForFunction(()=>document.querySelector('#story-workspace-status').textContent.includes('已保存到'));await Promise.race([verifiedRefsArrived,page.waitForTimeout(5000).then(()=>{throw new Error('verified refs refresh did not reach local-remove race');})]);assert.equal(await raceRefs.locator('[data-contribution-id]').count(),2);await raceRefs.getByRole('button',{name:'移除此来源'}).last().click();assert.equal(await raceRefs.locator('[data-contribution-id]').count(),1);assert.equal(await raceRefs.locator('[data-contribution-id]').getAttribute('data-contribution-id'),audioContributionId);resolveRefs();await page.waitForTimeout(100);assert.equal(await raceRefs.locator('[data-contribution-id]').count(),1,'late refs refresh cannot undo an explicit local removal');assert.equal(await raceRefs.locator('[data-contribution-id]').getAttribute('data-contribution-id'),audioContributionId);await page.locator('#story-reload-memory').click();await page.locator('#story-reader').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelectorAll('#story-reader .story-reader-sources [data-contribution-id]').length===2);
  const readerSources=page.locator('#story-reader .story-reader-sources');await page.locator('#story-reader-play').click();assert.equal(await page.locator('#story-reader-play').textContent(),'暂停播放');await readerSources.locator('summary').click();assert.equal(await page.locator('#story-reader-play').textContent(),'慢慢播放','opening the current chapter sources stops paced playback');await readerSources.locator('summary').click();await page.waitForTimeout(150);assert.equal(await page.locator('#story-reader-play').textContent(),'慢慢播放','collapsing sources does not resume playback');await readerSources.locator('summary').click();const sourceRow=readerSources.locator(`[data-contribution-id="${contributionId}"]`),audioSourceRow=readerSources.locator(`[data-contribution-id="${audioContributionId}"]`);assert.equal(await readerSources.locator('[data-contribution-id]').count(),2);assert.match(await sourceRow.textContent(),/家人回忆来源/);assert.equal(await sourceRow.locator('.story-contribution-source-detail').isVisible(),false);
  const refsReadsBefore=requests.filter(item=>item.method==='GET'&&item.path.includes('/contribution-refs')).length,detailReadsBefore=requests.filter(item=>item.method==='GET'&&item.path.includes('/contributions/')).length;
  assert.equal(await sourceRow.locator('button').count(),1,`reference row has its explicit detail action: ${await sourceRow.textContent()}`);await page.locator('#story-reader-play').click();assert.equal(await page.locator('#story-reader-play').textContent(),'暂停播放');await sourceRow.locator('button').click();assert.equal(await page.locator('#story-reader-play').textContent(),'慢慢播放','explicit source detail review also stops paced playback');await page.waitForTimeout(500);assert.match(await sourceRow.textContent(),/合成家人原话/,`authorized text detail should render; got ${await sourceRow.textContent()}`);assert.equal(requests.filter(item=>item.method==='GET'&&item.path.includes('/contribution-refs')).length,refsReadsBefore);assert.equal(requests.filter(item=>item.method==='GET'&&item.path.includes('/contributions/')).length,detailReadsBefore+1);assert.equal(requests.some(item=>item.path.includes('/audio')),false,'source review never fetches original audio');
  await audioSourceRow.locator('button').click();await page.waitForTimeout(500);assert.match(await audioSourceRow.textContent(),/AI 转写 · 录音家人/);assert.match(await audioSourceRow.textContent(),/合成录音里的家人原话/,'audio source reveals only its authorized ready transcript and is labeled AI-derived');assert.equal(requests.filter(item=>item.method==='GET'&&item.path.includes('/contributions/')).length,detailReadsBefore+2);assert.equal(requests.some(item=>item.path.includes('/audio')),false,'source review never fetches original audio');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.style.zoom='150%';});await audioSourceRow.scrollIntoViewIfNeeded();assert.equal(await page.locator('#story-reader').evaluate(el=>el.scrollWidth>el.clientWidth),false);assert.equal(await audioSourceRow.evaluate(el=>el.scrollWidth>el.clientWidth),false);await page.locator('#story-reader').screenshot({path:path.join(artifacts,'story-contribution-source-reader-390-150.png')});await page.evaluate(()=>{document.documentElement.style.zoom='';});await page.setViewportSize({width:1280,height:960});
  await sourceRow.locator('button').click();let detailArrivedResolve;const detailArrived=new Promise(resolve=>detailArrivedResolve=resolve);holdDetail=true;arriveDetail=detailArrivedResolve;await sourceRow.locator('button').click();await Promise.race([detailArrived,page.waitForTimeout(5000).then(()=>{throw new Error('authorized source detail request did not reach the delayed-response fence');})]);await page.locator('#story-reader-close').evaluate(el=>el.click());resolveDetail();await page.waitForTimeout(100);await page.locator('.saved-memory-cover').click();await page.locator('#story-reader').waitFor({state:'visible'});await page.locator('#story-reader .story-reader-sources summary').click();assert.doesNotMatch(await page.locator('#story-reader .story-reader-sources').textContent(),/合成家人原话/,'late source detail cannot repopulate a newly rendered reader');
  malformedNextRefs=true;await page.locator('#story-reader-edit').click();await page.locator('#story-reload-memory').click();await page.locator('#story-reader').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#story-reader .story-reader-sources')?.textContent.includes('来源链接刷新失败'));const stillLinked=page.locator('#story-reader .story-reader-sources [data-contribution-id]');assert.equal(await stillLinked.count(),2,'malformed reload does not replace previously verified links with an empty list');assert.match(await page.locator('#story-reader .story-reader-sources').textContent(),/仍显示上次核实的链接/);await page.locator('#story-reader-edit').click();const refNote=page.locator('.story-chapter-card[data-chapter-id="chapter-1"] .story-contribution-references');await refNote.waitFor();assert.equal(await refNote.locator('.story-contribution-refs-status').count(),1,'malformed refresh warning appears beside retained editor links');assert.match(await refNote.textContent(),/仍显示上次核实的链接/,'warning distinguishes retained verified links from compatible-save fallback');assert.equal(await refNote.locator('[data-contribution-id]').count(),2);assert.doesNotMatch(await refNote.textContent(),/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,'editor labels refs without exposing opaque UUIDs');assert.equal(await refNote.getByRole('button',{name:'查看家人回忆'}).count(),2);assert.match(await refNote.textContent(),/家人回忆来源/);const editorSourceRow=refNote.locator(`[data-contribution-id="${contributionId}"]`);await editorSourceRow.getByRole('button',{name:'查看家人回忆'}).click();const editorDetail=editorSourceRow.locator('.story-contribution-source-detail');await editorDetail.waitFor({state:'visible'});assert.match(await editorDetail.textContent(),/合成家人原话/);await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.style.zoom='150%';});await refNote.scrollIntoViewIfNeeded();assert.equal(await refNote.evaluate(el=>el.scrollWidth>el.clientWidth),false,'saved ref and review/remove controls fit in the editor at 390px and 150%');await refNote.screenshot({path:path.join(artifacts,'story-contribution-ref-editor-390-150.png')});await page.evaluate(()=>{document.documentElement.style.zoom='';});await page.setViewportSize({width:1280,height:960});
  await refNote.getByRole('button',{name:'移除此来源'}).first().click();await refNote.getByRole('button',{name:'移除此来源'}).first().click();assert.equal(await refNote.locator('button').count(),0);await page.locator('#story-preview').click();await page.locator('#story-reader').waitFor({state:'visible'});assert.match(await page.locator('#story-reader .story-reader-sources').textContent(),/来源链接刷新失败/,'an empty retained map still shows the failed-refresh state');assert.equal(await page.locator('#story-reader .story-reader-sources [data-contribution-id]').count(),0);await page.locator('#story-reader-close').click();let refsArrivedResolve;const refsArrived=new Promise(resolve=>refsArrivedResolve=resolve);holdRefs=true;arriveRefs=refsArrivedResolve;await page.locator('#story-save-memory').click();await page.waitForFunction(()=>document.querySelector('#story-workspace-status').textContent.includes('已保存到'));const clearWrite=writes.at(-1);assert.deepEqual(JSON.parse(JSON.parse(clearWrite.body).contribution_refs),[{chapter_id:'chapter-1',contribution_ids:[]}]);
  await Promise.race([refsArrived,page.waitForTimeout(5000).then(()=>{throw new Error('post-save references did not reach the delayed-response fence');})]);await page.locator('#story-workspace-close').click();await page.locator('#logout').click();await page.locator('#auth').waitFor({state:'visible'});resolveRefs();await page.waitForTimeout(100);assert.equal(await page.locator('#story-chapter-editor').textContent(),'','late refs response cannot restore prior-scope editor rows');assert.doesNotMatch(await page.locator('#story-reader').textContent(),new RegExp(contributionId),'scope clear removes volatile contribution references');
  assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(external,[]);assert.deepEqual(errors,[]);pass('a0 saved refs adopt, persist atomically, reopen with explicit detail disclosure, and clear on explicit save');
  fs.writeFileSync(path.join(artifacts,'checks.json'),JSON.stringify({checks,errors,external,fixture:'synthetic accepted text and audio contributions seeded into the explicitly opted-in closed ASGI SQLite fixture'},null,2));console.log('ARTIFACTS '+artifacts);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(ctx)await ctx.close();if(browser)await browser.close();bridge.stdin.end();});
