'use strict';
/* Real Chromium UI against a synthetic, no-listener protected ASGI bridge. */
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {createInterface}=require('node:readline');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||process.env.PLAYWRIGHT_MODULE_PATH||'playwright-core');
const root=path.resolve(__dirname,'../..');
const artifacts=process.env.PH_BROWSER_ARTIFACTS||fs.mkdtempSync(path.join(os.tmpdir(),'photohouse-editorial-browser-'));
fs.mkdirSync(artifacts,{recursive:true});console.log('ARTIFACTS_DIR '+artifacts);
const python=process.env.PH_BROWSER_PYTHON||path.join(root,'.venv/bin/python');
const bridge=spawn(python,[path.join(__dirname,'memory_book_editorial_browser_bridge.py')],{cwd:root,stdio:['pipe','pipe','pipe']});
let serial=0,readyResolve,readyReject,bookId,textSourceId,secondTextSourceId,audioSourceId,firstStoryId,secondStoryId,csrfToken,sessionCookie,cookieName;const pending=new Map();
const ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
bridge.stderr.on('data',chunk=>process.stderr.write(chunk));
createInterface({input:bridge.stdout}).on('line',line=>{const value=JSON.parse(line);if(value.ready){bookId=value.book_id;textSourceId=value.text_source_id;secondTextSourceId=value.second_text_source_id;audioSourceId=value.audio_source_id;firstStoryId=value.first_story_id;secondStoryId=value.second_story_id;csrfToken=value.csrf_token;sessionCookie=value.session_cookie;cookieName=value.cookie_name;readyResolve();return;}const call=pending.get(value.id);if(call){pending.delete(value.id);call.resolve(value);}});
bridge.on('exit',code=>{if(code){readyReject(new Error(`Editorial ASGI bridge failed (${code})`));for(const call of pending.values())call.reject(new Error('Editorial ASGI bridge failed'));}});
const rpc=message=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});bridge.stdin.write(JSON.stringify({...message,id})+'\n');});
let browser,context,page;
(async()=>{
  await ready;
  browser=await chromium.launch({headless:true,...(process.env.PH_BROWSER_EXECUTABLE?{executablePath:process.env.PH_BROWSER_EXECUTABLE}:{}),args:['--disable-background-networking','--disable-component-update','--no-first-run','--host-resolver-rules=MAP * ~NOTFOUND']});
  context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,serviceWorkers:'block'});
  await context.addCookies([{name:cookieName,value:sessionCookie,url:'https://photohouse.test/',httpOnly:true,secure:true,sameSite:'Strict'}]);
  page=await context.newPage();const external=[];await context.route('**/*',async route=>{const request=route.request(),u=new URL(request.url());if(u.origin!=='https://photohouse.test'){external.push(u.origin);await route.abort();return;}if(u.pathname==='/'){await route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><main><div id="book-shelf"></div></main></body></html>'});return;}const response=await rpc({method:request.method(),path:u.pathname+u.search,headers:await request.allHeaders(),body:(request.postDataBuffer()||Buffer.alloc(0)).toString('base64')});await route.fulfill({status:response.status,contentType:response.content_type||'application/json',body:Buffer.from(response.body,'base64')});});
  const css=fs.readFileSync(path.join(root,'backend/app/ui/access/styles.css'),'utf8');
  const js=fs.readFileSync(path.join(root,'backend/app/ui/access/memory-community.js'),'utf8');
  await page.goto('https://photohouse.test/');await page.addStyleTag({content:css});
  await page.addScriptTag({content:js});
  await page.evaluate(csrf=>{
    window.__memoryRequests=[];window.__failEditorial=null;window.__holdNextEditorial=false;window.__editorialWaiting=false;window.__holdNextInspect=null;window.__inspectWaiting=false;window.__failInspectionStatus=null;window.__injectUnavailableEditorial=false;window.__heldInspectionResolve=null;window.__createdObjectUrls=[];window.__revokedObjectUrls=[];
    const createURL=URL.createObjectURL.bind(URL),revokeURL=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const value=createURL(blob);window.__createdObjectUrls.push(value);return value;};URL.revokeObjectURL=value=>{window.__revokedObjectUrls.push(value);return revokeURL(value);};
    const request=async(path,options={})=>{
      const url=new URL(path,location.href);url.searchParams.set('library','family-a');
      const method=options.method||'GET',body=options.rawBody!==undefined?options.rawBody:options.body===undefined?undefined:JSON.stringify(options.body);
      const log={method,path:url.pathname+url.search,body:body===undefined?null:body};window.__memoryRequests.push(log);
      if(method==='PUT'&&url.pathname.endsWith('/editorial')&&window.__failEditorial){const status=window.__failEditorial;window.__failEditorial=null;const error=new Error('Synthetic intercepted outcome');error.status=status;throw error;}
      const isInspect=/\/stories\/[^/]+\/contributions\/[^/?]+(?:\/audio)?$/.test(url.pathname);
      if(isInspect&&window.__failInspectionStatus){const status=window.__failInspectionStatus;window.__failInspectionStatus=null;const error=new Error('Synthetic protected-source failure');error.status=status;throw error;}
      const headers={'Accept':'application/json','Sec-Fetch-Site':'same-origin',...(options.headers||{}),...(options.extraHeaders||{})};if(method!=='GET'&&method!=='HEAD')headers['X-CSRF-Token']=window.__csrf;if(body!==undefined&&!headers['Content-Type'])headers['Content-Type']='application/json';
      const response=await fetch(url.pathname+url.search,{method,headers,body,signal:options.signal});if(!response.ok){const detail=await response.text();window.__requestFailures.push({status:response.status,path:url.pathname+url.search,detail});const error=new Error(`Request failed ${response.status}: ${detail}`);error.status= response.status;throw error;}let value;if(options.responseType==='blob')value=await response.blob();else value=await response.json();if(method==='GET'&&url.pathname.endsWith('/editorial')&&window.__injectUnavailableEditorial){window.__injectUnavailableEditorial=false;value.introduction_source_refs=[...value.introduction_source_refs,{story_id:window.__firstStoryId,story_revision:'1',chapter_id:'chapter-1',contribution_id:'00000000-0000-4000-8000-000000000001'}];}if(method==='PUT'&&url.pathname.endsWith('/editorial')&&window.__holdNextEditorial){window.__holdNextEditorial=false;window.__editorialWaiting=true;await new Promise(resolve=>{window.__releaseEditorial=resolve;});window.__editorialWaiting=false;}if(isInspect&&window.__holdNextInspect===url.pathname){window.__holdNextInspect=null;window.__inspectWaiting=true;await new Promise(resolve=>{window.__releaseInspection=resolve;});window.__inspectWaiting=false;}return value;
    };
    window.__requestErrors=[];window.__requestFailures=[];window.__csrf=csrf;window.__firstStoryId=null;window.__scope={account:'synthetic-owner',library:'family-a',locked:false,language:'en'};window.__community=window.PhotoHouseMemoryCommunity({scope:()=>window.__scope,request,onError:error=>window.__requestErrors.push({status:error.status,message:error.message})});
  },csrfToken);
  await rpc({command:'editorial-off'});
  await page.evaluate(()=>window.__community.books(document.querySelector('#book-shelf')));
  await page.locator('.memory-book-edit').first().click();
  await page.locator('.memory-community-book-editor').waitFor({state:'visible',timeout:6000});
  assert.equal(await page.getByRole('button',{name:'Collapse editor',exact:true}).count(),1,'the editor has one clear disclosure control');
  assert.equal(await page.locator('.memory-community-book-form input[name="title"]').inputValue(),'Editorial memoir');assert.equal(await page.locator('.memory-community-book-form textarea[name="introduction"]').inputValue(),'Opening words');
  await page.evaluate(()=>window.__community.translate());
  assert.equal(await page.locator('.memory-book-editorial-panel').count(),0,'HTTP 503 default-off fallback keeps the legacy editor without a citation panel');
  await rpc({command:'editorial-on'});
  await page.locator('.memory-book-edit').first().click();
  await page.locator('.memory-book-editorial-panel').waitFor({state:'attached',timeout:6000});
  const panel=page.locator('.memory-book-editorial-panel');await panel.locator('summary').click();
  assert.equal(await panel.locator('textarea').count(),1,'two-child memoir has one adjacent-story transition');
  assert.match(await panel.textContent(),/Recall 1/,'source picker shows a human recall ordinal');
  const fieldsets=panel.locator('fieldset.memory-book-editorial-sources');assert.equal(await fieldsets.count(),2,'opening and transition citations are separate');
  const citationBeforeInspect=await fieldsets.first().locator('input[type=checkbox]').evaluateAll(nodes=>nodes.map(node=>node.checked));
  assert.deepEqual(await page.evaluate(()=>window.__memoryRequests.filter(item=>/\/stories\/[^/]+\/contributions\/[^/?]+(?:\/audio)?(?:\?|$)/.test(item.path))),[],'opening the citation panel never fetches contribution details or audio');
  const textInspect=fieldsets.first().locator(`button[data-source-id="${textSourceId}"]`),audioInspect=fieldsets.first().locator(`button[data-source-id="${audioSourceId}"]`);
  await textInspect.click();await panel.getByText('synthetic family contribution',{exact:true}).waitFor({state:'visible'});
  assert.match(await panel.locator('.memory-book-editorial-byline').innerText(),/Byline \(as submitted\): Synthetic family byline/,'source detail shows the submitted byline without implying an account identity');
  assert.equal(await panel.locator('.memory-book-editorial-original h5').first().innerText(),'Original family words');
  assert.match(await panel.locator('.memory-book-editorial-derived').innerText(),/waiting or in progress/,'original words and the pending derivative state are distinct');
  assert.deepEqual(await fieldsets.first().locator('input[type=checkbox]').evaluateAll(nodes=>nodes.map(node=>node.checked)),citationBeforeInspect,'reading a source does not change its citation checkbox');
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>/\/audio(?:\?|$)/.test(item.path)).length),0,'text inspection never fetches recording bytes');
  await panel.locator('summary').click();await page.waitForFunction(()=>!document.querySelector('.memory-book-editorial-inspection'));
  assert.equal(await textInspect.getAttribute('aria-expanded'),'false','collapsing the editorial panel closes and clears source inspection');await panel.locator('summary').click();
  await audioInspect.click();await panel.getByRole('button',{name:'Load original recording'}).waitFor({state:'visible'});
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>/\/audio(?:\?|$)/.test(item.path)).length),0,'audio detail does not fetch its recording');
  await panel.getByRole('button',{name:'Load original recording'}).click();await panel.locator('.memory-book-editorial-audio-box audio').waitFor({state:'attached'});
  assert.equal(await panel.locator('.memory-book-editorial-audio-box audio').evaluate(player=>player.autoplay),false,'native audio controls do not autoplay');
  assert.equal(await panel.locator('.memory-book-editorial-audio-box audio').evaluate(player=>player.preload),'none');
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>/\/audio(?:\?|$)/.test(item.path)).length),1,'recording bytes are requested only after the explicit load action');
  assert.equal(await page.evaluate(()=>window.__createdObjectUrls.length),1);
  const loadedPlayer=await panel.locator('.memory-book-editorial-audio-box audio').elementHandle(),loadAudioButton=panel.getByRole('button',{name:'Load original recording'});
  assert(await loadAudioButton.isDisabled(),'the successful audio load remains disabled');
  await loadAudioButton.evaluate(node=>node.dispatchEvent(new MouseEvent('click',{bubbles:true})));
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>/\/audio(?:\?|$)/.test(item.path)).length),1,'repeated load invocation sends no second audio GET');
  assert.equal(await page.evaluate(()=>window.__createdObjectUrls.length),1,'repeated load invocation creates no replacement URL');
  assert.equal(await panel.locator('.memory-book-editorial-audio-box audio').count(),1,'repeated load invocation keeps one player');
  await textInspect.click();await panel.getByText('synthetic family contribution',{exact:true}).waitFor({state:'visible'});
  assert.equal(await page.evaluate(()=>window.__revokedObjectUrls.length),1,'changing source clears and revokes the prior player URL');
  await loadedPlayer.evaluate(player=>{player.pause=()=>{window.__stalePlayPauseCount=(window.__stalePlayPauseCount||0)+1;};player.dispatchEvent(new Event('play'));});
  assert.equal(await page.evaluate(()=>window.__stalePlayPauseCount),1,'a late play event from an inactive source is paused');
  await page.evaluate(()=>{window.__failInspectionStatus=404;});await audioInspect.click();
  await panel.locator('.memory-book-editorial-inspection-status').first().waitFor({state:'visible'});
  assert.equal(await panel.getByText('synthetic family contribution',{exact:true}).count(),0,'404 does not leave earlier source text visible');
  await page.evaluate(()=>{window.__failInspectionStatus=403;});await textInspect.click();
  await page.waitForFunction(()=>document.querySelectorAll('.memory-book-editorial-inspection-status').length>=2);
  assert(await page.evaluate(()=>window.__requestErrors.some(item=>item.status===403)),'protected denial follows the existing reportBook path');
  assert.equal(await panel.getByText('synthetic family contribution',{exact:true}).count(),0,'protected denial also clears the prior source');
  const sourceTwoPath=`/memory-community/v1/stories/${secondStoryId}/contributions/${secondTextSourceId}`;
  const sourceTwoButton=panel.locator(`fieldset.memory-book-editorial-sources button[data-source-id="${secondTextSourceId}"]`).first();
  await page.evaluate(path=>{window.__holdNextInspect=path;},sourceTwoPath);await sourceTwoButton.click();await page.waitForFunction(()=>window.__inspectWaiting);
  await sourceTwoButton.locator('xpath=..').locator('input[type=checkbox]').check();await page.evaluate(()=>window.__releaseInspection());await page.waitForFunction(()=>!window.__inspectWaiting);
  assert.equal(await panel.locator('.memory-book-editorial-inspection').count(),0,'source-choice mutation discards a held detail response');
  await page.evaluate(path=>{window.__holdNextInspect=path;},sourceTwoPath);await panel.locator(`button[data-source-id="${secondTextSourceId}"]`).first().click();await page.waitForFunction(()=>window.__inspectWaiting);
  await page.evaluate(async()=>window.__community.books(document.querySelector('#book-shelf')));await page.evaluate(()=>window.__releaseInspection());await page.waitForFunction(()=>!window.__inspectWaiting);
  assert.equal(await page.locator('.memory-book-editorial-inspection').count(),0,'memoir shelf refresh discards a held detail response');
  await page.locator('.memory-book-edit').first().click();await page.locator('.memory-book-editorial-panel').waitFor({state:'attached'});await page.locator('.memory-book-editorial-panel summary').click();
  await page.evaluate(path=>{window.__holdNextInspect=path;},sourceTwoPath);await page.locator(`.memory-book-editorial-panel button[data-source-id="${secondTextSourceId}"]`).first().click();await page.waitForFunction(()=>window.__inspectWaiting);
  await page.evaluate(async()=>{window.__scope.account='changed-account';window.__scope.library='family-b';await window.__community.books(document.querySelector('#book-shelf'));});await page.evaluate(()=>window.__releaseInspection());await page.waitForFunction(()=>!window.__inspectWaiting);
  assert.equal(await page.locator('.memory-book-editorial-inspection').count(),0,'account and library change discards a held detail response');
  await page.evaluate(async()=>{window.__scope.account='synthetic-owner';window.__scope.library='family-a';await window.__community.books(document.querySelector('#book-shelf'));});
  await page.locator('.memory-book-edit').first().click();await page.locator('.memory-book-editorial-panel').waitFor({state:'attached'});await page.locator('.memory-book-editorial-panel summary').click();
  await page.locator(`.memory-book-editorial-panel button[data-source-id="${audioSourceId}"]`).first().click();await page.getByRole('button',{name:'Load original recording'}).waitFor({state:'visible'});
  const createdBeforeLateAudio=await page.evaluate(()=>window.__createdObjectUrls.length),audioPath=`/memory-community/v1/stories/${firstStoryId}/contributions/${audioSourceId}/audio`;
  await page.evaluate(path=>{window.__holdNextInspect=path;},audioPath);await page.getByRole('button',{name:'Load original recording'}).click();await page.waitForFunction(()=>window.__inspectWaiting);
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await page.evaluate(()=>window.__releaseInspection());await page.waitForFunction(()=>!window.__inspectWaiting);
  assert.equal(await page.evaluate(()=>window.__createdObjectUrls.length),createdBeforeLateAudio,'backgrounded late audio never creates a player URL');assert.equal(await page.locator('.memory-book-editorial-audio-box audio').count(),0,'backgrounded late audio never creates a player');
  await page.evaluate(()=>{delete document.hidden;Object.defineProperty(document,'hidden',{configurable:true,value:false});});await page.evaluate(async()=>window.__community.books(document.querySelector('#book-shelf')));
  await page.locator('.memory-book-edit').first().click();await page.locator('.memory-book-editorial-panel').waitFor({state:'attached'});await page.locator('.memory-book-editorial-panel summary').click();
  const transitionSource=fieldsets.nth(1).locator('input[type=checkbox]').first();await transitionSource.click();assert.equal(await transitionSource.isChecked(),false,'blank transition cannot acquire a source citation');
  await fieldsets.nth(0).locator('input[type=checkbox]').first().check();
  await panel.locator('textarea').fill('Our family kept this moment in a different story.');
  await transitionSource.check();
  await panel.locator('textarea').fill('');await panel.getByRole('button',{name:'Save references and transitions'}).click();
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).length),0,'blank transition with a selected citation is rejected before sending');
  await panel.locator('textarea').fill('Our family kept this moment in a different story.');
  await page.evaluate(()=>{window.__failEditorial=503;});
  await panel.getByRole('button',{name:'Save references and transitions'}).click();
  await panel.getByRole('button',{name:'Retry the same save'}).waitFor({state:'visible'});
  assert.equal(await panel.locator('textarea').inputValue(),'Our family kept this moment in a different story.','uncertain save preserves authored text');
  assert(await panel.locator('textarea').isDisabled(),'an unresolved mutation freezes its visible text');
  assert(await page.locator('.memory-community-book-form button[type=submit]').isDisabled(),'independent book save is blocked while editorial outcome is uncertain');
  const bookSavesBefore=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&!item.path.includes('/editorial')).length);
  await page.locator('.memory-community-book-form').evaluate(form=>form.requestSubmit());
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&!item.path.includes('/editorial')).length),bookSavesBefore);
  const beforeRetry=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).at(-1).body);
  await panel.getByRole('button',{name:'Retry the same save'}).click();
  await page.waitForFunction(()=>document.querySelector('.memory-book-editorial-panel textarea')?.value==='Our family kept this moment in a different story.');
  const puts=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).map(item=>item.body));
  assert.equal(puts.length,2);assert.equal(puts[1],beforeRetry,'uncertain retry sends byte-identical JSON');
  const stored=JSON.parse(puts[1]);assert.equal(stored.transitions[0].source_refs.length,1);assert.equal(stored.introduction_source_refs.length,1);
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='GET'&&/\/stories\/[^/]+\/contributions\/[^/?]+(?:\/audio)?(?:\?|$)/.test(item.path)).length),11,'source endpoint reads correspond only to explicit inspection and stale-response probes');

  // A definitive conflict retains the draft, requires a current read, then an
  // explicit save. The server state changes only on that final user action.
  const priorBookReads=await page.evaluate(id=>window.__memoryRequests.filter(item=>item.method==='GET'&&item.path.startsWith(`/memory-community/v1/books/${id}?`)).length,bookId);
  await page.locator('.memory-book-edit').first().click();
  await page.waitForFunction(({id,count})=>window.__memoryRequests.filter(item=>item.method==='GET'&&item.path.startsWith(`/memory-community/v1/books/${id}?`)).length>count,{id:bookId,count:priorBookReads});
  await page.waitForTimeout(300);await page.waitForFunction(()=>document.querySelectorAll('.memory-book-editorial-panel fieldset.memory-book-editorial-sources input:checked').length===2);
  await page.locator('.memory-community-book-form input[name="title"]').fill('Title draft kept through editorial conflict');
  await page.locator('.memory-community-book-form textarea[name="introduction"]').fill('Opening draft kept through editorial conflict');
  await panel.locator('summary').click().catch(()=>{});
  await page.locator('.memory-book-editorial-panel textarea').fill('A revised family-written transition.');
  await page.evaluate(()=>{window.__failEditorial=409;});
  await page.locator('.memory-book-editorial-save').click();
  await page.locator('.memory-book-editorial-panel summary').click();
  await page.getByRole('button',{name:'Reload current version'}).waitFor({state:'visible'});
  assert.equal(await page.locator('.memory-book-editorial-panel textarea').inputValue(),'A revised family-written transition.');
  assert.equal(await page.locator('.memory-community-book-form input[name="title"]').inputValue(),'Title draft kept through editorial conflict','409 rerender retains title draft before current-version reload');
  assert.equal(await page.locator('.memory-community-book-form textarea[name="introduction"]').inputValue(),'Opening draft kept through editorial conflict','409 rerender retains opening draft before current-version reload');
  await page.getByRole('button',{name:'Reload current version'}).click();
  await page.waitForFunction(()=>document.querySelector('.memory-book-editorial-panel textarea')?.value==='A revised family-written transition.'&&!document.querySelector('.memory-book-editorial-save')?.disabled);
  assert.equal(await page.locator('.memory-book-editorial-save').isEnabled(),true,'save is enabled only after the explicit current-version reload');
  assert.equal(await page.locator('.memory-community-book-form input[name="title"]').inputValue(),'Title draft kept through editorial conflict');
  assert.equal(await page.locator('.memory-community-book-form textarea[name="introduction"]').inputValue(),'Opening draft kept through editorial conflict');
  await page.locator('.memory-book-editorial-panel summary').first().click();
  await page.locator('.memory-book-editorial-save').click();
  await page.waitForFunction(()=>document.querySelectorAll('.memory-book-editorial-panel fieldset.memory-book-editorial-sources input:checked').length===2&&document.querySelector('.memory-book-editorial-panel textarea')?.value==='A revised family-written transition.'&&!document.querySelector('.memory-book-editorial-panel textarea').disabled&&!document.querySelector('.memory-book-editorial-save').disabled);

  assert.equal(await page.locator('.memory-community-book-form input[name=title]').inputValue(),'Title draft kept through editorial conflict','successful editorial save preserves independent title draft');
  assert.equal(await page.locator('.memory-community-book-form textarea[name=introduction]').inputValue(),'Opening draft kept through editorial conflict','successful editorial save preserves independent opening draft');

  // A language rerender during a committed-but-held response detaches the old
  // form. Completion must use the stable shelf and retain independent drafts.
  await page.locator('.memory-book-editorial-panel summary').first().evaluate(node=>{node.parentElement.open=true;});
  await page.locator('.memory-book-editorial-panel textarea').fill('A passage saved across a language change.');
  await page.evaluate(()=>{window.__holdNextEditorial=true;});await page.locator('.memory-book-editorial-save').click();
  await page.waitForFunction(()=>window.__editorialWaiting===true);
  await page.evaluate(async()=>{window.__scope.language='zh';await window.__community.translate();});
  assert(await page.locator('.memory-book-editorial-save').isDisabled());
  assert(await page.locator('.memory-book-editorial-panel textarea').isDisabled());
  await page.evaluate(()=>window.__releaseEditorial());
  await page.waitForFunction(()=>document.querySelector('.memory-book-editorial-panel textarea')?.value==='A passage saved across a language change.'&&!document.querySelector('.memory-book-editorial-panel textarea').disabled&&!document.querySelector('.memory-book-editorial-save').disabled);
  assert.equal(await page.locator('.memory-community-book-form input[name=title]').inputValue(),'Title draft kept through editorial conflict');
  assert.equal(await page.locator('.memory-community-book-form textarea[name=introduction]').inputValue(),'Opening draft kept through editorial conflict');
  await page.locator('.memory-book-editorial-panel summary').first().evaluate(node=>{node.parentElement.open=true;});
  assert.match(await page.locator('.memory-book-editorial-sources').first().textContent(),/第 1 章/,'source labels follow the current interface language');
  await page.evaluate(async()=>{window.__scope.language='en';await window.__community.translate();});

  // Deleting a cited original invalidates the historical sidecar. The UI hides
  // its stale prose and requires an explicit fresh draft from current stories.
  const deleted=await rpc({command:'delete-source'});assert.equal(deleted.status,200);
  await page.locator('.memory-book-edit').first().click();
  await page.waitForFunction(()=>document.querySelector('.memory-book-editorial-panel')?.textContent.includes('source or story revision changed'));
  await page.locator('.memory-book-editorial-panel summary').click();
  assert.equal(await page.locator('.memory-book-editorial-panel textarea').count(),0,'stale transition prose is not shown after source invalidation');
  await page.getByRole('button',{name:'Start a fresh draft from current stories'}).click();
  assert.equal(await page.locator('.memory-book-editorial-panel textarea').count(),1);
  await page.locator('.memory-book-editorial-panel summary').first().evaluate(node=>{node.parentElement.open=true;});
  await page.locator('.memory-book-editorial-panel textarea').fill('家人后来又讲起那段旅程。');
  await page.evaluate(async()=>{window.__scope.language='zh';await window.__community.translate();document.documentElement.style.zoom='1.5';});
  await page.waitForFunction(()=>document.querySelector('.memory-book-editorial-panel textarea')?.value==='家人后来又讲起那段旅程。');
  await page.locator('.memory-book-editorial-panel summary').click();
  assert.match(await page.locator('.memory-book-editorial-panel').innerText(),/家人撰写/);

  assert.deepEqual(external,[]);
  const sourceTwoFinal=page.locator(`.memory-book-editorial-panel button[data-source-id="${secondTextSourceId}"]`).first();await sourceTwoFinal.click();await page.locator('.memory-book-editorial-original-text').waitFor({state:'visible'});
  assert.equal(await page.locator('.memory-book-editorial-original-text').innerText(),'synthetic family contribution');assert.match(await page.locator('.memory-book-editorial-derived').innerText(),/synthetic dictated words/);assert.match(await page.locator('.memory-book-editorial-derived').innerText(),/synthetic derived draft/,'transcript and polished draft remain explicitly derived from original words');
  await page.evaluate(()=>{window.__scope.language='zh';document.documentElement.style.zoom='1.5';});await page.evaluate(async()=>window.__community.translate());await page.locator('.memory-book-editorial-panel summary').first().evaluate(node=>{node.parentElement.open=true;});
  const inspectZh=page.locator(`.memory-book-editorial-panel button[data-source-id="${secondTextSourceId}"]`).first();await inspectZh.click();await page.locator('.memory-book-editorial-original-text').waitFor({state:'visible'});await page.locator('.memory-book-editorial-inspection').scrollIntoViewIfNeeded();
  const zhMobile=path.join(artifacts,'memoir-source-inspector-zh-390px-150.png');await page.screenshot({path:zhMobile});
  const zhFull=path.join(artifacts,'memoir-source-inspector-zh-390px-150-full.png');await page.screenshot({path:zhFull,fullPage:true});
  await page.evaluate(()=>{window.__scope.language='en';document.documentElement.style.zoom='1.5';});await page.evaluate(async()=>window.__community.translate());await page.locator('.memory-book-editorial-panel summary').first().evaluate(node=>{node.parentElement.open=true;});
  const inspectEn=page.locator(`.memory-book-editorial-panel button[data-source-id="${secondTextSourceId}"]`).first();await inspectEn.click();await page.locator('.memory-book-editorial-original-text').waitFor({state:'visible'});await page.locator('.memory-book-editorial-inspection').scrollIntoViewIfNeeded();
  const enMobile=path.join(artifacts,'memoir-source-inspector-en-390px-150.png');await page.screenshot({path:enMobile});
  const enFull=path.join(artifacts,'memoir-source-inspector-en-390px-150-full.png');await page.screenshot({path:enFull,fullPage:true});
  const mobileFit=await page.locator('.memory-book-editorial-inspection').evaluate(node=>{const box=node.getBoundingClientRect();return {left:box.left,right:box.right,viewport:document.documentElement.clientWidth,close:node.parentElement.querySelector('.memory-book-editorial-inspect')?.getBoundingClientRect().right,original:node.querySelector('.memory-book-editorial-original-text')?.getBoundingClientRect().right};});
  assert(mobileFit.left>=0&&mobileFit.right<=mobileFit.viewport+1&&mobileFit.close<=mobileFit.viewport+1&&mobileFit.original<=mobileFit.viewport+1,'390px inspection fits without horizontal overflow at 150% zoom');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),'the complete mobile page has no horizontal overflow');
  await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{document.documentElement.style.zoom='1';});await page.locator('.memory-book-editorial-inspection').scrollIntoViewIfNeeded();
  const desktop=path.join(artifacts,'memoir-source-inspector-en-1280px.png');await page.screenshot({path:desktop});

  const largeCatalog=await rpc({command:'large-catalog'});assert.equal(largeCatalog.created,22,'large fixture expands the eligible catalog to 24 rows including two original baseline rows');
  const largeReadsBefore=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='GET'&&/\/stories\/[^/]+\/contributions\/[^/?]+(?:\/audio)?(?:\?|$)/.test(item.path)).length),largeAudioBefore=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='GET'&&/\/audio(?:\?|$)/.test(item.path)).length);
  await page.evaluate(async()=>window.__community.books(document.querySelector('#book-shelf')));await page.locator('.memory-book-edit').first().click();
  await page.locator('.memory-book-editorial-panel').waitFor({state:'attached'});
  const chooserPanel=page.locator('.memory-book-editorial-panel');await chooserPanel.locator('summary').click();
  const startFresh=page.getByRole('button',{name:'Start a fresh draft from current stories'});if(await startFresh.count()){await startFresh.click();await chooserPanel.locator('summary').click();}
  const chooser=chooserPanel.locator('fieldset.memory-book-editorial-sources').first();
  await page.waitForTimeout(300);const initialChooserText=await chooserPanel.innerText();if(!initialChooserText.includes('24 available'))throw new Error(`Large chooser fixture did not render 24 options: ${initialChooserText.slice(0,900)}`);
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='GET'&&/\/stories\/[^/]+\/contributions\/[^/?]+(?:\/audio)?(?:\?|$)/.test(item.path)).length),largeReadsBefore,'opening a large chooser does not fetch original details or audio');
  const choices=chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice');assert.equal(await choices.count(),12,'only 12 eligible source rows appear on one page');
  assert.match(await chooser.locator('.memory-book-editorial-pages').innerText(),/Page 1 of 2/);
  const chooserDetailPath=(id,story=firstStoryId)=>`/memory-community/v1/stories/${story}/contributions/${id}`;
  let pendingSourceId=await choices.first().locator('button[data-source-id]').getAttribute('data-source-id');
  await page.evaluate(({path,story})=>{window.__holdNextInspect=path;window.__firstStoryId=story;},{path:chooserDetailPath(pendingSourceId),story:firstStoryId});
  await choices.first().locator('button[data-source-id]').click();await page.waitForFunction(()=>window.__inspectWaiting);
  await chooser.getByRole('button',{name:'Next page'}).click();await page.waitForFunction(()=>!document.querySelector('.memory-book-editorial-inspection'));
  await page.evaluate(()=>window.__releaseInspection());await page.waitForFunction(()=>!window.__inspectWaiting);
  assert.equal(await chooser.locator('.memory-book-editorial-original-text').count(),0,'paging clears and fences a held inspection response');
  assert.equal(await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').count(),12);
  assert.match(await chooser.locator('.memory-book-editorial-pages').innerText(),/Page 2 of 2/);
  pendingSourceId=await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').first().locator('button[data-source-id]').getAttribute('data-source-id');
  await page.evaluate(({path,story})=>{window.__holdNextInspect=path;window.__firstStoryId=story;},{path:chooserDetailPath(pendingSourceId,secondStoryId),story:firstStoryId});
  await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').first().locator('button[data-source-id]').click();await page.waitForFunction(()=>window.__inspectWaiting);
  const search=chooser.getByLabel('Search sources');await search.fill('Editorial child one');
  assert.equal(await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').count(),12,'local story-title filter matches one story without fetching source details');
  assert.match(await chooser.locator('.memory-book-editorial-counts').innerText(),/12 matches; 24 available/);
  assert.equal(await chooser.locator('.memory-book-editorial-inspection').count(),0,'filtering clears the inspected row and fences its pending response');
  await page.evaluate(()=>window.__releaseInspection());await page.waitForFunction(()=>!window.__inspectWaiting);
  assert.equal(await chooser.locator('.memory-book-editorial-original-text').count(),0,'late filtered detail cannot restore original words');
  await chooser.locator('.memory-book-editorial-choice-list input[type=checkbox]').first().check();
  await chooser.getByRole('button',{name:'Clear filter'}).click();assert.equal(await search.inputValue(),'');
  await chooser.getByRole('button',{name:'Next page'}).click();await chooser.locator('.memory-book-editorial-choice-list input[type=checkbox]').first().check();
  assert.match(await chooser.locator('.memory-book-editorial-counts').innerText(),/2 selected/,'selections on both pages remain selected');
  await chooser.getByRole('button',{name:'Previous page'}).click();await search.fill('Editorial child two');
  assert.match(await chooser.locator('.memory-book-editorial-counts').innerText(),/12 matches; 24 available; 2 selected \(1 selected outside this view\)/,'counts disclose a selected source hidden by the filter');
  await search.fill('no matching synthetic source');assert.equal(await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').count(),0);
  assert.match(await chooser.locator('.memory-book-editorial-choice-list').innerText(),/No sources match this filter/);
  assert.match(await chooser.locator('.memory-book-editorial-counts').innerText(),/2 selected \(2 selected outside this view\)/,'no-match filtering does not clear hidden selections');
  await chooser.getByRole('button',{name:'Clear filter'}).click();
  await search.fill('Chapter 1');assert.equal(await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').count(),12,'chapter-label search remains capped at one page');
  assert.match(await chooser.locator('.memory-book-editorial-counts').innerText(),/24 matches; 24 available/);
  await chooser.getByRole('button',{name:'Clear filter'}).click();
  await search.fill('Recall 12');assert.equal(await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').count(),2,'recall-label search matches the local catalog ordinal');
  await chooser.getByRole('button',{name:'Clear filter'}).click();
  const largeReadsAfter=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='GET'&&/\/stories\/[^/]+\/contributions\/[^/?]+(?:\/audio)?(?:\?|$)/.test(item.path)).length);
  assert.equal(largeReadsAfter-largeReadsBefore,2,'only two explicit held source inspections requested details');
  const largeAudioAfter=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='GET'&&/\/audio(?:\?|$)/.test(item.path)).length);assert.equal(largeAudioAfter,largeAudioBefore,'filtering and paging never load audio');
  const refsBeforeLargeSave=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).length);
  await chooserPanel.getByRole('button',{name:'Save references and transitions'}).click();
  await page.waitForFunction(count=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).length>count,refsBeforeLargeSave);
  const largeSave=await page.evaluate(()=>JSON.parse(window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).at(-1).body));
  assert.equal(largeSave.introduction_source_refs.length,2,'selected references from separate pages are saved unchanged');
  const editorialReadPath=`/memory-community/v1/books/${bookId}/editorial`;
  let editorialReads=await page.evaluate(path=>window.__memoryRequests.filter(item=>item.method==='GET'&&item.path.startsWith(path)).length,editorialReadPath);
  await page.locator('.memory-book-edit').first().click();await page.waitForFunction(({path,count})=>window.__memoryRequests.filter(item=>item.method==='GET'&&item.path.startsWith(path)).length>count,{path:editorialReadPath,count:editorialReads});
  await chooserPanel.locator('summary').click();await page.waitForFunction(()=>document.querySelectorAll('.memory-book-editorial-sources').item(0)?.querySelectorAll('.memory-book-editorial-choice-list input:checked').length===1);
  assert.equal(await chooser.locator('.memory-book-editorial-choice-list input:checked').count(),1,'reopened page one shows its saved reference');
  await chooser.getByRole('button',{name:'Next page'}).click();assert.equal(await chooser.locator('.memory-book-editorial-choice-list input:checked').count(),1,'reopened page two shows its saved reference');

  await chooser.locator('.memory-book-editorial-choice-list input:checked').focus();await page.keyboard.press('Space');
  await chooser.getByRole('button',{name:'Previous page'}).click();await chooser.locator('.memory-book-editorial-choice-list input:checked').focus();await page.keyboard.press('Space');
  await chooser.getByRole('button',{name:'Next page'}).click();
  const recallSevenRow=choices.filter({hasText:'Editorial child two'}).filter({hasText:'Recall 7'}).first();
  assert.equal(await recallSevenRow.count(),1,'the identity-stability case selects a distinct page-two recall label');
  const recallSeven=recallSevenRow.locator('input[type="checkbox"]'),recallSevenKey=await recallSeven.getAttribute('data-ref-key');
  await recallSeven.focus();const scrollBeforeKeyboard=await page.evaluate(()=>window.scrollY);await page.keyboard.press('Space');
  const keyboardFocus=await page.evaluate(()=>({key:document.activeElement?.dataset?.refKey,scroll:window.scrollY}));
  assert.equal(keyboardFocus.key,recallSevenKey,'space selection preserves keyboard focus on the same source identity');
  assert.equal(keyboardFocus.scroll,scrollBeforeKeyboard,'selection rerender does not jump the viewport');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(key=>document.activeElement?.classList.contains('memory-book-editorial-inspect')&&document.activeElement.dataset.sourceId===JSON.parse(key)[3],recallSevenKey),true,'Tab proceeds from the selected checkbox to that source inspection control');
  await page.evaluate(()=>{window.__scope.language='zh';});await page.evaluate(async()=>window.__community.translate());await chooserPanel.locator('summary').click();
  assert.match(await chooser.locator('.memory-book-editorial-pages').innerText(),/第 1 页，共 2 页/,'locale change resets the source list to page one');
  assert.equal(await chooser.locator('.memory-book-editorial-choice-list input:checked').count(),0,'translation does not copy page-two checked state onto page-one identities');
  await chooser.getByRole('button',{name:'下一页'}).click();
  assert.equal(await chooser.locator('.memory-book-editorial-choice-list').evaluate((node,key)=>[...node.querySelectorAll('input[data-ref-key]')].find(input=>input.dataset.refKey===key)?.checked||false,recallSevenKey),true,'translation renders the original selected identity on page two');
  const refsBeforeIdentitySave=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).length);
  await chooserPanel.getByRole('button',{name:'保存引用与衔接'}).click();
  await page.waitForFunction(count=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).length>count,refsBeforeIdentitySave);
  const identitySave=await page.evaluate(()=>JSON.parse(window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).at(-1).body));
  assert.deepEqual(identitySave.introduction_source_refs.map(ref=>ref.contribution_id),[JSON.parse(recallSevenKey)[3]],'saving after translation preserves exactly the selected source identity');
  await page.evaluate(()=>{window.__scope.language='en';});await page.evaluate(async()=>window.__community.translate());await chooserPanel.locator('summary').click();

  await page.evaluate(()=>window.__injectUnavailableEditorial=true);editorialReads=await page.evaluate(path=>window.__memoryRequests.filter(item=>item.method==='GET'&&item.path.startsWith(path)).length,editorialReadPath);
  await page.locator('.memory-book-edit').first().click();await page.waitForFunction(({path,count})=>window.__memoryRequests.filter(item=>item.method==='GET'&&item.path.startsWith(path)).length>count,{path:editorialReadPath,count:editorialReads});
  await chooserPanel.locator('summary').click();await chooser.locator('.memory-book-editorial-unavailable-list input[type=checkbox]').waitFor({state:'visible'});assert(await chooser.locator('.memory-book-editorial-unavailable-list input[type=checkbox]').isChecked());
  await chooser.getByLabel('Search sources').fill('no matching synthetic source');
  assert.equal(await chooser.locator('.memory-book-editorial-unavailable-list input[type=checkbox]').count(),1,'unavailable selected reference stays visible with no matching eligible rows');
  const unavailableRemoval=chooser.locator('.memory-book-editorial-unavailable-list input[type=checkbox]');await unavailableRemoval.focus();await page.keyboard.press('Space');assert.equal(await chooser.locator('.memory-book-editorial-unavailable-list input[type=checkbox]').count(),0,'unavailable selected reference can be explicitly removed');
  const removalFocus=await page.evaluate(()=>({tag:document.activeElement?.tagName,className:document.activeElement?.className,type:document.activeElement?.type,connected:document.activeElement?.isConnected}));
  assert.equal(await page.evaluate(()=>document.activeElement?.matches('.memory-book-editorial-choice-list input[data-ref-key],.memory-book-editorial-search')),true,`removing an unavailable reference leaves focus on a remaining source or search control: ${JSON.stringify(removalFocus)}`);

  await page.evaluate(()=>{window.__scope.language='zh';document.documentElement.style.zoom='1.5';});await page.evaluate(async()=>window.__community.translate());
  await chooserPanel.locator('summary').click();
  const zhSearch=chooser.getByLabel('搜索来源');assert.equal(await zhSearch.inputValue(),'','locale change clears the local filter');
  const zhPageText=await chooser.locator('.memory-book-editorial-pages').innerText();assert.match(zhPageText,/第 1 页，共 2 页/,`locale change resets pagination to page one: ${zhPageText}`);
  assert.equal(await chooser.locator('.memory-book-editorial-choice-list .memory-book-editorial-choice').count(),12);
  const chooserZh=path.join(artifacts,'memoir-source-chooser-zh-390px-150.png');await page.setViewportSize({width:390,height:844});await chooser.evaluate(node=>window.scrollTo(0,node.getBoundingClientRect().top+window.scrollY-24));await page.screenshot({path:chooserZh});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),'large Chinese chooser remains within 390 px at 150% zoom');
  await zhSearch.fill('Editorial child two');await page.evaluate(async()=>{window.__scope.account='changed-account';window.__scope.library='family-b';await window.__community.books(document.querySelector('#book-shelf'));});
  await page.evaluate(async()=>{window.__scope.account='synthetic-owner';window.__scope.library='family-a';window.__scope.language='en';await window.__community.books(document.querySelector('#book-shelf'));});
  await page.locator('.memory-book-edit').first().click();await page.locator('.memory-book-editorial-panel').waitFor({state:'attached'});await page.locator('.memory-book-editorial-panel summary').click();
  const reloadedChooser=page.locator('.memory-book-editorial-panel fieldset.memory-book-editorial-sources').first();assert.equal(await reloadedChooser.getByLabel('Search sources').inputValue(),'','account/library change starts with a clear local filter');
  assert.match(await reloadedChooser.locator('.memory-book-editorial-pages').innerText(),/Page 1 of 2/,'account/library change resets to the first page');
  assert.equal(await reloadedChooser.locator('.memory-book-editorial-choice-list input:checked').count(),0,'scope reload page one does not inherit a page-two checked position');
  await reloadedChooser.getByRole('button',{name:'Next page'}).click();
  assert.equal(await reloadedChooser.locator('.memory-book-editorial-choice-list').evaluate((node,key)=>[...node.querySelectorAll('input[data-ref-key]')].find(input=>input.dataset.refKey===key)?.checked||false,recallSevenKey),true,'scope reload keeps the saved source checked by identity on page two');
  await reloadedChooser.getByRole('button',{name:'Previous page'}).click();
  await page.evaluate(()=>{document.documentElement.style.zoom='1.5';});await reloadedChooser.scrollIntoViewIfNeeded();
  const chooserEn=path.join(artifacts,'memoir-source-chooser-en-390px-150.png');await page.locator('.memory-book-editorial-panel fieldset.memory-book-editorial-sources').first().evaluate(node=>window.scrollTo(0,node.getBoundingClientRect().top+window.scrollY-24));await page.screenshot({path:chooserEn});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),'large English chooser remains within 390 px at 150% zoom');
  const chooserText=await reloadedChooser.innerText();assert.equal(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.test(chooserText),false,'chooser labels do not expose technical identifiers');

  await page.evaluate(()=>{window.__failEditorial=503;});await chooserPanel.getByRole('button',{name:'Save references and transitions'}).click();
  await chooserPanel.getByRole('button',{name:'Retry the same save'}).waitFor({state:'visible'});
  const frozenEditorialBody=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).at(-1).body);
  await page.evaluate(()=>{window.__holdNextEditorial=true;});await chooserPanel.getByRole('button',{name:'Retry the same save'}).click();await page.waitForFunction(()=>window.__editorialWaiting);
  const retryChooser=page.locator('.memory-book-editorial-panel fieldset.memory-book-editorial-sources').first();await retryChooser.getByRole('button',{name:'Next page'}).click();
  const retryPageInputs=retryChooser.locator('.memory-book-editorial-choice-list input[type=checkbox]');assert.equal(await retryPageInputs.count(),12);assert.equal(await retryPageInputs.evaluateAll(nodes=>nodes.every(node=>node.disabled)),true,'pagination during an uncertain retry renders disabled source controls');
  const uncheckedRetryIndex=await retryPageInputs.evaluateAll(nodes=>nodes.findIndex(node=>!node.checked));assert(uncheckedRetryIndex>=0,'the retry page has an unselected eligible source');const uncheckedRetryInput=retryPageInputs.nth(uncheckedRetryIndex);
  const forcedRetryState=await uncheckedRetryInput.evaluate(input=>{input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));return input.checked;});
  assert.equal(forcedRetryState,false,'a forced change event cannot mutate frozen references');
  assert.equal(await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).at(-1).body),frozenEditorialBody,'pagination and a forced event leave the frozen retry body unchanged');
  await page.evaluate(()=>window.__releaseEditorial());await page.waitForFunction(()=>!window.__editorialWaiting&&document.querySelector('.memory-book-editorial-save')?.textContent==='Save references and transitions');
  const frozenRetryBodies=await page.evaluate(()=>window.__memoryRequests.filter(item=>item.method==='PUT'&&/\/editorial(?:\?|$)/.test(item.path)).slice(-2).map(item=>item.body));
  assert.deepEqual(frozenRetryBodies,[frozenEditorialBody,frozenEditorialBody],'uncertain retry sends byte-identical JSON after paging');
  assert.deepEqual(external,[]);
  console.log(`PASS default-off fallback; eligible citation-only inspection; original/derivative separation; explicit audio load and URL cleanup; stale inspection fencing; 24-source local search and 12-row paging; hidden/unavailable selection retention/removal; save/reopen and locale/scope reset; responsive renders ${zhMobile} ${zhFull} ${enMobile} ${enFull} ${desktop} ${chooserZh} ${chooserEn}`);
})().catch(error=>{console.error(error.stack||error);process.exitCode=1;}).finally(async()=>{try{await context?.close();}catch(_){}try{await browser?.close();}catch(_){}try{bridge.stdin.write(JSON.stringify({command:'quit'})+'\n');bridge.stdin.end();}catch(_){}});
