'use strict';
/* Real browser -> closed ASGI -> SQLite leave-confirmation journey. */
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {createInterface}=require('node:readline');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||process.env.PLAYWRIGHT_MODULE_PATH||'playwright-core');
const root=path.resolve(__dirname,'../..'),artifacts=process.env.PH_BROWSER_ARTIFACTS||fs.mkdtempSync(path.join(os.tmpdir(),'photohouse-reader-leave-'));
fs.mkdirSync(artifacts,{recursive:true});console.log('ARTIFACTS_DIR '+artifacts);
const bridge=spawn(process.env.PH_BROWSER_PYTHON||path.join(root,'.venv/bin/python'),[path.join(__dirname,'memory_community_browser_bridge.py')],{cwd:root,stdio:['pipe','pipe','pipe']});
let serial=0,readyResolve,readyReject;const pending=new Map(),requests=[],dialogs=[],errors=[];
const ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
bridge.stderr.on('data',chunk=>process.stderr.write(chunk));createInterface({input:bridge.stdout}).on('line',line=>{const result=JSON.parse(line);if(result.ready){readyResolve();return;}const call=pending.get(result.id);if(call){pending.delete(result.id);call.resolve(result);}});
bridge.on('exit',code=>{if(code){readyReject(new Error(`Browser bridge failed (${code})`));for(const call of pending.values())call.reject(new Error('Browser bridge failed'));}});
const rpc=message=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});bridge.stdin.write(JSON.stringify({...message,id})+'\n');});
let browser,context,page,dialogDecision='dismiss',holdBookParent=false,bookParentArrivedResolve,bookParentReleaseResolve,onDialog;
const count=(method,pattern)=>requests.filter(item=>item.method===method&&pattern.test(item.path)).length;
const setDialog=decision=>{dialogDecision=decision;};
(async()=>{
  await ready;const audioPath=path.join(artifacts,'synthetic-microphone.wav'),frames=48000,data=Buffer.alloc(frames*2),wav=Buffer.alloc(44+data.length);wav.write('RIFF',0);wav.writeUInt32LE(wav.length-8,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(data.length,40);data.copy(wav,44);fs.writeFileSync(audioPath,wav);
  browser=await chromium.launch({headless:true,...(process.env.PH_BROWSER_EXECUTABLE?{executablePath:process.env.PH_BROWSER_EXECUTABLE}:{}),args:['--disable-background-networking','--disable-component-update','--no-first-run','--host-resolver-rules=MAP * ~NOTFOUND','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--use-file-for-fake-audio-capture='+audioPath]});
  context=await browser.newContext({viewport:{width:1280,height:960},serviceWorkers:'block',permissions:['microphone']});
  await context.addInitScript(()=>{const utterances=[];class Utterance{constructor(text){this.text=text;}}const synth={speaking:false,pending:false,paused:false,getVoices:()=>[{lang:'zh-CN',localService:true}],speak(value){utterances.push(value);this.speaking=true;},cancel(){this.speaking=false;}};Object.defineProperty(window,'speechSynthesis',{configurable:true,value:synth});window.SpeechSynthesisUtterance=Utterance;});
  await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!=='https://photohouse.test'){await route.abort();return;}const headers=await request.allHeaders();delete headers['content-length'];if(!headers['sec-fetch-site'])headers['sec-fetch-site']='same-origin';const entry={method:request.method(),path:url.pathname+url.search};requests.push(entry);const result=await rpc({method:entry.method,path:entry.path,headers,body:(request.postDataBuffer()||Buffer.alloc(0)).toString('base64')});entry.status=result.status;if(holdBookParent&&entry.method==='GET'&&/^\/memory-community\/v1\/books\/[0-9a-f-]{36}(?:\?|$)/.test(entry.path)){holdBookParent=false;bookParentArrivedResolve();await new Promise(resolve=>bookParentReleaseResolve=resolve);}const responseHeaders={...result.headers};delete responseHeaders['content-length'];delete responseHeaders['content-encoding'];try{await route.fulfill({status:result.status,headers:responseHeaders,body:Buffer.from(result.body,'base64')});}catch(error){if(!/closed|handled|cancel|Invalid InterceptionId/.test(error.message))throw error;}});
  page=await context.newPage();page.on('pageerror',error=>errors.push(error.stack||error.message));page.on('dialog',async dialog=>{dialogs.push(dialog.message());const wake=onDialog;onDialog=null;if(dialogDecision==='accept')await dialog.accept();else await dialog.dismiss();wake?.();});
  await page.goto('https://photohouse.test/ui');await page.locator('#auth').waitFor();await page.locator('#phone').fill('+12025550100');await page.locator('#password').fill('Synthetic family passphrase!');await page.locator('#auth-submit').click();await page.locator('.saved-memory-card').first().waitFor();
  const openStory=async()=>{await page.locator('.saved-memory-cover').first().click();await page.locator('#story-reader').waitFor({state:'visible'});await page.locator('#story-reader-community .memory-community[data-state=ready]').waitFor();};
  const openChat=async root=>{await root.getByRole('tab',{name:'一起聊回忆',exact:true}).click();await root.getByRole('button',{name:'新建讨论',exact:true}).click();await root.locator('textarea[name=message]').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.memory-chat-conversations button')].some(button=>button.textContent==='新建讨论'&&!button.disabled));};
  await openStory();
  const reader=page.locator('#story-reader'),community=page.locator('#story-reader-community');
  await openChat(community);const message=community.locator('textarea[name=message]');await message.fill('离开前仍需保留的合成消息草稿。');
  const deletesBefore=count('DELETE',/^\/memory-community\/v1\/jobs\//),asrBefore=count('POST',/\/asr|\/transcribe/);
  setDialog('dismiss');await page.locator('#story-reader-close').click();
  assert.match(dialogs.at(-1)||'',/未发送的消息和草稿/,`Chinese leave dialog explains discarded inputs: ${JSON.stringify(dialogs)}`);assert(await reader.isVisible(),'cancel keeps the story reader open');assert.equal(await message.inputValue(),'离开前仍需保留的合成消息草稿。','cancel preserves the unsent composer text');assert.equal(count('DELETE',/^\/memory-community\/v1\/jobs\//),deletesBefore,'cancel sends no pending-job DELETE');
  const storyReads=()=>count('GET',/^\/memory-stories\/[0-9a-f-]{36}(?:\?|$)/),readsBeforeReopen=storyReads(),asrBeforeReopen=count('POST',/\/asr|\/transcribe/),deletesBeforeReopen=count('DELETE',/^\/memory-community\/v1\/jobs\//),threadBeforeReopen=await community.locator('select[name=conversation]').inputValue(),panelBeforeReopen=await community.locator('.memory-community-content').getAttribute('id');
  setDialog('dismiss');await page.locator('.saved-memory-card').nth(1).locator('.saved-memory-cover').evaluate(button=>button.click());
  assert.match(dialogs.at(-1)||'',/未发送的消息和草稿/,'reopening another saved story asks before replacement');assert(await reader.isVisible(),'cancelled target replacement keeps the current reader open');assert.equal(await message.inputValue(),'离开前仍需保留的合成消息草稿。','cancelled target replacement preserves the current composer');assert.equal(await community.locator('select[name=conversation]').inputValue(),threadBeforeReopen,'cancelled target replacement keeps the same conversation selected');assert.equal(await community.locator('.memory-community-content').getAttribute('id'),panelBeforeReopen,'cancelled target replacement keeps the current panel mounted');assert.equal(storyReads(),readsBeforeReopen,'cancelled target replacement does not GET the requested story');assert.equal(count('DELETE',/^\/memory-community\/v1\/jobs\//),deletesBeforeReopen,'cancelled target replacement sends no job DELETE');assert.equal(count('POST',/\/asr|\/transcribe/),asrBeforeReopen,'cancelled target replacement does not transcribe');
  setDialog('accept');await page.locator('#story-reader-close').click();await reader.waitFor({state:'hidden'});assert.equal(count('DELETE',/^\/memory-community\/v1\/jobs\//),deletesBefore,'confirming a draft-only exit does not invent a job cancellation');
  await openStory();setDialog('dismiss');const beforeEmpty=dialogs.length;await page.locator('#story-reader-close').click();await reader.waitFor({state:'hidden'});assert.equal(dialogs.length,beforeEmpty,'empty reader closes without a leave prompt');

  await openStory();await openChat(community);const record=community.getByRole('button',{name:'录一段口述（不会保留录音）',exact:true});await record.click();const stop=community.getByRole('button',{name:'结束录音并识别文字',exact:true});await stop.waitFor();
  setDialog('dismiss');await page.keyboard.press('Escape');assert.match(dialogs.at(-1),/录音会停止/,'Escape dialog explains active recording cancellation');assert(await reader.isVisible(),'cancelling Escape keeps memoir reader open');assert(await stop.isVisible(),'cancelling Escape leaves the active microphone controls intact');assert.equal(count('POST',/\/asr|\/transcribe/),asrBefore,'cancelling Escape does not transcribe or upload the active capture');assert.equal(count('DELETE',/^\/memory-community\/v1\/jobs\//),deletesBefore,'cancelling Escape sends no pending-job DELETE');
  setDialog('accept');await page.keyboard.press('Escape');await reader.waitFor({state:'hidden'});assert.equal(count('POST',/\/asr|\/transcribe/),asrBefore,'confirming Escape stops the temporary capture without transcribing');

  await openStory();await community.getByRole('tab',{name:'家人的声音',exact:true}).click();await community.locator('.memory-community-composer summary').click();const contribution=community.locator('textarea[name=text]');await contribution.fill('离开前仍保留的家人原话草稿。');await community.locator('input[name=byline]').fill('合成署名');
  setDialog('dismiss');await page.locator('#story-reader-related').click();assert(await reader.isVisible(),'cancel keeps reader open for the related-memory action');assert.equal(await contribution.inputValue(),'离开前仍保留的家人原话草稿。','cancel retains original contribution wording');assert.equal(await community.locator('input[name=byline]').inputValue(),'合成署名','cancel retains the byline');assert.equal(count('POST',/\/contributions\/text/),0,'guard cancellation does not save the original contribution');
  setDialog('accept');await page.locator('#story-reader-related').click();await reader.waitFor({state:'hidden'});assert.equal(count('POST',/\/contributions\/text/),0,'confirmed exit discards rather than submitting contribution text');

  const shelf=page.locator('#memory-books');await shelf.waitFor({state:'visible'});await shelf.locator('.memory-book-compose-cta').click();const form=shelf.locator('.memory-community-book-form');await form.waitFor();await form.locator('input[name=title]').fill('离开确认测试回忆集');await form.locator('textarea[name=introduction]').fill('只在合成浏览器中使用。');await form.locator('input[name=story_ids]').first().check();await form.getByRole('button',{name:'保存回忆集'}).click();const bookCard=shelf.locator('.memory-book-card').filter({hasText:'离开确认测试回忆集'});await bookCard.waitFor();await bookCard.getByRole('button',{name:'继续阅读这本回忆集'}).click();const bookReader=page.locator('#memory-book-reader');await bookReader.waitFor({state:'visible'});await bookReader.locator('.memory-book-toc button').first().click();await bookReader.locator('.memory-book-reading-prose').waitFor();
  const memoirCommunity=bookReader.locator('.memory-community');await openChat(memoirCommunity);const memoirDraft=memoirCommunity.locator('textarea[name=message]');await memoirDraft.fill('回忆录中未发送的讨论草稿。');setDialog('dismiss');await bookReader.locator(':scope > header button').click();assert(await bookReader.isVisible(),'cancel preserves the memoir reader');assert.equal(await memoirDraft.inputValue(),'回忆录中未发送的讨论草稿。','cancel preserves the memoir chat draft');setDialog('accept');await bookReader.locator(':scope > header button').click();await bookReader.waitFor({state:'hidden'});
  await bookCard.getByRole('button',{name:'继续阅读这本回忆集'}).click();await bookReader.waitFor({state:'visible'});await bookReader.locator('.memory-book-toc button').first().click();await bookReader.locator('.memory-book-reading-prose').waitFor();await page.waitForFunction(()=>![...document.querySelectorAll('.story-reader-sources-note')].some(node=>node.textContent.includes('正在核实')));const mediaChat=bookReader.locator('.memory-community');await openChat(mediaChat);const mediaDraft=mediaChat.locator('textarea[name=message]');await mediaDraft.fill('打开素材前仍需保留的草稿。');assert.equal(await mediaDraft.inputValue(),'打开素材前仍需保留的草稿。','memoir media setup has a dirty composer');
  let parentArrivedResolve;const parentArrived=new Promise(resolve=>parentArrivedResolve=resolve);bookParentArrivedResolve=parentArrivedResolve;const childReadsBefore=count('GET',/^\/memory-stories\/[0-9a-f-]{36}(?:\?|$)/),parentReadsBefore=count('GET',/^\/memory-community\/v1\/books\/[0-9a-f-]{36}(?:\?|$)/),mutationsBefore=requests.filter(item=>['POST','PUT','DELETE'].includes(item.method)).length,dialogsBefore=dialogs.length;let promptResolve;const promptShown=new Promise(resolve=>promptResolve=resolve);onDialog=promptResolve;holdBookParent=true;setDialog('dismiss');await bookReader.getByRole('button',{name:'打开故事与家人回忆',exact:true}).click();await Promise.race([parentArrived,page.waitForTimeout(5000).then(()=>{throw new Error('memoir parent reauthorization did not reach hold');})]);await mediaDraft.fill('授权核对期间补写的回忆草稿。');bookParentReleaseResolve();await Promise.race([promptShown,page.waitForTimeout(5000).then(()=>{throw new Error('memoir leave confirmation did not follow parent reauthorization');})]);assert.equal(dialogs.length,dialogsBefore+1,'memoir child-story replacement asks only after parent authorization returns');assert.match(dialogs.at(-1),/未发送的消息和草稿/);assert(await bookReader.evaluate(el=>el.open),'cancel after reauthorization leaves the memoir open');assert.equal(await mediaDraft.inputValue(),'授权核对期间补写的回忆草稿。','words typed during read-only authorization survive Cancel');assert.equal(count('GET',/^\/memory-community\/v1\/books\/[0-9a-f-]{36}(?:\?|$)/),parentReadsBefore+1,'Cancel permits only the authorized read-only parent GET');assert.equal(count('GET',/^\/memory-stories\/[0-9a-f-]{36}(?:\?|$)/),childReadsBefore,'Cancel does not fetch or replace the child story');assert.equal(requests.filter(item=>['POST','PUT','DELETE'].includes(item.method)).length,mutationsBefore,'Cancel after authorization makes no mutation request');
  const mediaThreadBefore=await mediaChat.locator('select[name=conversation]').inputValue(),mediaMountBefore=await mediaChat.locator('.memory-community-content').getAttribute('id');const bookMedia=bookReader.locator('.memory-book-reading-frames button').first();setDialog('dismiss');await bookMedia.click();assert(await bookReader.isVisible(),'cancel preserves memoir while choosing chapter media');const mediaThreadAfter=await mediaChat.locator('select[name=conversation]').inputValue(),mediaMountAfter=await mediaChat.locator('.memory-community-content').getAttribute('id'),afterMedia=await bookReader.locator('.memory-community textarea[name=message]').evaluateAll(nodes=>nodes.map(node=>node.value));assert.equal(mediaThreadAfter,mediaThreadBefore,'same selected memoir thread remains mounted after media-exit cancel');assert.equal(mediaMountAfter,mediaMountBefore,'memoir target panel identity remains unchanged after media-exit cancel');assert.deepEqual(afterMedia,['授权核对期间补写的回忆草稿。'],`cancel preserves draft in current memoir thread; dialog=${dialogs.at(-1)} thread=${mediaThreadBefore}/${mediaThreadAfter} mount=${mediaMountBefore}/${mediaMountAfter}`);setDialog('accept');await bookMedia.click();await bookReader.waitFor({state:'hidden'});
  assert.deepEqual(errors,[],'reader exits do not produce browser errors');assert.equal(requests.some(item=>item.path.includes('/audio?')||item.path.includes('/contributions/audio')),false,'leave confirmation never fetches or uploads original audio');
  console.log('MEMORY_READER_LEAVE_GUARD_BROWSER_PASS');console.log('ARTIFACTS_DIR '+artifacts);
})().catch(error=>{console.error(error.stack||error);process.exitCode=1;}).finally(async()=>{try{await context?.close();}catch(_){}try{await browser?.close();}catch(_){}try{bridge.stdin.write(JSON.stringify({command:'quit'})+'\n');bridge.kill();}catch(_){}});
