'use strict';
/* Actual browser -> closed ASGI -> migrated synthetic SQLite; no HTTP listener. */
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {createInterface}=require('node:readline');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../..');
const artifacts=process.env.PH_BROWSER_ARTIFACTS||fs.mkdtempSync(path.join(os.tmpdir(),'photohouse-story-web-'));
fs.mkdirSync(artifacts,{recursive:true});
const bridge=spawn(process.env.PH_BROWSER_PYTHON||path.join(root,'.venv/bin/python'),[path.join(__dirname,'browser_bridge.py')],{cwd:root,stdio:['pipe','pipe','pipe']});
let serial=0,readyResolve,readyReject;const pending=new Map();
const ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
bridge.stderr.on('data',chunk=>process.stderr.write(chunk));
createInterface({input:bridge.stdout}).on('line',line=>{const result=JSON.parse(line);if(result.ready){readyResolve();return;}const request=pending.get(result.id);if(request){pending.delete(result.id);request.resolve(result);}});
bridge.on('exit',code=>{if(code){readyReject(new Error('Bridge failed'));for(const item of pending.values())item.reject(new Error('Bridge failed'));}});
const rpc=message=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});bridge.stdin.write(JSON.stringify({...message,id})+'\n');});
let browser,ctx,hold=null,releaseHold,arrivedHold,shelfHold=null,releaseShelfHold,arrivedShelfHold,corruptShelfTheme=false,constrainPreviewEvidence=true,previewEvidence=null;const errors=[],external=[],checks=[],requests=[];
const pass=name=>{checks.push(name);console.log('PASS '+name);};
(async()=>{
  await ready;
  browser=await chromium.launch({headless:true,...(process.env.PH_BROWSER_EXECUTABLE?{executablePath:process.env.PH_BROWSER_EXECUTABLE}:{}),args:['--disable-background-networking','--disable-component-update','--no-first-run','--host-resolver-rules=MAP * ~NOTFOUND']});
  ctx=await browser.newContext({viewport:{width:1280,height:960},serviceWorkers:'block',acceptDownloads:true});
  await ctx.addInitScript(()=>{const utterances=[];class MockUtterance{constructor(text){this.text=text;}}const voices=[{name:'Synthetic local Chinese',lang:'zh-CN',localService:true},{name:'Synthetic local English',lang:'en-US',localService:true},{name:'Synthetic remote Chinese',lang:'zh-CN',localService:false}];const synth={speaking:false,pending:false,paused:false,cancelCount:0,resumeCount:0,getVoices:()=>voices,speak(value){utterances.push(value);this.speaking=true;},pause(){this.paused=true;},resume(){this.resumeCount++;this.paused=false;},cancel(){this.cancelCount++;this.speaking=false;this.pending=false;}};Object.defineProperty(window,'speechSynthesis',{configurable:true,value:synth});window.SpeechSynthesisUtterance=MockUtterance;window.__mockSpeech={utterances,synth};let Constructor;Object.defineProperty(window,'PhotoHouseStoryWorkspace',{configurable:true,get:()=>Constructor,set:value=>{Constructor=config=>{let forcedLanguage=null;const originalScope=config.scope;const instance=value({...config,scope:()=>({...originalScope(),...(forcedLanguage?{language:forcedLanguage}:{})})});window.__setStoryWorkspaceTestLanguage=language=>{forcedLanguage=language;instance.translate();};window.__storyWorkspaceTest=instance;return instance;};}});});
  await ctx.route('**/*',async route=>{
    const req=route.request(),url=new URL(req.url());
    if(url.origin!=='https://photohouse.test'){external.push(url.origin);await route.abort();return;}
    requests.push({method:req.method(),path:url.pathname+url.search,...(url.pathname==='/story-workspace/preview'?{body:req.postData()}:{} )});
    if(req.method()==='GET'&&url.pathname==='/memory-stories'){
      const theme=url.searchParams.get('theme'),page=Number(url.searchParams.get('page')||1),all=Array.from({length:10},(_,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,title:`合成保存故事 ${i+1}`,theme:i===9?'birthday':'trip',cover_asset_id:i%2?'102':'101',item_count:2,chapter_count:1}));
      let rows=theme==='grandparents'?[]:theme?all.filter(item=>item.theme===theme):all;const selected=rows.slice((page-1)*8,page*8),payload={library_id:'family-a',page,page_size:8,has_more:page*8<rows.length,can_create:false,items:selected};
      if(shelfHold&&theme==='trip'&&page===1){const gate=shelfHold;shelfHold=null;arrivedShelfHold();await gate;}
      if(corruptShelfTheme&&theme){corruptShelfTheme=false;if(payload.items.length)payload.items[0].theme='birthday';}
      await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(payload)});return;
    }
    const headers=await req.allHeaders();delete headers['content-length'];
    if(!headers['sec-fetch-site'])headers['sec-fetch-site']=new URL(req.frame().url()).origin===url.origin?'same-origin':'none';
    const result=await rpc({method:req.method(),path:url.pathname+url.search,headers,body:(req.postDataBuffer()||Buffer.alloc(0)).toString('base64')});
    if(hold&&url.pathname==='/story-workspace/preview'){const gate=hold;hold=null;arrivedHold();await gate;}
    let body=Buffer.from(result.body,'base64');
    if(constrainPreviewEvidence&&req.method()==='POST'&&url.pathname==='/story-workspace/preview'){
      constrainPreviewEvidence=false;const payload=JSON.parse(body.toString()),section=payload.chapters[0];
      const [firstItem,secondItem]=payload.items;
      if(!section||payload.items.length!==2||!firstItem.evidence.length||!secondItem.evidence.length)throw new Error('Fixture needs two cited chapter assets with source text');
      const family={id:'family-reader-fixture',source:'family',title:'合成家人回忆',text:'<em>家人原话</em> & 仅作界面测试'};
      const sharedId='shared-reader-fixture',firstShared={id:sharedId,source:'ai',title:'',text:'第一张画面的合成参考'},secondShared={id:sharedId,source:'ai',title:'',text:'第二张画面的合成参考'};
      firstItem.evidence.push(family,firstShared);secondItem.evidence.push(secondShared);
      const firstAsset=firstItem.id,secondAsset=secondItem.id;
      payload.chapters=[
        {...section,id:'chapter-1',title:'第一章',asset_ids:[firstAsset],evidence_ids:[family.id,sharedId]},
        {...section,id:'chapter-2',title:'第二章',asset_ids:[secondAsset],evidence_ids:[sharedId]}
      ];
      previewEvidence={family,sharedId,firstText:firstShared.text,secondText:secondShared.text,uncited:firstItem.evidence.find(item=>item.id!==family.id&&item.id!==sharedId)};
      body=Buffer.from(JSON.stringify(payload));
    } else if(req.method()==='POST'&&url.pathname==='/story-workspace/preview'&&result.status===200){
      // Later browser checkpoints retain one ephemeral family-source marker so
      // the logout test can prove private reader DOM is cleared while mounted.
      const payload=JSON.parse(body.toString()),item=payload.items[0],id='family-clear-fixture';
      item.evidence.push({id,source:'family',title:'',text:'合成家庭来源清除检查'});
      const section=payload.chapters.find(value=>value.asset_ids.includes(item.id));if(section)section.evidence_ids.push(id);
      body=Buffer.from(JSON.stringify(payload));
    }
    if(shelfHold&&url.pathname==='/memory-stories'&&url.searchParams.get('theme')==='trip'){const gate=shelfHold;shelfHold=null;arrivedShelfHold();await gate;}
    if(corruptShelfTheme&&url.pathname==='/memory-stories'&&url.searchParams.has('theme')){corruptShelfTheme=false;const payload=JSON.parse(body.toString());if(payload.items?.length)payload.items[0].theme='birthday';body=Buffer.from(JSON.stringify(payload));}
    const output={...result.headers};delete output['content-length'];delete output['content-encoding'];
    try{await route.fulfill({status:result.status,headers:output,body});}catch(error){if(!/closed|handled|cancel|Invalid InterceptionId/.test(error.message))throw error;}
  });
  let dismissDialogs=false;
  const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>dismissDialogs?d.dismiss():d.accept());
  async function login(phone='+12025550102'){await page.goto('https://photohouse.test/ui');await page.locator('#auth').waitFor({state:'visible'});await page.locator('#phone').fill(phone);await page.locator('#password').fill('Synthetic family passphrase!');await page.locator('#auth-submit').click();await page.locator('#grid .asset').first().waitFor();}
  await login();
  assert.equal(await page.locator('.memory-theme').count(),6);
  assert.equal(await page.locator('#memory-home').isVisible(),true);
  assert.match(await page.locator('.memory-home-copy h2').textContent(),/值得慢慢看/);
  await page.screenshot({path:path.join(artifacts,'memory-home-desktop-zh.png'),fullPage:true});
  pass('Chinese memory home and six theme entries use authorized gallery media');
  await page.locator('.memory-theme[data-theme=trip]').click();
  assert.equal(await page.locator('#story-workspace').isVisible(),true);
  assert.equal(await page.locator('#story-workspace-theme').inputValue(),'trip');
  assert.equal(await page.locator('#story-selection input:checked').count(),2);
  await page.locator('.story-frame-order button[aria-label="向后移动 102"]').click();
  assert.deepEqual(await page.locator('#story-selection input').evaluateAll(nodes=>nodes.map(n=>n.value)),['101','102']);
  await page.locator('#story-workspace-title').fill('湖边的一天');
  await page.locator('#story-build').click();await page.locator('.story-chapter-card').first().waitFor();
  assert.equal(await page.locator('.story-chapter-card').count(),2);
  await page.locator('.story-chapter-card input').first().fill('从这段回忆开始');
  await page.locator('.story-chapter-card textarea').first().fill('那天下午，我们沿着湖边慢慢走。\n这段文字由家人补充。');
  dismissDialogs=true;
  await page.locator('#story-workspace-theme').selectOption('birthday');
  assert.equal(await page.locator('#story-workspace-theme').inputValue(),'trip');
  await page.locator('#story-selection input').first().click();
  assert.equal(await page.locator('#story-selection input:checked').count(),2);
  await page.locator('#story-build').click();
  assert.match(await page.locator('.story-chapter-card textarea').first().inputValue(),/家人补充/);
  dismissDialogs=false;
  pass('Cancelling replacement preserves edited narration, selected frames and theme');
  await page.locator('.story-reference-list summary').first().click();
  assert.match(await page.locator('.story-reference-list').first().textContent(),/AI 观察.*待核实/);
  await page.screenshot({path:path.join(artifacts,'story-editor-desktop-zh.png'),fullPage:true});
  pass('Authenticated multi-media outline, editable chapter and separate AI references');
  const downloadEvent=page.waitForEvent('download');await page.locator('#story-export').click();
  const download=await downloadEvent;await download.saveAs(path.join(artifacts,'synthetic-story-draft.json'));
  const exported=JSON.parse(fs.readFileSync(path.join(artifacts,'synthetic-story-draft.json'),'utf8'));
  assert.equal(exported.saved,false);assert.equal(exported.title,'湖边的一天');assert.match(exported.chapters[0].narration,/家人补充/);
  await page.locator('#story-preview').click();if(!(await page.locator('#story-reader').isVisible()))throw new Error('Reader failed to open: '+JSON.stringify(errors));await page.locator('#story-reader').waitFor({state:'visible'});
  assert.equal(await page.locator('#story-workspace').isVisible(),true,'draft preview retains its existing editor underneath');
  assert.equal(await page.locator('#story-reader-title').textContent(),'从这段回忆开始');
  await page.waitForFunction(()=>Boolean(document.querySelector('#story-reader-stage img')?.naturalWidth));
  await page.screenshot({path:path.join(artifacts,'story-reader-desktop-zh.png'),fullPage:true});
  pass('Edited narrative is read literally in cinematic preview and explicit draft download');
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert(await page.locator('#story-reader').evaluate(el=>el.scrollWidth<=el.clientWidth));
  await page.screenshot({path:path.join(artifacts,'story-reader-mobile-zh.png'),fullPage:true});
  const chapterSources=page.locator('#story-reader .story-reader-sources');assert.equal(await chapterSources.count(),1,'reader offers references for the active chapter');
  assert.equal(await chapterSources.evaluate(node=>node.open),false,'source disclosure starts collapsed');
  assert.equal(await chapterSources.locator('summary').evaluate(node=>getComputedStyle(node).display),'list-item','native details marker remains visible');
  assert.deepEqual(await chapterSources.locator('[data-evidence-id]').evaluateAll(nodes=>nodes.map(node=>node.dataset.evidenceId)),[previewEvidence.family.id,previewEvidence.sharedId],'reader includes only the cited evidence attached to this chapter');
  assert.equal(await chapterSources.locator(`[data-evidence-id="${previewEvidence.uncited.id}"]`).count(),0,'reader excludes evidence attached to this image when the chapter did not cite it');
  assert.match(await chapterSources.textContent(),/参考资料，不代表已核实事实/);
  assert.match(await chapterSources.textContent(),/家人提供的文字/);assert.match(await chapterSources.textContent(),/AI 观察 · 需核对/);
  assert.equal(await chapterSources.locator('em').count(),0,'family wording is rendered as literal text, never interpreted as markup');
  assert.match(await chapterSources.textContent(),/<em>家人原话<\/em> & 仅作界面测试/);
  await chapterSources.locator('summary').press('Enter');assert.equal(await chapterSources.evaluate(node=>node.open),true,'native disclosure opens from the keyboard');
  await chapterSources.screenshot({path:path.join(artifacts,'story-reader-sources-mobile-zh.png')});
  const postsBeforeTranslation=requests.filter(item=>item.method==='POST').length;
  await page.evaluate(()=>window.__setStoryWorkspaceTestLanguage('en'));
  assert.equal(await chapterSources.evaluate(node=>node.open),true,'translation preserves disclosure state');
  assert.equal(await chapterSources.locator('summary').textContent(),'View sources for this chapter');
  assert.equal(await chapterSources.locator('.story-reader-sources-note').textContent(),'These are references cited for this chapter; they are not verified facts.');
  assert.equal(await chapterSources.locator('[data-evidence-id] strong').first().textContent(),'Family-provided wording');
  assert.equal(requests.filter(item=>item.method==='POST').length,postsBeforeTranslation,'source translation sends no request');
  await page.evaluate(()=>{window.__setStoryWorkspaceTestLanguage('zh');window.__setStoryWorkspaceTestLanguage(null);});
  const narration=page.locator('.story-narration-controls');
  assert.equal(await narration.count(),1);assert.equal(await page.evaluate(()=>window.__mockSpeech.utterances.length),0,'loading a reader must not autoplay narration');
  await narration.getByRole('button',{name:'朗读本章'}).click();
  assert.equal(await page.evaluate(()=>window.__mockSpeech.utterances.length),1);assert.match(await narration.textContent(),/正在朗读本章/);
  await narration.getByRole('button',{name:'暂停朗读'}).click();assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.paused),true);
  await narration.getByRole('button',{name:'继续朗读'}).click();assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.paused),false);
  await narration.getByRole('button',{name:'暂停朗读'}).click();await narration.getByRole('button',{name:'停止朗读'}).click();assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.paused),true,'mock cancel preserves paused state');
  const resumeCount=await page.evaluate(()=>window.__mockSpeech.synth.resumeCount);await narration.getByRole('button',{name:'朗读本章'}).click();assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.paused),false,'new explicit start resumes after paused cancel');assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.resumeCount),resumeCount+1);
  const callsBeforeStop=await page.evaluate(()=>window.__mockSpeech.utterances.length);await narration.getByRole('button',{name:'停止朗读'}).click();
  await page.evaluate(()=>window.__mockSpeech.utterances[0].onend?.());assert.equal(await page.evaluate(()=>window.__mockSpeech.utterances.length),callsBeforeStop,'late end callback cannot restart a cancelled utterance');
  await narration.getByRole('button',{name:'朗读本章'}).click();assert.equal(await page.evaluate(()=>window.__mockSpeech.utterances.length),callsBeforeStop+1);
  await page.locator('#story-reader-play').click();assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.speaking),false,'story slideshow activation stops narration');await page.locator('#story-reader-play').click();
  await page.locator('#story-reader-next').click();assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.speaking),false,'chapter change cancels narration');
  assert.equal(await page.locator('#story-reader .story-reader-sources').evaluate(node=>node.open),false,'chapter change closes the source disclosure');
  assert.deepEqual(await page.locator('#story-reader .story-reader-sources [data-evidence-id]').evaluateAll(nodes=>nodes.map(node=>node.dataset.evidenceId)),[previewEvidence.sharedId]);
  assert.equal(await page.locator('#story-reader .story-reader-sources').locator(`[data-evidence-id="${previewEvidence.sharedId}"]`).count(),1,'shared citation ID does not expose a sibling asset’s second record');
  assert.match(await page.locator('#story-reader .story-reader-sources').textContent(),new RegExp(previewEvidence.secondText));
  assert.doesNotMatch(await page.locator('#story-reader .story-reader-sources').textContent(),new RegExp(previewEvidence.firstText));
  await page.locator('#story-reader-previous').click();
  assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.speaking),false,'navigation cancels narration');
  await page.evaluate(()=>{document.documentElement.style.zoom='150%';});
  assert(await narration.evaluate(el=>el.scrollWidth<=el.clientWidth),'150% narration controls remain within their reader column');await narration.scrollIntoViewIfNeeded();
  await narration.screenshot({path:path.join(artifacts,'story-narration-mobile-150-zh.png')});
  assert.equal(await chapterSources.evaluate(node=>node.open),false);await chapterSources.screenshot({path:path.join(artifacts,'story-reader-sources-mobile-150-closed-zh.png')});
  await chapterSources.locator('summary').press('Enter');assert(await chapterSources.evaluate(node=>node.scrollWidth<=node.clientWidth),'expanded chapter sources fit at 150% zoom');await chapterSources.screenshot({path:path.join(artifacts,'story-reader-sources-mobile-150-zh.png')});
  assert.equal(await page.locator('#story-reader').evaluate(el=>el.open),true,'reader remains open during chapter narration checks');
  await page.screenshot({path:path.join(artifacts,'story-reader-mobile-150-zh.png')});
  await page.evaluate(()=>{document.documentElement.style.zoom='';});
  const beforeClosePlay=await page.evaluate(()=>window.__mockSpeech.utterances.length);await narration.getByRole('button',{name:'朗读本章'}).click();assert.equal(await page.evaluate(()=>window.__mockSpeech.utterances.length),beforeClosePlay+1,'explicit play starts before close test');const cancelCount=await page.evaluate(()=>window.__mockSpeech.synth.cancelCount);await page.locator('#story-reader-close').click();await page.locator('#story-reader').waitFor({state:'hidden'});
  assert(await page.evaluate(count=>window.__mockSpeech.synth.cancelCount>count,cancelCount),'closing the reader cancels active narration');
  pass('Mock local voice is explicit, pausable, cancellable and never resumes after chapter or frame navigation');
  assert(await page.locator('#story-workspace').evaluate(el=>el.scrollWidth<=el.clientWidth));
  await page.screenshot({path:path.join(artifacts,'story-editor-mobile-zh.png'),fullPage:true});
  await page.locator('#story-workspace-close').click();
  await page.screenshot({path:path.join(artifacts,'memory-home-mobile-zh.png'),fullPage:true});
  pass('390px home, editor and story preview have no horizontal overflow');
  await page.locator('#language').click();
  await page.locator('#memory-create').click();
  assert.match(await page.locator('#story-workspace-heading').textContent(),/Story draft/);
  await page.locator('#story-workspace-title').fill('<img src=x onerror=alert(1)>');await page.locator('#story-build').click();await page.locator('.story-chapter-card').first().waitFor();
  assert.equal(await page.locator('#story-workspace-title').inputValue(),'<img src=x onerror=alert(1)>');
  assert.equal(await page.locator('#story-chapter-editor img[src="x"]').count(),0);
  await page.locator('#story-preview').click();await page.locator('#story-reader').waitFor({state:'visible'});
  await page.locator('.story-narration-controls').getByRole('button',{name:'Read this chapter aloud'}).click();
  assert.equal(await page.evaluate(()=>window.__mockSpeech.utterances.at(-1).voice.lang),'en-US','English text uses a local English voice');
  await page.locator('#story-reader').press('Escape');assert.equal(await page.evaluate(()=>window.__mockSpeech.synth.speaking),false,'Escape closes the reader and cancels speech');
  await page.locator('#story-workspace-close').click();
  pass('English workspace and user-provided markup remain literal text');
  await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===8);
  const hasListCall=(pageNumber,theme)=>requests.some(item=>{const parsed=new URL(item.path,'https://photohouse.test');if(!parsed.pathname.endsWith('/memory-stories'))return false;const query=parsed.searchParams;return query.get('page')===String(pageNumber)&&(theme===null?!query.has('theme'):query.get('theme')===theme);});
  assert(hasListCall(1,null),'All keeps the existing all-stories request path without a theme parameter');
  assert.equal(await page.locator('#saved-memory-filters button').count(),7);assert.equal(await page.locator('#saved-memory-filters [aria-pressed=true]').getAttribute('data-theme'),'all');
  assert.equal(await page.locator('#saved-memory-list .saved-memory-card').count(),8);assert(await page.locator('#saved-memory-more').isVisible(),'all stories paginate globally');await page.locator('#saved-memory-more').click();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===10);
  await page.locator('#saved-memory-filters [data-theme=trip]').click();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===8);assert(hasListCall(1,'trip'));assert(await page.locator('#saved-memory-more').isVisible());await page.locator('#saved-memory-more').click();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===9);assert(hasListCall(2,'trip'));
  await page.locator('#saved-memory-filters [data-theme=birthday]').click();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===1);const birthdayRefresh=page.waitForRequest(req=>new URL(req.url()).searchParams.get('theme')==='birthday'&&new URL(req.url()).searchParams.get('page')==='1');await page.locator('#saved-memory-refresh').click();await birthdayRefresh;await page.waitForFunction(()=>!document.querySelector('#saved-memory-refresh').disabled);assert(hasListCall(1,'birthday'));
  await page.locator('#saved-memory-filters [data-theme=grandparents]').click();await page.waitForFunction(()=>document.querySelector('.saved-memory-empty'));assert.match(await page.locator('.saved-memory-empty').textContent(),/No saved stories under this theme yet/);assert.equal(await page.locator('#saved-memory-more').isHidden(),true);await page.locator('.saved-memory-empty-actions button').first().click();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===8);assert.equal(await page.locator('#saved-memory-filters [data-theme=all]').getAttribute('aria-pressed'),'true');
  let shelfArrival;const shelfArrived=new Promise(resolve=>shelfArrival=resolve);shelfHold=new Promise(resolve=>releaseShelfHold=resolve);arrivedShelfHold=shelfArrival;await page.locator('#saved-memory-filters [data-theme=trip]').click();await shelfArrived;await page.locator('#saved-memory-filters [data-theme=birthday]').click();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===1);releaseShelfHold();await page.waitForTimeout(80);assert.equal(await page.locator('#saved-memory-filters [data-theme=birthday]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#saved-memory-list .saved-memory-card').count(),1,'late trip response cannot replace current birthday filter');
  let logoutArrival;const logoutArrived=new Promise(resolve=>logoutArrival=resolve);shelfHold=new Promise(resolve=>releaseShelfHold=resolve);arrivedShelfHold=logoutArrival;await page.locator('#saved-memory-filters [data-theme=trip]').click();await logoutArrived;await page.locator('#logout').click();await page.locator('#auth').waitFor({state:'visible'});releaseShelfHold();await page.waitForTimeout(80);assert.equal(await page.locator('#saved-memory-list .saved-memory-card').count(),0,'late filtered reply after account clear cannot restore prior cards');assert.equal(await page.locator('#saved-memory-filters [data-theme=all][aria-pressed=true]').count(),1);await login();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===8);
  corruptShelfTheme=true;await page.locator('#saved-memory-filters [data-theme=trip]').click();await page.waitForFunction(()=>document.querySelector('#saved-memory-status')?.textContent.includes('暂不可用'));assert.equal(await page.locator('#saved-memory-list .saved-memory-card').count(),0,'mismatched server theme is rejected before render');
  await page.locator('#saved-memory-refresh').click();await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===8);await page.setViewportSize({width:1280,height:960});await page.locator('#saved-memory-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifacts,'saved-story-theme-shelf-desktop-top.png')});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>{document.documentElement.style.zoom='150%';});assert(await page.locator('#saved-memory-filters').evaluate(el=>el.scrollWidth<=el.clientWidth));await page.locator('#saved-memory-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifacts,'saved-story-theme-shelf-mobile-150-zh-top.png')});await page.locator('#saved-memory-panel').screenshot({path:path.join(artifacts,'saved-story-theme-shelf-mobile-150-zh.png')});await page.evaluate(()=>{document.documentElement.style.zoom='';});
  await page.locator('#logout').click();await page.locator('#auth').waitFor({state:'visible'});assert.equal(await page.locator('#saved-memory-filters [data-theme=all][aria-pressed=true]').count(),1,'account clear resets selection to All');await login();await page.waitForFunction(()=>document.querySelector('#saved-memory-filters [data-theme=all][aria-pressed=true]'));await page.waitForFunction(()=>document.querySelectorAll('#saved-memory-list .saved-memory-card').length===8);assert(hasListCall(1,null),'relogin starts in All with a fresh first-page request');
  pass('Saved story theme filters use server pagination, preserve selection on refresh, reject stale/mismatched replies and wrap at mobile zoom');
  await page.locator('#memory-create').click();
  await page.locator('#story-build').click();await page.locator('.story-chapter-card').first().waitFor();
  await page.locator('#story-preview').click();await page.locator('#story-reader').waitFor({state:'visible'});
  assert.match(await page.locator('#story-reader').textContent(),/合成家庭来源清除检查/,'synthetic family wording is present before account clear');
  await page.locator('#story-reader-close').click();await page.locator('#story-workspace-close').click();
  await page.locator('#logout').click();await page.locator('#auth').waitFor({state:'visible'});
  assert.equal(await page.locator('#story-reader .story-reader-sources').count(),0,'account clear removes private source disclosures from closed reader DOM');
  assert.doesNotMatch(await page.locator('#story-reader').textContent(),/合成家庭来源清除检查|家人原话/,'account clear removes synthetic private source wording from reader DOM');
  await login();
  await page.locator('#memory-create').click();
  hold=new Promise(resolve=>releaseHold=resolve);const arrived=new Promise(resolve=>arrivedHold=resolve);
  await page.locator('#story-build').click();await arrived;await page.locator('#story-workspace-close').click();
  await page.locator('#logout').click();await page.locator('#auth').waitFor({state:'visible'});releaseHold();
  await page.waitForTimeout(100);
  assert.equal(await page.locator('#story-reader .story-reader-sources').count(),0,'logout removes private source disclosures from closed reader DOM');
  assert.doesNotMatch(await page.locator('#story-reader').textContent(),/合成家庭来源清除检查|家人原话/,'logout removes synthetic private source wording from reader DOM');
  assert.equal(await page.locator('#story-reader').isVisible(),false);
  assert.equal(await page.locator('#story-selection img').count(),0);
  assert.equal(await page.locator('#story-chapter-editor').textContent(),'');
  assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
  pass('Logout clears drafts/media; late preview cannot repopulate private UI; no browser storage');
  await login();await rpc({command:'mutate',scenario:'many-assets'});
  const albumIds=Array.from({length:29},(_,i)=>String(1101+i));
  await page.evaluate(ids=>window.__storyWorkspaceTest.open(ids,'trip'),albumIds);
  assert.equal(await page.locator('#story-selection input').count(),8,'album choices are paged in bounded groups');
  assert.equal(await page.locator('#story-selection input[value="1101"]').getAttribute('aria-label'),'画面 1101','ID-only album choices do not claim a media kind before metadata is loaded');
  assert.match(await page.locator('#story-selection-count').textContent(),/24 \/ 24.*共 29/);
  assert.match(await page.locator('#story-workspace-status').textContent(),/默认选中前 24/);
  const seen=await page.locator('#story-selection input').evaluateAll(nodes=>nodes.map(node=>node.value));
  for(let i=0;i<3;i++){await page.locator('#story-selection-next').click();seen.push(...await page.locator('#story-selection input').evaluateAll(nodes=>nodes.map(node=>node.value)));}
  assert.deepEqual(seen,albumIds,'every album choice remains reachable across pages');
  assert.equal(await page.locator('#story-selection input[value="1129"]').isDisabled(),true,'limit requires unchecking a choice first');
  await page.locator('#story-selection input[value="1129"]').evaluate(input=>{input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));});
  assert.equal(await page.locator('#story-selection input[value="1129"]').isChecked(),false,'handler also enforces the cap');
  const detached=await page.locator('#story-selection input[value="1129"]').elementHandle();
  await page.locator('#story-selection-clear').click();assert.match(await page.locator('#story-selection-count').textContent(),/^0 \/ 24/);assert.equal(await page.locator('#story-build').isDisabled(),true);
  await detached.evaluate(input=>{input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));});
  assert.match(await page.locator('#story-selection-count').textContent(),/^0 \/ 24/,'detached page choices cannot change a later selection');await detached.dispose();
  await page.locator('#story-selection-first').click();assert.match(await page.locator('#story-selection-count').textContent(),/^24 \/ 24/);
  await page.locator('#story-selection input[value="1101"]').uncheck();
  for(let i=0;i<3;i++)await page.locator('#story-selection-next').click();
  await page.locator('#story-selection input[value="1129"]').check();
  await page.evaluate(()=>window.__storyWorkspaceTest.open(['1101','1101'],'trip'));
  assert.equal(await page.locator('#story-selection input').count(),5,'malformed replacement preserves existing page and choices');
  assert.equal(await page.locator('#story-selection input[value="1129"]').isChecked(),true);
  await page.locator('#story-workspace').evaluate(el=>{el.style.fontSize='150%';el.scrollTop=0;});
  for(const selector of ['.story-selection-panel','.story-selection-actions','.story-selection-pages','.story-writing-panel'])assert(await page.locator(selector).evaluate(el=>el.scrollWidth<=el.clientWidth),`${selector} fits the 390px viewport at 150% text`);
  await page.locator('#story-workspace').screenshot({path:path.join(artifacts,'story-album-choices-mobile-150-zh.png')});
  await page.evaluate(()=>window.__storyWorkspaceTest.setItems([{id:'101',kind:'image'},{id:'102',kind:'video'}]));
  assert.match(await page.locator('#story-selection-count').textContent(),/^24 \/ 24.*共 29/,'a late gallery refresh does not replace the active album snapshot');
  await page.locator('.story-frame-start[aria-label="设为开头 1129"]').click();
  assert.equal(await page.locator('#story-selection input').first().inputValue(),'1129','a later selected frame can become the story cover/opening');
  await page.locator('#story-build').click();await page.waitForFunction(()=>document.querySelectorAll('.story-chapter-card').length===6);
  const outgoing=JSON.parse(requests.filter(r=>r.method==='POST'&&r.path.startsWith('/story-workspace/preview')).at(-1).body);
  assert.deepEqual(outgoing.asset_ids.split(','),['1129',...albumIds.slice(1,24)],'only selected IDs, in the displayed order, go to the real protected API');
  assert.match(await page.locator('#story-selection-count').textContent(),/^24 \/ 24.*共 29/,'building preserves the full album choice pool');
  await page.locator('#story-selection-next').click();assert.equal(await page.locator('#story-selection input').count(),8);
  await page.locator('#story-workspace-close').click();
  await page.evaluate(()=>window.__storyWorkspaceTest.open(['101','102'],'trip'));
  assert.equal(await page.locator('#story-selection input[value="102"]').getAttribute('aria-label'),'视频 102','ID-only choices reuse known gallery metadata without claiming an immediate playback action');
  await page.locator('#story-workspace-close').click();await page.locator('#logout').click();await page.locator('#auth').waitFor({state:'visible'});
  assert.equal(await page.locator('#story-selection img').count(),0,'large album choice pool clears at logout');
  assert.deepEqual(external,[]);assert.deepEqual(errors,[]);
  pass('Large album choices remain available, cap is enforced, a later frame reaches the protected API, and choices clear at logout');
  fs.writeFileSync(path.join(artifacts,'checks.json'),JSON.stringify({checks,errors,external,fixture:'synthetic ASGI; Fetch Metadata explicitly modeled',saved_story_shelf_fixture:'synthetic response adapter; backend filtering separately covered by API tests'},null,2));
  console.log('ARTIFACTS '+artifacts);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(ctx)await ctx.close();if(browser)await browser.close();bridge.stdin.end();});
