'use strict';
/* Real browser -> closed ASGI -> SQLite memoir source-reference journey. */
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {createInterface}=require('node:readline');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../..'),artifacts=process.env.PH_BROWSER_ARTIFACTS||fs.mkdtempSync(path.join(os.tmpdir(),'photohouse-memoir-refs-'));
fs.mkdirSync(artifacts,{recursive:true});
const bridge=spawn(process.env.PH_BROWSER_PYTHON||path.join(root,'.venv/bin/python'),[path.join(__dirname,'browser_bridge.py')],{cwd:root,stdio:['pipe','pipe','pipe']});
let serial=0,readyResolve,readyReject;const pending=new Map(),ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
bridge.stderr.on('data',chunk=>process.stderr.write(chunk));createInterface({input:bridge.stdout}).on('line',line=>{const value=JSON.parse(line);if(value.ready){readyResolve();return;}const request=pending.get(value.id);if(request){pending.delete(value.id);request.resolve(value);}});
bridge.on('exit',code=>{if(code){readyReject(new Error('Browser bridge failed'));for(const item of pending.values())item.reject(new Error('Browser bridge failed'));}});
const rpc=message=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});bridge.stdin.write(JSON.stringify({...message,id})+'\n');return undefined;});
const requests=[],pageErrors=[],external=[];let browser,ctx,storyId=null,storyPayload=null,failNextRefs=false,holdRefs=false,resolveRefs,arriveRefs,holdDetail=false,resolveDetail,arriveDetail;const writes=[];
(async()=>{
  await ready;browser=await chromium.launch({headless:true,...(process.env.PH_BROWSER_EXECUTABLE?{executablePath:process.env.PH_BROWSER_EXECUTABLE}:{}),args:['--disable-background-networking','--disable-component-update','--no-first-run','--host-resolver-rules=MAP * ~NOTFOUND']});
  ctx=await browser.newContext({viewport:{width:1280,height:960},serviceWorkers:'block'});
  await ctx.addInitScript(()=>{let Constructor;Object.defineProperty(window,'PhotoHouseStoryWorkspace',{configurable:true,get:()=>Constructor,set:value=>{Constructor=config=>{const instance=value(config);window.__storyWorkspaceTest=instance;return instance;};}});});
  await ctx.route('**/*',async route=>{
    const req=route.request(),url=new URL(req.url());if(url.origin!=='https://photohouse.test'){external.push(url.origin);await route.abort();return;}
    const record={method:req.method(),path:url.pathname+url.search,body:req.postData()};requests.push(record);
    if(failNextRefs&&req.method()==='GET'&&url.pathname.endsWith('/contribution-refs')){failNextRefs=false;record.status=503;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'synthetic optional refs unavailable'})});return;}
    const headers=await req.allHeaders();delete headers['content-length'];if(!headers['sec-fetch-site'])headers['sec-fetch-site']=new URL(req.frame().url()).origin===url.origin?'same-origin':'none';record.headers=headers;
    if(['POST','PUT'].includes(req.method())&&url.pathname.startsWith('/memory-stories'))writes.push(record);
    const result=await rpc({method:req.method(),path:url.pathname+url.search,headers,body:(req.postDataBuffer()||Buffer.alloc(0)).toString('base64')});record.status=result.status;record.response=Buffer.from(result.body,'base64').toString();
    if(req.method()==='GET'&&/^\/memory-stories\/[0-9a-f-]{36}$/.test(url.pathname)&&result.status===200){storyPayload=JSON.parse(Buffer.from(result.body,'base64').toString());storyId=storyPayload.id;}
    if(holdRefs&&req.method()==='GET'&&url.pathname.endsWith('/contribution-refs')){holdRefs=false;arriveRefs();await new Promise(resolve=>resolveRefs=resolve);}
    if(holdDetail&&req.method()==='GET'&&/^\/memory-community\/v1\/stories\/[0-9a-f-]+\/contributions\/[0-9a-f-]+$/.test(url.pathname)){holdDetail=false;arriveDetail();await new Promise(resolve=>resolveDetail=resolve);}
    const output={...result.headers};delete output['content-length'];delete output['content-encoding'];
    try{await route.fulfill({status:result.status,headers:output,body:Buffer.from(result.body,'base64')});}catch(error){if(!/closed|handled|cancel|Invalid InterceptionId/.test(error.message))throw error;}
  });
  const page=await ctx.newPage();page.on('pageerror',error=>pageErrors.push(error.message));page.on('dialog',dialog=>dialog.accept());await page.goto('https://photohouse.test/ui');await page.locator('#auth').waitFor();await page.locator('#phone').fill('+12025550100');await page.locator('#password').fill('Synthetic family passphrase!');await page.locator('#auth-submit').click();await page.locator('#grid .asset').first().waitFor();
  await rpc({command:'mutate',scenario:'many-assets'});await rpc({command:'mutate',scenario:'enable-story-source-detail-fixture'});
  await page.locator('#memory-create').click();await page.locator('#story-workspace-title').fill('合成湖边回忆');await page.locator('#story-build').click();await page.locator('.story-chapter-card').first().waitFor();await page.locator('.story-chapter-card textarea').first().fill('家人沿湖边慢慢散步。');await page.locator('#story-save-memory').click();await page.waitForFunction(()=>document.querySelector('#story-workspace-status').textContent.includes('已保存到'));assert(writes.some(item=>item.method==='POST'&&item.path.startsWith('/memory-stories?')),'first story was saved through the browser UI');
  await page.locator('#story-workspace-close').click();await page.locator('.saved-memory-card').first().locator('.saved-memory-cover').click();await page.locator('#story-reader').waitFor({state:'visible'});await page.waitForFunction(()=>window.__storyWorkspaceTest&&document.querySelector('#story-reader .story-reader-sources'));
  assert(storyPayload&&storyId,'the saved child was re-read through the real protected story endpoint');
  const seeded=await rpc({command:'mutate',scenario:'story-ref-contributions',story_id:storyId,chapter_id:'chapter-1'});assert.equal(seeded.ok,true);const textId=seeded.contribution_id,audioId=seeded.audio_contribution_id;
  const storyHeaders=writes.findLast(item=>item.method==='POST'&&item.path.startsWith('/memory-stories?')).headers;
  const authRead=requests.findLast(item=>item.method==='GET'&&item.path===`/memory-stories/${storyId}?library=family-a`);assert(authRead?.headers,'an authorized story GET is available for the current revision');
  const currentRead=await rpc({method:'GET',path:`/memory-stories/${storyId}?library=family-a`,headers:authRead.headers});assert.equal(currentRead.status,200);let current=JSON.parse(Buffer.from(currentRead.body,'base64').toString());
  const assets=current.items.map(item=>item.id);assert(assets.length>=2,'fixture story has two or more assets for chapter navigation');const groups=[assets.slice(0,1)];for(let i=1;i<assets.length;i+=4)groups.push(assets.slice(i,i+4));assert(groups.length<=6);
  const chapters=groups.map((asset_ids,index)=>({id:`chapter-${index+1}`,title:index?`合成章节 ${index+1}`:current.chapters[0].title,narration:index?`这是第 ${index+1} 章的合成文字。`:current.chapters[0].narration,asset_ids,evidence_ids:[]}));
  const refs=chapters.map((chapter,index)=>({chapter_id:chapter.id,contribution_ids:index===0?[textId,audioId]:[]}));
  const update={title:current.title,theme:current.theme,language:current.language,asset_ids:assets.join(','),chapters:JSON.stringify(chapters),selection_revision:current.selection_revision,revision:current.revision,mutation_id:'f0000000-0000-4000-8000-000000000081',contribution_refs:JSON.stringify(refs)};
  const updated=await rpc({method:'PUT',path:`/memory-stories/${storyId}?library=family-a&contribution_refs=1`,headers:storyHeaders,body:Buffer.from(JSON.stringify(update)).toString('base64')});assert.equal(updated.status,200,`refs fixture save failed: ${Buffer.from(updated.body,'base64')}`);current=JSON.parse(Buffer.from(updated.body,'base64').toString());
  const secondBody={title:'第二篇合成湖边回忆',theme:current.theme,language:current.language,asset_ids:assets.join(','),chapters:JSON.stringify(chapters),selection_revision:current.selection_revision,revision:'0',mutation_id:'f0000000-0000-4000-8000-000000000082'};
  const secondResult=await rpc({method:'POST',path:'/memory-stories?library=family-a',headers:storyHeaders,body:Buffer.from(JSON.stringify(secondBody)).toString('base64')});assert.equal(secondResult.status,200,`second story creation failed: ${Buffer.from(secondResult.body,'base64')}`);const second=JSON.parse(Buffer.from(secondResult.body,'base64').toString());
  const bookBody={title:'合成家庭回忆集',language:'zh',introduction:'只供本地浏览器测试。',story_ids:`${storyId},${second.id}`,revision:'0',mutation_id:'f0000000-0000-4000-8000-000000000083'};
  const created=await rpc({method:'POST',path:'/memory-community/v1/books?library=family-a',headers:storyHeaders,body:Buffer.from(JSON.stringify(bookBody)).toString('base64')});assert.equal(created.status,200,`memoir creation failed: ${Buffer.from(created.body,'base64')}`);const book=JSON.parse(Buffer.from(created.body,'base64').toString());
  const detailCount=()=>requests.filter(item=>item.method==='GET'&&item.path.includes('/contributions/')).length,detailBefore=detailCount();failNextRefs=true;await page.evaluate(value=>window.__storyWorkspaceTest.openBook(value),book);await page.locator('#memory-book-reader').waitFor({state:'visible'});await page.locator('#memory-book-reader .memory-book-toc button').first().click();await page.locator('#memory-book-reader .memory-book-reading-prose').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('#memory-book-reader .story-reader-sources-note')].some(node=>node.textContent.includes('来源链接暂不可用')));assert(await page.locator('#memory-book-reader .memory-book-reading-prose').isVisible(),'optional refs 503 leaves memoir prose readable');assert.equal(detailCount(),detailBefore,'opening the memoir does not fetch contribution detail');assert(requests.some(item=>item.method==='GET'&&item.path===`/memory-community/v1/books/${book.id}?library=family-a`),'parent book is reauthorized');assert(requests.some(item=>item.method==='GET'&&item.path===`/memory-stories/${storyId}?library=family-a`),'child story is reauthorized before refs');
  await page.locator('#memory-book-reader>header button').click();await page.locator('#memory-book-reader').waitFor({state:'hidden'});let refsArrivedResolve;const refsArrived=new Promise(resolve=>refsArrivedResolve=resolve);holdRefs=true;arriveRefs=refsArrivedResolve;await page.evaluate(value=>window.__storyWorkspaceTest.openBook(value),book);await page.locator('#memory-book-reader').waitFor({state:'visible'});await page.locator('#memory-book-reader .memory-book-toc button').first().click();const reader=page.locator('#memory-book-reader'),sources=reader.locator('.memory-book-reading .story-reader-sources');await sources.locator('summary').waitFor();await Promise.race([refsArrived,page.waitForTimeout(5000).then(()=>{throw new Error('memoir refs did not reach background-response hold');})]);
  await page.evaluate(()=>{const synth=speechSynthesis;synth.cancelCalls=0;synth.getVoices=()=>[{lang:'zh-CN',localService:true}];synth.speak=utterance=>{window.__syntheticUtterance=utterance;};synth.cancel=()=>{synth.cancelCalls++;};window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};});const narration=reader.locator('.story-narration-controls');await sources.locator('summary').click();await narration.getByRole('button',{name:'朗读本章'}).click();await narration.getByRole('button',{name:'停止朗读'}).waitFor({state:'visible'});await sources.locator('summary').focus();const scrollBefore=await reader.evaluate(el=>el.scrollTop);resolveRefs();await page.waitForFunction(()=>document.querySelectorAll('#memory-book-reader .story-reader-sources [data-contribution-id]').length===2);assert.equal(detailCount(),detailBefore,'retry hydrates refs only; no detail fetch occurs');assert.deepEqual(await sources.locator('[data-contribution-id]').evaluateAll(nodes=>nodes.map(node=>node.dataset.contributionId)),[textId,audioId]);assert.doesNotMatch(await sources.textContent(),/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,'source UUIDs stay out of memoir reader text');assert.equal(await narration.getByRole('button',{name:'停止朗读'}).isVisible(),true,'background reference completion does not stop active narration');assert.equal(await page.evaluate(()=>speechSynthesis.cancelCalls),0,'background reference completion does not cancel local speech');assert.equal(await sources.locator('summary').evaluate(el=>el===document.activeElement),true,'background refs rendering preserves focus on the source summary');assert.equal(await reader.evaluate(el=>el.scrollTop),scrollBefore,'background refs rendering preserves memoir reading position');
  await sources.locator('summary').click();await sources.locator('summary').click();assert.equal(await narration.getByRole('button',{name:'停止朗读'}).isVisible(),false,'explicit source disclosure stops local memoir narration');assert(await page.evaluate(()=>speechSynthesis.cancelCalls>0));
  const textRow=sources.locator(`[data-contribution-id="${textId}"]`);await textRow.locator('button').click();await textRow.locator('.story-contribution-source-detail').waitFor({state:'visible'});assert.match(await textRow.textContent(),/合成家人原话/);assert.equal(detailCount(),detailBefore+1,'text source detail loads only after explicit review');assert.equal(requests.some(item=>item.path.includes('/audio')),false,'no original audio endpoint is fetched');
  const audioRow=sources.locator(`[data-contribution-id="${audioId}"]`);await audioRow.locator('button').click();await audioRow.locator('.story-contribution-source-detail').waitFor({state:'visible'});assert.match(await audioRow.textContent(),/AI 转写/);assert.match(await audioRow.textContent(),/合成录音里的家人原话/);assert.equal(detailCount(),detailBefore+2,'ready transcript comes from the explicit authorized contribution detail GET');assert.equal(requests.some(item=>item.path.includes('/audio')),false,'audio source review never fetches original audio');
  const sourceAction=textRow.locator('button');await sourceAction.click();holdDetail=true;let arrivedResolve;const arrived=new Promise(resolve=>arrivedResolve=resolve);arriveDetail=arrivedResolve;await sourceAction.click();await Promise.race([arrived,page.waitForTimeout(5000).then(()=>{throw new Error('memoir detail did not reach late-response fence');})]);await reader.locator('.memory-book-reading-controls button').nth(1).click();await page.waitForFunction(title=>document.querySelector('#memory-book-reader .memory-book-reading h4')?.textContent!==title,chapters[0].title);resolveDetail();await page.waitForTimeout(100);assert.doesNotMatch(await reader.locator('.memory-book-reading').textContent(),/合成家人原话/,'late detail cannot appear after section switch');
  await reader.locator('.memory-book-reading-controls button').nth(1).click();await page.waitForFunction(title=>document.querySelector('#memory-book-reader .memory-book-reading h3')?.textContent===title,second.title);assert.doesNotMatch(await reader.locator('.memory-book-reading').textContent(),/合成家人原话/,'late detail stays out of the next child story');await reader.locator('.memory-book-reading-controls button').nth(2).click();assert(await reader.locator('.memory-book-reading').isHidden(),'Back to contents hides the active reading pane');
  await reader.locator('.memory-book-toc button').first().click();const backSources=reader.locator('.memory-book-reading .story-reader-sources'),backRow=backSources.locator(`[data-contribution-id="${textId}"]`);await backSources.locator('summary').click();await backRow.locator('button').click();await backRow.locator('.story-contribution-source-detail').waitFor({state:'visible'});await backRow.locator('button').click();await backRow.locator('.story-contribution-source-detail').waitFor({state:'hidden'});holdDetail=true;let backArrivedResolve;const backArrived=new Promise(resolve=>backArrivedResolve=resolve);arriveDetail=backArrivedResolve;await backRow.locator('button').click();await Promise.race([backArrived,page.waitForTimeout(5000).then(()=>{throw new Error('back-to-contents detail did not reach response fence');})]);await reader.locator('.memory-book-reading-controls button').nth(2).click();resolveDetail();await page.waitForTimeout(100);assert(await reader.locator('.memory-book-reading').isHidden(),'Back to contents hides reading before the held callback returns');assert.equal(await backRow.locator('.story-contribution-source-detail').evaluate(el=>el.hidden),true,'late detail cannot repopulate a hidden reading after Back to contents');
  await page.setViewportSize({width:390,height:844});await reader.locator('.memory-book-toc button').first().click();await sources.locator('summary').waitFor();await sources.locator('summary').click();const mobileTextRow=sources.locator(`[data-contribution-id="${textId}"]`);await mobileTextRow.locator('button').click();await mobileTextRow.locator('.story-contribution-source-detail').waitFor({state:'visible'});await page.evaluate(()=>{const elements=[...document.body.querySelectorAll('*')].filter(element=>[...element.childNodes].some(child=>child.nodeType===Node.TEXT_NODE&&child.textContent.trim()));window.__memoirFontScaleRestore=elements.map(element=>({element,fontSize:element.style.fontSize,lineHeight:element.style.lineHeight}));for(const element of elements){const style=getComputedStyle(element),size=parseFloat(style.fontSize),line=parseFloat(style.lineHeight);if(Number.isFinite(size))element.style.fontSize=`${size*1.5}px`;if(Number.isFinite(line))element.style.lineHeight=`${line*1.5}px`;}});await mobileTextRow.scrollIntoViewIfNeeded();const mobileLayout=await page.evaluate(()=>{const reader=document.querySelector('#memory-book-reader'),host=reader.querySelector('.memory-book-source-host'),row=reader.querySelector('[data-contribution-id]'),body=row.querySelector('.story-contribution-source-detail'),rect=element=>{const value=element.getBoundingClientRect();return {x:value.x,y:value.y,width:value.width,height:value.height,right:value.right,bottom:value.bottom};};return {viewport:{width:innerWidth,height:innerHeight},reader:{clientWidth:reader.clientWidth,scrollWidth:reader.scrollWidth,clientHeight:reader.clientHeight,scrollTop:reader.scrollTop,rect:rect(reader)},host:rect(host),row:rect(row),detail:rect(body),fontSize:getComputedStyle(row).fontSize};});assert.equal(mobileLayout.reader.scrollWidth>mobileLayout.reader.clientWidth,false,'source disclosure fits 390px at 150% text');console.log('MEMOIR_MOBILE_LAYOUT '+JSON.stringify(mobileLayout));await page.screenshot({path:path.join(artifacts,'memoir-source-reviewed-390-150.png')});await page.evaluate(()=>{for(const item of window.__memoirFontScaleRestore||[]){item.element.style.fontSize=item.fontSize;item.element.style.lineHeight=item.lineHeight;}delete window.__memoirFontScaleRestore;});await page.setViewportSize({width:1280,height:960});
  // A late detail after close is fenced by this reader's ticket and detached DOM.
  const rowAgain=sources.locator(`[data-contribution-id="${textId}"]`);await rowAgain.locator('button').click();await rowAgain.locator('.story-contribution-source-detail').waitFor({state:'hidden'});holdDetail=true;let closeArrivedResolve;const closeArrived=new Promise(resolve=>closeArrivedResolve=resolve);arriveDetail=closeArrivedResolve;await rowAgain.locator('button').click();await Promise.race([closeArrived,page.waitForTimeout(5000).then(()=>{throw new Error('close-race detail did not reach response fence');})]);await reader.locator(':scope > header button').click();resolveDetail();await page.waitForTimeout(100);await page.evaluate(value=>window.__storyWorkspaceTest.openBook(value),book);await page.locator('#memory-book-reader').waitFor({state:'visible'});await reader.locator('.memory-book-toc button').first().click();await page.waitForFunction(()=>document.querySelector('#memory-book-reader .memory-book-reading-prose'));assert.doesNotMatch(await reader.locator('.memory-book-reading').textContent(),/合成家人原话/,'closed reader late detail cannot restore reviewed text into a new reader');
  const scopeRow=sources.locator(`[data-contribution-id="${textId}"]`);await sources.locator('summary').click();await scopeRow.locator('button').click();await scopeRow.locator('.story-contribution-source-detail').waitFor({state:'visible'});await scopeRow.locator('button').click();await scopeRow.locator('.story-contribution-source-detail').waitFor({state:'hidden'});holdDetail=true;let libraryArrivedResolve;const libraryArrived=new Promise(resolve=>libraryArrivedResolve=resolve);arriveDetail=libraryArrivedResolve;await scopeRow.locator('button').click();await Promise.race([libraryArrived,page.waitForTimeout(5000).then(()=>{throw new Error('library-race detail did not reach response fence');})]);await page.locator('#library-select').evaluate(select=>{const option=document.createElement('option');option.value='family-b';option.textContent='Synthetic other library';select.append(option);});await page.locator('#library-select').selectOption('family-b');await reader.waitFor({state:'detached'});resolveDetail();await page.waitForTimeout(100);assert.equal(await page.locator('#memory-book-reader').count(),0,'changing library clears the prior memoir reader before late details can repopulate it');assert.doesNotMatch(await page.locator('body').textContent(),/合成家人原话/,'late memoir detail does not surface in the new library scope');
  assert.deepEqual(external,[]);assert.deepEqual(pageErrors,[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
  fs.writeFileSync(path.join(artifacts,'checks.json'),JSON.stringify({checks:['real ASGI parent/child refs','503 leaves prose readable and reopen retries refs','no automatic detail/audio fetch','explicit text and AI transcript review','narration stops on explicit source opening','chapter and child switching fence late detail','390px 150% reviewed-source render','close and library scope fences'],external,pageErrors,storyId,bookId:book.id},null,2));console.log('ARTIFACTS '+artifacts);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(ctx)await ctx.close();if(browser)await browser.close();bridge.stdin.end();});
