'use strict';
/* Deterministic VM coverage for the private, explicit browser narration controller. */
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../../backend/app/ui/access/story-workspace.js'),'utf8');
const appSource=fs.readFileSync(require('node:path').join(__dirname,'../../backend/app/ui/access/app.js'),'utf8');
const start=source.indexOf('  const narrationCopy =');
const end=source.indexOf('  const message =',start);
assert(start>=0&&end>start,'narration controller source remains present');
assert.match(source,/document\.addEventListener\('visibilitychange',\(\)=>\{if\(document\.hidden\)\{stopPlaying\(\);stopNarration\(\);\}\}\)/,'hidden documents stop browser narration');
assert.match(source,/mountNarration\(pane,section\.title,section\.narration,readingStory\.language/,'the authorized memoir essay reader offers the same chapter narrator');
assert.match(source,/window\.addEventListener\('pagehide',stopNarration\)/,'page hide cancels browser narration');
assert.match(source,/window\.addEventListener\('photohouse-memory-audio-start',stopNarration\)/,'family playback and microphone starts cancel browser narration');
class Element {
  constructor(tag,text='',cls=''){this.tag=tag;this.textContent=text;this.className=cls;this.children=[];this.listeners={};this.attributes={};this.style={};this.disabled=false;this.hidden=false;this.isConnected=false;this.parent=null;}
  append(...items){for(const item of items){item.parent=this;item.setConnected(this.isConnected);this.children.push(item);}}
  setConnected(value){this.isConnected=value;for(const child of this.children)child.setConnected(value);}
  addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
  setAttribute(key,value){this.attributes[key]=String(value);}
  click(){if(!this.disabled)for(const fn of this.listeners.click||[])fn({target:this});}
  remove(){if(this.parent)this.parent.children=this.parent.children.filter(child=>child!==this);this.isConnected=false;}
  querySelector(selector){return selector==='.story-narration-controls'?this.children.find(child=>child.className===selector.slice(1)):null;}
}
let account='a',library='l',locked=false,language='zh';
let playbackStops=0,captureBusy=false;
const utterances=[];let voices=[];
class Utterance{constructor(text){this.text=text;}}
const synth={speaking:false,pending:false,paused:false,resumeCount:0,cancelCount:0,getVoices:()=>voices,speak(value){utterances.push(value);this.speaking=true;},pause(){this.paused=true;},resume(){this.resumeCount++;this.paused=false;},cancel(){this.cancelCount++;this.speaking=false;this.pending=false;}};
const window={speechSynthesis:synth,SpeechSynthesisUtterance:Utterance};
const context={window,TextEncoder,validText:(value,max)=>typeof value==='string'&&Array.from(value).length<=max&&!/[\u0000\uD800-\uDFFF]/u.test(value),scope:()=>({account,library,locked,language}),narrationEpoch:0,narrationState:null,community:{stopPlayback(){playbackStops++;},isCapturing(){return captureBusy;}},
  stopPlaying(){},node:(tag,text,cls)=>new Element(tag,text,cls),button:(label,action)=>{const el=new Element('button',label);if(action)el.addEventListener('click',action);return el;}};
vm.runInNewContext(source.slice(start,end),context);
const mount=context.mountNarration;
const mountReplySpeech=context.mountReplySpeech;
const makeContainer=()=>{const root=new Element('div');root.isConnected=true;return root;};
const controlsOf=root=>root.children.find(child=>child.className==='story-narration-controls');
const replyControlsOf=root=>root.children.find(child=>child.className==='story-reply-speech-controls');
assert.match(appSource,/mountReplySpeech:\(\.\.\.args\)=>storyWorkspace\?\.mountReplySpeech\?\.\(\.\.\.args\)/,'the composition root injects the later-assigned local narration helper into MemoryCommunity');
const noVoice=makeContainer();voices=[{lang:'zh-CN',localService:false}];mount(noVoice,'标题','正文','zh',()=>true);
assert.equal(utterances.length,0,'mounting does not autoplay');controlsOf(noVoice).children[0].click();assert.equal(utterances.length,0,'remote-only voices are never spoken');assert.match(controlsOf(noVoice).children[4].textContent,/本机中文或英文语音/,'unsupported narration explains that text remains available');
const zh=makeContainer();voices=[{lang:'en-US',localService:true},{lang:'zh-CN',localService:true},{lang:'zh-TW',localService:false}];mount(zh,'标题','仅朗读正文','zh',()=>true);
const z=controlsOf(zh);assert.equal(utterances.length,0,'mounting does not autoplay');captureBusy=true;z.children[0].click();assert.equal(utterances.length,0,'active microphone capture blocks narration');assert.match(z.children[4].textContent,/请先结束录音/);captureBusy=false;const playbackStopsBefore=playbackStops;z.children[0].click();assert.equal(playbackStops,playbackStopsBefore+1,'authorized narrator start first stops family original playback');assert.equal(utterances.length,1);assert.equal(utterances[0].voice.lang,'zh-CN');assert.match(utterances[0].text,/标题.*仅朗读正文/);assert.doesNotMatch(utterances[0].text,/参考资料|原始贡献/);
z.children[1].click();assert.equal(synth.paused,true);z.children[1].click();assert.equal(synth.paused,false);const stale=utterances[0];z.children[2].click();assert.match(z.children[4].textContent,/已停止朗读/);assert.match(z.children[3].textContent,/片段 1 \/ 1/,'Stop keeps the last chunk position visible');stale.onend();assert.equal(utterances.length,1,'late callback after Stop cannot speak another chunk');
z.children[0].click();z.children[1].click();z.children[2].click();assert.equal(synth.paused,true,'cancel does not assume the browser clears its paused state');assert.equal(z.children[1].textContent,'暂停朗读','Stop resets the pause control label');const resumes=synth.resumeCount;z.children[0].click();assert.equal(synth.paused,false,'an authorized new start resumes a paused speech engine');assert.equal(synth.resumeCount,resumes+1);
const mismatch=makeContainer();mount(mismatch,'Title','Body','en',()=>true);voices=[{lang:'zh-CN',localService:true}];const beforeMismatch=utterances.length;controlsOf(mismatch).children[0].click();assert.equal(utterances.length,beforeMismatch,'story language must match a local voice');assert.match(controlsOf(mismatch).children[4].textContent,/本机中文或英文语音/);
language='en';const en=makeContainer();voices=[{lang:'en-GB',localService:true}];mount(en,'Title','Body','en',()=>true);controlsOf(en).children[0].click();assert.equal(utterances.at(-1).voice.lang,'en-GB','English story selects a local English voice');assert.match(controlsOf(en).children[3].textContent,/Chunk 1 \/ 1/,'English progress is bilingual and chunk-scoped');utterances.at(-1).onend();assert.match(controlsOf(en).children[4].textContent,/Chapter narration complete/,'English completion is clear');language='zh';
z.remove();z.children[2].click();assert.equal(synth.speaking,true,'a stale detached Stop button cannot cancel a newer reader');z.children[1].click();assert.equal(synth.paused,false,'a stale detached Pause button cannot pause a newer reader');
language='en';const fallback=makeContainer();mount(fallback,'Title','Body','und',()=>true);voices=[{lang:'en-US',localService:true}];controlsOf(fallback).children[0].click();assert.equal(utterances.at(-1).voice.lang,'en-US','und uses only the current UI language as fallback');language='zh';
const long=makeContainer();voices=[{lang:'zh-CN',localService:true}];const longText='这是一段很长的家庭回忆。'.repeat(500);mount(long,'长标题',longText,'zh',()=>true);const before=utterances.length;controlsOf(long).children[0].click();let index=before;while(index<utterances.length&&index<before+100){const utterance=utterances[index++];utterance.onend?.();if(index<utterances.length)utterance.onerror?.();}
const chunks=utterances.slice(before).map(item=>Array.from(item.text).length);assert(chunks.length>1&&chunks.every(size=>size<=180),'long text is split into bounded browser utterances');assert.match(controlsOf(long).children[3].textContent,new RegExp(`片段 ${chunks.length} \/ ${chunks.length}`),'plain progress follows bounded chunks without live announcements');assert.match(controlsOf(long).children[4].textContent,/本章朗读完毕/,'completion leaves a clear status');assert.equal(controlsOf(long).children[3].attributes['aria-live'],'off','chunk progress is excluded from live announcements');
const gated=makeContainer();let authorized=true;mount(gated,'标题','第一块。'.repeat(100),'zh',()=>authorized);const n=utterances.length;controlsOf(gated).children[0].click();const first=utterances.at(-1);first.onend();const next=utterances.at(-1);const started=utterances.length;first.onend();first.onerror?.();assert.equal(utterances.length,started,'duplicate or late callbacks for an old chunk cannot advance or stop the current chunk');assert.match(controlsOf(gated).children[3].textContent,/片段 2 \/ 3/);assert.match(controlsOf(gated).children[4].textContent,/正在朗读/,'stale errors cannot replace the current chunk status');authorized=false;next.onend();assert.equal(utterances.length,started,'authorization loss prevents the next chunk from speaking');context.stopNarration();assert.equal(controlsOf(gated).children[3].textContent,'','scope cleanup clears stale chunk progress');
const interrupted=makeContainer();mount(interrupted,'标题','新的章节','zh',()=>true);controlsOf(interrupted).children[0].click();context.stopNarration({type:'photohouse-memory-audio-start'});assert.equal(controlsOf(interrupted).children[3].textContent,'','DOM audio-start events clear progress instead of requesting explicit Stop retention');assert.equal(context.narrationState,null,'event cancellation releases the reader narration state');

const replyText='你'.repeat(6000);assert.equal(Array.from(replyText).length,6000);assert.equal(new TextEncoder().encode(replyText).length,18000);
const replyParent=makeContainer(),replyFallback=new Element('p',replyText,'assistant-reply');replyParent.append(replyFallback);const utterancesBeforeReplyMount=utterances.length,replyDispose=mountReplySpeech(replyParent,replyText,'zh',()=>true),replyControls=replyControlsOf(replyParent);
assert.ok(replyControls);assert.equal(replyControls.attributes['aria-label'],'助手回复朗读');assert.equal(replyControls.children[0].textContent,'朗读回复');assert.equal(replyControls.children[3].attributes.role,'status');assert.equal(replyControls.children[3].attributes['aria-live'],'polite');assert.equal(utterances.length,utterancesBeforeReplyMount,'mounting reply controls never autoplays');
voices=[{lang:'zh-CN',localService:false}];replyControls.children[0].click();assert.equal(utterances.length,utterancesBeforeReplyMount,'reply reading never selects a remote voice');assert.match(replyControls.children[3].textContent,/本机中文或英文语音/);assert.equal(replyFallback.textContent,replyText,'unsupported playback leaves the whole assistant reply available as text');
voices=[{lang:'zh-CN',localService:true},{lang:'en-US',localService:true}];captureBusy=true;replyControls.children[0].click();assert.equal(utterances.length,utterancesBeforeReplyMount,'active capture takes priority over local reply narration');assert.match(replyControls.children[3].textContent,/先结束录音/);captureBusy=false;
const replyFirst=utterances.length,replyStopsBefore=playbackStops;replyControls.children[0].click();assert.equal(playbackStops,replyStopsBefore+1,'explicit reply playback first stops contribution playback');assert.equal(utterances.length,replyFirst+1);assert.equal(utterances[replyFirst].voice.lang,'zh-CN');
replyControls.children[1].click();assert.equal(synth.paused,true);assert.equal(replyControls.children[1].textContent,'继续朗读');assert.match(replyControls.children[3].textContent,/朗读已暂停/);const pausedChunkCount=utterances.length;replyControls.children[1].click();assert.equal(synth.paused,false);assert.equal(replyControls.children[1].textContent,'暂停朗读');assert.equal(utterances.length,pausedChunkCount,'resume continues the same chunk without repeating text');
let replyIndex=replyFirst;while(replyIndex<utterances.length){const utterance=utterances[replyIndex++];utterance.onend?.();}
assert.equal(utterances.slice(replyFirst).map(item=>item.text).join(''),replyText,'the exact 6,000-code-point reply is read across bounded chunks without truncation');assert(utterances.slice(replyFirst).every(item=>Array.from(item.text).length<=180));assert.match(replyControls.children[3].textContent,/回复朗读完毕/);assert.equal(replyFallback.textContent,replyText,'successful speech leaves the full reply text intact');

language='en';const englishReply=makeContainer(),englishText='Your family’s memory stays available as text.';mountReplySpeech(englishReply,englishText,'en',()=>true);const englishControls=replyControlsOf(englishReply);assert.equal(englishControls.attributes['aria-label'],'Assistant reply audio');assert.equal(englishControls.children[0].textContent,'Read reply aloud');voices=[{lang:'en-US',localService:true}];const beforeEnglishReply=utterances.length;englishControls.children[0].click();assert.equal(utterances.length,beforeEnglishReply+1);assert.equal(utterances.at(-1).text,englishText);englishControls.children[1].click();assert.equal(englishControls.children[1].textContent,'Resume reading');assert.equal(englishControls.children[3].textContent,'Reading paused.');englishControls.children[1].click();assert.equal(englishControls.children[1].textContent,'Pause reading');utterances.at(-1).onerror?.();assert.equal(englishControls.children[1].hidden,true,'error clears pause controls');assert.match(englishControls.children[3].textContent,/Reply audio could not continue/);assert.equal(englishText,'Your family’s memory stays available as text.','speech failure leaves the original assistant text untouched');language='zh';voices=[{lang:'zh-CN',localService:true}];

const tooLong=makeContainer(),tooLongText='回'.repeat(6001),tooLongFallback=new Element('p',tooLongText);tooLong.append(tooLongFallback);mountReplySpeech(tooLong,tooLongText,'zh',()=>true);const tooLongControls=replyControlsOf(tooLong),beforeTooLong=utterances.length;
assert.equal(tooLongControls.children[0].disabled,true);assert.match(tooLongControls.children[3].textContent,/较长，暂时无法朗读/);tooLongControls.children[0].click();assert.equal(utterances.length,beforeTooLong,'oversize reply text is not silently truncated into speech');assert.equal(tooLongFallback.textContent,tooLongText,'oversize reply remains completely readable as text');

const stoppedReply=makeContainer(),stoppedText='停止操作后回复仍可阅读。';const stoppedFallback=new Element('p',stoppedText);stoppedReply.append(stoppedFallback);mountReplySpeech(stoppedReply,stoppedText,'zh',()=>true);const stoppedControls=replyControlsOf(stoppedReply),stoppedStart=utterances.length;stoppedControls.children[0].click();const stoppedUtterance=utterances.at(-1),beforeReplyStop=synth.cancelCount;stoppedControls.children[1].click();assert.equal(synth.paused,true);stoppedControls.children[2].click();assert.equal(stoppedControls.children[1].hidden,true);assert.equal(stoppedControls.children[1].disabled,true);assert.equal(synth.cancelCount,beforeReplyStop+1,'explicit Stop cancels the current reply utterance');assert.match(stoppedControls.children[3].textContent,/已停止朗读/);stoppedUtterance.onend?.();assert.equal(utterances.length,stoppedStart+1,'late end callback after reply Stop cannot continue the reply');assert.equal(stoppedFallback.textContent,stoppedText);

// Keep the actual handle from a fresh mount, then prove idempotent unmount and late-callback fencing.
const ownedReply=makeContainer(),ownedHandle=mountReplySpeech(ownedReply,'这段回复只属于当前卡片。','zh',()=>true),ownedControls=replyControlsOf(ownedReply);ownedControls.children[0].click();const ownedUtterance=utterances.at(-1),beforeOwnedDispose=synth.cancelCount,afterOwnedDisposeCount=utterances.length;ownedHandle();assert.equal(synth.cancelCount,beforeOwnedDispose+1,'disposing the mounted active reply cancels its own narration');assert.equal(ownedControls.isConnected,false);ownedUtterance.onend?.();assert.equal(utterances.length,afterOwnedDisposeCount,'late callback after disposer cannot continue narration');ownedHandle();assert.equal(synth.cancelCount,beforeOwnedDispose+1,'reply disposer is synchronous and idempotent');
const staleReply=makeContainer(),staleHandle=mountReplySpeech(staleReply,'较早的回复。','zh',()=>true),staleControls=replyControlsOf(staleReply);staleControls.children[0].click();mount(staleReply,'新章节','新的章节正文','zh',()=>true);controlsOf(staleReply).children[0].click();const chapterUtterance=utterances.at(-1),beforeStaleDispose=synth.cancelCount;staleHandle();assert.equal(synth.cancelCount,beforeStaleDispose,'stale reply disposal cannot cancel a newer chapter narration');assert.equal(synth.speaking,true);const resumesBeforeStale=synth.resumeCount;for(const action of staleControls.children[1].listeners.click)action();assert.equal(synth.resumeCount,resumesBeforeStale,'an older reply pause callback cannot resume the new chapter');chapterUtterance.onend?.();
const authorization=makeContainer();let replyAuthorized=true;mountReplySpeech(authorization,'授权改变后不应继续。'.repeat(20),'zh',()=>replyAuthorized);replyControlsOf(authorization).children[0].click();const authorizedFirst=utterances.at(-1),beforeAuthorizationAdvance=utterances.length;replyAuthorized=false;const resumesBeforeDenied=synth.resumeCount;for(const action of replyControlsOf(authorization).children[1].listeners.click)action();assert.equal(synth.resumeCount,resumesBeforeDenied,'denied reply scope cannot change native playback');authorizedFirst.onend?.();assert.equal(utterances.length,beforeAuthorizationAdvance,'stale target/conversation authorization blocks the next reply chunk');
const pauseFailure=makeContainer();mountReplySpeech(pauseFailure,'暂停操作失败后仍保留这段回复。','zh',()=>true);const failedPauseControls=replyControlsOf(pauseFailure);failedPauseControls.children[0].click();const failedPauseUtterance=utterances.at(-1),pauseMethod=synth.pause,cancelsBeforePauseFailure=synth.cancelCount,chunksBeforePauseFailure=utterances.length;synth.pause=()=>{throw new Error('Synthetic native pause failure');};failedPauseControls.children[1].click();synth.pause=pauseMethod;assert.equal(synth.cancelCount,cancelsBeforePauseFailure+1,'native pause failure cancels its own narration');assert.match(failedPauseControls.children[3].textContent,/回复朗读暂时无法继续/);assert.equal(failedPauseControls.children[1].hidden,true);failedPauseUtterance.onend?.();assert.equal(utterances.length,chunksBeforePauseFailure,'pause failure fences the late native callback');
replyDispose();assert.equal(replyControls.isConnected,false,'disposing an older inactive reply removes only its own controls');
console.log('PASS local chapter and reply narration, explicit start/Stop, bounded full reply text, local voices, capture priority, oversize fallback, cancellation and disposer ownership');

// Reviewable draft chapters reuse the same one-voice controller with distinct labels.
language='zh';voices=[{lang:'zh-CN',localService:true}];
const draftParent=makeContainer(),draftText='家人提供的文字仍需核对。'.repeat(30),draftBefore=utterances.length;
let draftCurrent=true;const draftDispose=mountReplySpeech(draftParent,draftText,'zh',()=>draftCurrent,'draft'),draftControls=replyControlsOf(draftParent);
assert.equal(draftControls.attributes['aria-label'],'AI建议章节朗读 · 待核对');assert.equal(draftControls.children[0].textContent,'朗读建议章节');assert.equal(utterances.length,draftBefore,'draft controls never autoplay');
captureBusy=true;draftControls.children[0].click();assert.equal(utterances.length,draftBefore,'recording blocks reviewable draft speech');assert.match(draftControls.children[3].textContent,/请先结束录音/);captureBusy=false;
draftControls.children[0].click();assert.equal(utterances.length,draftBefore+1);assert.ok(draftText.startsWith(utterances.at(-1).text),'spoken chunks come from the exact visible draft');assert.match(draftControls.children[3].textContent,/内容仍需核对/);draftControls.children[1].click();assert.equal(synth.paused,true);draftControls.children[1].click();assert.equal(synth.paused,false);
const draftFirst=utterances.at(-1),draftCount=utterances.length;draftCurrent=false;draftFirst.onend?.();assert.equal(utterances.length,draftCount,'stale chapter identity cannot speak another chunk');const draftCancels=synth.cancelCount;draftDispose();assert.equal(synth.cancelCount,draftCancels+1);assert.equal(draftControls.isConnected,false);
language='en';voices=[{lang:'en-US',localService:true}];const enDraft=makeContainer(),enDraftDispose=mountReplySpeech(enDraft,'This is reviewable draft text.','en',()=>true,'draft');const enDraftControls=replyControlsOf(enDraft);assert.equal(enDraftControls.children[0].textContent,'Read draft chapter aloud');enDraftControls.children[0].click();assert.equal(utterances.at(-1).text,'This is reviewable draft text.');assert.equal(utterances.at(-1).voice.lang,'en-US');enDraftControls.children[2].click();const endStopped=utterances.length;utterances.at(-1).onend?.();assert.equal(utterances.length,endStopped);enDraftDispose();
const invalidKind=makeContainer();assert.throws(()=>mountReplySpeech(invalidKind,'text','en',()=>true,'original'));assert.equal(invalidKind.children.length,0,'unknown content labels are rejected before mounting controls');
console.log('PASS draft chapter audio is explicit, local, review-labeled, paused/resumed/stopped and revision-fenced');
