'use strict';
/* Edition-bound source inspection against a synthetic ASGI bridge in Chromium. */
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process'),{createInterface}=require('node:readline');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const root=path.resolve(__dirname,'../..'),artifacts=process.env.PH_BROWSER_ARTIFACTS||fs.mkdtempSync(path.join(os.tmpdir(),'photohouse-edition-sources-'));
fs.mkdirSync(artifacts,{recursive:true});console.log('ARTIFACTS_DIR '+artifacts);
async function enlargeSourceText150(shelf){
  const baseline=await shelf.evaluate(root=>{const nodes=[...root.querySelectorAll('*')].filter(node=>[...node.childNodes].some(child=>child.nodeType===3&&child.textContent.trim()));return nodes.map((node,index)=>{const style=getComputedStyle(node);return {index,size:parseFloat(style.fontSize),line:parseFloat(style.lineHeight),oldSize:node.style.fontSize,oldLine:node.style.lineHeight};});});
  await shelf.evaluate((root,rows)=>{const nodes=[...root.querySelectorAll('*')].filter(node=>[...node.childNodes].some(child=>child.nodeType===3&&child.textContent.trim()));rows.forEach(row=>{const node=nodes[row.index];node.style.fontSize=`${row.size*1.5}px`;if(Number.isFinite(row.line))node.style.lineHeight=`${row.line*1.5}px`;});},baseline);
  const result=await shelf.evaluate((root,rows)=>{const nodes=[...root.querySelectorAll('*')].filter(node=>[...node.childNodes].some(child=>child.nodeType===3&&child.textContent.trim()));const checks=nodes.map((node,index)=>({node,index})).filter(({node})=>node.closest('.memory-edition-source-inspector')&&(node.closest('.memory-edition-source-open')||node.closest('.memory-edition-source-material')||node.closest('.memory-edition-source-excerpt')||node.classList.contains('memory-edition-source-origin'))).map(({node,index})=>({font:parseFloat(getComputedStyle(node).fontSize),minimum:rows[index].size*1.5,tag:node.tagName}));return {checks,overflow:root.scrollWidth>root.clientWidth||document.documentElement.scrollWidth>innerWidth};},baseline);
  assert(result.checks.some(check=>check.tag==='BUTTON')&&result.checks.some(check=>check.tag==='P'),'150% source check covers metadata actions and readable text');assert(result.checks.every(check=>check.font>=check.minimum-0.1),`source metadata and material reach 150%: ${JSON.stringify(result.checks)}`);assert.equal(result.overflow,false,'150% source inspector fits a 390px viewport');
  return baseline;
}
async function restoreSourceText(shelf,baseline){await shelf.evaluate((root,rows)=>{const nodes=[...root.querySelectorAll('*')].filter(node=>[...node.childNodes].some(child=>child.nodeType===3&&child.textContent.trim()));rows.forEach(row=>{const node=nodes[row.index];if(node){node.style.fontSize=row.oldSize;node.style.lineHeight=row.oldLine;}});},baseline);}
async function assertFocusedResult(selector,label){const result=await page.evaluate(selector=>{const node=document.querySelector(selector);if(!node)return {found:false};const rect=node.getBoundingClientRect();return {found:true,active:document.activeElement===node,visible:rect.top>=0&&rect.bottom<=innerHeight&&rect.left>=0&&rect.right<=innerWidth,rect:{top:rect.top,bottom:rect.bottom,left:rect.left,right:rect.right},viewport:{width:innerWidth,height:innerHeight,scrollY},text:node.textContent.trim()};},selector);assert(result.found,`${label} is present`);assert(result.active,`${label} receives focus after the explicit read`);assert(result.visible,`${label} is visible without test scrolling: ${JSON.stringify(result)}`);return result;}
const bridge=spawn(process.env.PH_BROWSER_PYTHON||path.join(root,'.venv/bin/python'),[path.join(__dirname,'memory_book_edition_sources_browser_bridge.py')],{cwd:root,stdio:['pipe','pipe','pipe']});
let serial=0,readyResolve,readyReject,seed;const pending=new Map(),ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
createInterface({input:bridge.stdout}).on('line',line=>{const value=JSON.parse(line);if(value.ready){seed=value;readyResolve();return;}const waiter=pending.get(value.id);if(waiter){pending.delete(value.id);waiter.resolve(value);}});
bridge.stderr.on('data',chunk=>process.stderr.write(chunk));bridge.on('exit',code=>{if(code){const error=new Error('Synthetic edition bridge exited '+code);readyReject(error);for(const waiter of pending.values())waiter.reject(error);}});
const rpc=message=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});bridge.stdin.write(JSON.stringify({...message,id})+'\n');});
let browser,context,page,failCommittedSave=true,acceptDialogs=true,malformCapsOnce=false,malformDetailOnce=false,holdProposal=false,proposalArrived,releaseProposal,proposalReady,proposalRelease,malformSourcePageOnce=false,malformShortMoreSourcePageOnce=false,sourcePageChangedOnce=false,emptySourcePageOnce=false,malformSourceDetailOnce=false,malformChapterSourceOnce=false,sourceChangedOnce=false,holdSourceDetail=false,sourceArrived,releaseSource,sourceReady,sourceRelease,holdAudio=false,audioArrived,releaseAudio,audioReady,audioRelease,failSourceOnce=false;const calls=[],external=[],errors=[];
(async()=>{
  await ready;
  browser=await chromium.launch({headless:true,...(process.env.PH_BROWSER_EXECUTABLE?{executablePath:process.env.PH_BROWSER_EXECUTABLE}:{}),args:['--disable-background-networking','--disable-component-update','--no-first-run','--host-resolver-rules=MAP * ~NOTFOUND']});
  context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});
  await context.addCookies([{name:seed.cookie_name,value:seed.session_cookie,url:'https://photohouse.test/',httpOnly:true,secure:true,sameSite:'Strict'}]);
  await context.route('**/*',async route=>{
    const request=route.request(),u=new URL(request.url());if(u.origin!=='https://photohouse.test'){external.push(u.origin);await route.abort();return;}
    if(u.pathname==='/'){await route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><main><div id="community"></div></main></body></html>'});return;}
    const entry={method:request.method(),path:u.pathname+u.search,body:request.postData()};calls.push(entry);
    const response=await rpc({method:entry.method,path:entry.path,headers:await request.allHeaders(),body:(request.postDataBuffer()||Buffer.alloc(0)).toString('base64')});
    if(u.pathname.endsWith('/edition-capabilities')&&malformCapsOnce){malformCapsOnce=false;await route.fulfill({status:200,contentType:'application/json',body:'{"version":1,"enabled":"true","can_save":true}'});return;}
    if(/\/editions\/[0-9a-f-]{36}$/.test(u.pathname)&&malformDetailOnce){malformDetailOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());value.state='source_changed';await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});return;}
    if(u.pathname.includes('/editions/proposals/')&&holdProposal){proposalArrived();await proposalRelease;}
    if(u.pathname.endsWith('/sources')&&malformSourcePageOnce){malformSourcePageOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());value.items[0].source_id='bad id';response.body=Buffer.from(JSON.stringify(value)).toString('base64');}
    if(u.pathname.endsWith('/sources')&&malformShortMoreSourcePageOnce){malformShortMoreSourcePageOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());value.items=value.items.slice(0,15);value.has_more=true;response.body=Buffer.from(JSON.stringify(value)).toString('base64');}
    if(u.pathname.endsWith('/sources')&&sourcePageChangedOnce){sourcePageChangedOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());value.state='source_changed';value.items=[];value.has_more=false;response.body=Buffer.from(JSON.stringify(value)).toString('base64');}
    if(u.pathname.endsWith('/sources')&&u.searchParams.get('page')==='2'&&emptySourcePageOnce){emptySourcePageOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());value.items=[];value.has_more=false;response.body=Buffer.from(JSON.stringify(value)).toString('base64');}
    if(/\/sources\/[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(u.pathname)&&malformSourceDetailOnce){malformSourceDetailOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());if(value.source)value.source.prompt_excerpt='x'.repeat(8193);response.body=Buffer.from(JSON.stringify(value)).toString('base64');}
    if(/\/sources\/editorial-[A-Za-z0-9-]+-chapter-[1-6]$/.test(u.pathname)&&malformChapterSourceOnce){malformChapterSourceOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());if(value.source)value.source.story_id=value.source.story_id===seed.child_one?seed.child_two:seed.child_one;response.body=Buffer.from(JSON.stringify(value)).toString('base64');}
    if(/\/sources\/[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(u.pathname)&&sourceChangedOnce){sourceChangedOnce=false;const value=JSON.parse(Buffer.from(response.body,'base64').toString());value.state='source_changed';value.source=null;response.body=Buffer.from(JSON.stringify(value)).toString('base64');}
    if(/\/sources\/[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(u.pathname)&&holdSourceDetail){sourceArrived();await sourceRelease;}
    if(u.pathname.endsWith('/audio')&&holdAudio){audioArrived();await audioRelease;}
    if(u.pathname.includes('/sources')&&failSourceOnce){failSourceOnce=false;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"Synthetic source unavailable"}'});return;}
    if(entry.method==='POST'&&/\/editions\?/.test(entry.path)&&response.status===200&&failCommittedSave){failCommittedSave=false;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"Synthetic lost save receipt"}'});return;}
    await route.fulfill({status:response.status,contentType:response.content_type||'application/json',body:Buffer.from(response.body,'base64')});
  });
  page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>acceptDialogs?dialog.accept():dialog.dismiss());
  await page.goto('https://photohouse.test/');await page.addStyleTag({content:fs.readFileSync(path.join(root,'backend/app/ui/access/styles.css'),'utf8')});await page.addStyleTag({content:'html{font-size:150%}'});
  await page.addScriptTag({content:fs.readFileSync(path.join(root,'backend/app/ui/access/memory-community.js'),'utf8')});
  await page.evaluate(async seed=>{
    window.__urls={created:[],revoked:[]};const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=value=>{const url=create(value);window.__urls.created.push(url);return url;};URL.revokeObjectURL=url=>{window.__urls.revoked.push(url);return revoke(url);};window.__mediaPlays=0;document.addEventListener('play',()=>window.__mediaPlays++,true);
    window.__scope={account:'synthetic-owner',library:'family-a',language:'zh',locked:false};window.__failures=[];
    const request=async(path,options={})=>{const suffix=path.includes('?')?'&':'?';const headers={'X-CSRF-Token':seed.csrf_token};let url=path+suffix+'library='+encodeURIComponent(window.__scope.library),method=options.method||'GET';
      // Narrative generation itself is covered elsewhere. Reuse the seeded,
      // actor-owned ready job to exercise this adoption path without a provider.
      if(method==='POST'&&path==='/memory-community/v1/jobs'){url='/memory-community/v1/jobs/'+seed.job_id+'?library=family-a';method='GET';}
      if(options.body)headers['Content-Type']='application/json';
      const response=await fetch(url,{method,headers,credentials:'same-origin',signal:options.signal,...(method!=='GET'&&options.body?{body:JSON.stringify(options.body)}:{})});
      if(!response.ok){const error=new Error('Synthetic HTTP '+response.status);error.status=response.status;throw error;}return options.responseType==='blob'?response.blob():response.json();};
    const book=await request('/memory-community/v1/books/'+seed.book_id);window.__target={...book,type:'memoir'};window.__baseTarget=window.__target;window.__loadBook=()=>request('/memory-community/v1/books/'+seed.book_id);
    window.__community=window.PhotoHouseMemoryCommunity({scope:()=>window.__scope,request,onError:error=>window.__failures.push(error.status)});
    await window.__community.attach(document.querySelector('#community'),window.__target);
  },seed);
  await page.getByRole('tab',{name:'整理建议',exact:true}).click();await page.locator('.memory-community-form button[type=submit]').click();await page.locator('.memory-edition-open').waitFor();
  assert.equal(calls.filter(call=>call.path.includes('/editions')).length,0,'job completion never adopts an edition');
  await page.locator('.memory-edition-open').click();await page.getByText('此相册库暂未开放回忆录版本保存。整理稿仍可在这里核对。',{exact:true}).waitFor();
  assert.equal(await page.locator('.memory-edition-form').count(),0,'default-off capability exposes no write form');
  await rpc({command:'editions-on'});malformCapsOnce=true;const capCount=calls.filter(call=>call.path.includes('/edition-capabilities')).length;
  await page.locator('.memory-edition-check-again').click();await page.waitForFunction(()=>window.__failures.length>0);assert.equal(calls.filter(call=>call.path.includes('/edition-capabilities')).length,capCount+1);assert.equal(await page.locator('.memory-edition-form').count(),0,'malformed capability cannot open a write form');
  await page.locator('.memory-edition-check-again').click();await page.locator('.memory-edition-form').waitFor();
  const form=page.locator('.memory-edition-form');assert(await form.locator('button[type=submit]').isDisabled(),'a proposal is not review confirmation');
  await form.locator('input[name=edition_title]').fill('家人核对的花园回忆 <b>原样文字</b>');await form.locator('.memory-edition-chapter summary').first().click();await form.locator('textarea[name=edition_chapter_0]').fill('奶奶讲起合成花园的片段；年份尚待家人确认。');
  const pendingForm=await form.elementHandle();const shelfReload=page.locator('.memory-edition-shelf-retry').count().then(n=>n?'.memory-edition-shelf-retry':'.memory-edition-shelf-refresh');await page.locator(await shelfReload).click();await page.getByText('还没有已保存的家庭版本。',{exact:true}).waitFor();assert(await pendingForm.evaluate(node=>node.isConnected),'shelf refresh preserves the pending editor DOM identity');assert.equal(await form.locator('input[name=edition_title]').inputValue(),'家人核对的花园回忆 <b>原样文字</b>','shelf refresh preserves unsaved editor text');
  await form.locator('input[name=edition_reviewed]').check();await form.locator('textarea[name=edition_chapter_0]').fill('奶奶讲起合成花园的片段；年份仍待家人确认。');assert(await form.locator('button[type=submit]').isDisabled(),'editing invalidates the prior review confirmation');
  acceptDialogs=false;await page.getByRole('tab',{name:'一起聊回忆',exact:true}).click();assert.equal(await form.locator('input[name=edition_title]').inputValue(),'家人核对的花园回忆 <b>原样文字</b>','declining discard keeps the manuscript');acceptDialogs=true;
  await form.locator('textarea[name=edition_chapter_0]').evaluate(input=>input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));
  await page.getByRole('tab',{name:'一起聊回忆',exact:true}).click();assert(await form.isVisible(),'IME composition blocks navigation');
  await form.locator('textarea[name=edition_chapter_0]').evaluate(input=>input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));
  assert(await form.locator('button[type=submit]').isDisabled(),'composition completion requires fresh review');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Chinese large text does not overflow horizontally');
  await form.locator('input[name=edition_reviewed]').check();await page.screenshot({path:path.join(artifacts,'review-zh-390px-text150.png'),fullPage:true});
  await form.locator('button[type=submit]').click();await page.getByText('暂时无法确认保存结果。稿件已保留；重试会使用完全相同的内容。',{exact:true}).waitFor();
  assert(await form.locator('input[name=edition_title]').isDisabled(),'uncertain saves freeze the exact manuscript');const firstSave=calls.find(call=>call.method==='POST'&&call.path.includes('/editions?'));assert(firstSave);
  const jobsBeforeRetry=calls.filter(call=>call.method==='POST'&&call.path.includes('/jobs?')).length;
  await page.locator('.memory-community-form button[type=submit]').click();assert.equal(calls.filter(call=>call.method==='POST'&&call.path.includes('/jobs?')).length,jobsBeforeRetry,'uncertain save blocks a new generation');
  await page.getByRole('tab',{name:'一起聊回忆',exact:true}).click();assert(await form.isVisible(),'uncertain save blocks switching into a conversation');
  await form.locator('button[type=submit]').click();await page.getByText('家庭版本已保存。',{exact:true}).waitFor();const saves=calls.filter(call=>call.method==='POST'&&call.path.includes('/editions?'));assert.equal(saves.length,2);assert.equal(saves[0].body,saves[1].body,'retry reuses identical payload and mutation');
  await page.locator('.memory-edition-shelf-refresh').click();await page.locator('.memory-edition-shelf-read').first().waitFor();assert.equal(await page.locator('.memory-edition-shelf-item').count(),1,'metadata shelf lists saved editions without prose');await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf h4').filter({hasText:'家人核对的花园回忆 <b>原样文字</b>'}).waitFor();assert.match(await page.locator('.memory-edition-shelf').innerText(),/年份仍待家人确认/);
  const shelfSourceCalls=()=>calls.filter(call=>call.path.includes('/sources'));
  assert.equal(shelfSourceCalls().length,0,'opening a saved edition does not automatically fetch source details');
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();
  assert.equal(shelfSourceCalls().filter(call=>/\/sources\?/.test(call.path)).length,1,'the explicit catalog action loads one metadata page');
  assert.equal(shelfSourceCalls().some(call=>/\/sources\/[^?]+$/.test(call.path)),false,'catalog rows do not automatically load material');
  assert.equal(shelfSourceCalls().some(call=>/\/audio(?:\?|$)/.test(call.path)),false,'catalog does not load audio');
  assert.equal(await page.locator('.memory-edition-source-open').count(),16,'source catalog pages contain at most sixteen metadata rows');
  assert.equal(await page.locator('.memory-edition-source-pages button').count(),1,'additional source metadata is paged');
  let sourceCatalogLabels=await page.locator('.memory-edition-source-open').allTextContents();
  await page.locator('.memory-edition-source-pages button').click();await page.waitForFunction(()=>document.querySelectorAll('.memory-edition-source-open').length>0&&document.querySelector('.memory-edition-source-list').textContent.includes('17'));
  assert(await page.locator('.memory-edition-source-open').count()>0&&await page.locator('.memory-edition-source-open').count()<=16,'second catalog page contains only bounded metadata');
  sourceCatalogLabels=sourceCatalogLabels.concat(await page.locator('.memory-edition-source-open').allTextContents());const allSourceLabels=sourceCatalogLabels.join('\n');for(const label of ['家人原话','家人录音','素材留言','图片描述','回忆录开场文字','已保存的篇章文字'])assert(allSourceLabels.includes(label),`source catalog labels the ${label} origin`);
  let audioRow=page.locator('.memory-edition-source-open').filter({hasText:'家人录音'}).first();
  if(!(await audioRow.count())){await page.locator('.memory-edition-source-pages button').click();await page.locator('.memory-edition-source-open').first().waitFor();audioRow=page.locator('.memory-edition-source-open').filter({hasText:'家人录音'}).first();}
  if(await audioRow.count()){await audioRow.click();await page.locator('.memory-edition-source-detail').waitFor();assert.match(await page.locator('.memory-edition-source-detail').innerText(),/当前转写文字 · AI 识别/);assert.equal(shelfSourceCalls().some(call=>/\/audio(?:\?|$)/.test(call.path)),false,'inspecting a recording source does not load audio automatically');
    await page.locator('.memory-edition-source-audio-load').click();await page.locator('.memory-edition-source-audio audio').waitFor();const player=page.locator('.memory-edition-source-audio audio');assert.equal(await player.evaluate(node=>node.autoplay),false);assert.equal(await player.evaluate(node=>node.preload),'none');assert.equal(await page.evaluate(()=>window.__mediaPlays),0,'audio loads with controls but never starts playback');assert.equal(shelfSourceCalls().filter(call=>/\/audio(?:\?|$)/.test(call.path)).length,1,'audio loads only after its explicit button');const urls=await page.evaluate(()=>window.__urls.created.slice());assert.equal(urls.length,1);await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf > h4').waitFor();assert.equal(await page.evaluate(()=>window.__urls.revoked.length),1,'fresh edition read revokes its previously loaded audio URL');
  }
  await rpc({command:'originals-off'});await page.locator('.memory-edition-sources-open').click();await page.getByText('来源目录暂时无法读取；未载入原话或录音。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-shelf > h4').count(),1,'originals gate refusal preserves only the bound manuscript');assert.equal(await page.locator('.memory-edition-source-detail').count(),0,'originals gate refusal exposes no source material');
  await rpc({command:'originals-on'});failSourceOnce=true;await page.locator('.memory-edition-sources-open').click();await page.getByText('来源目录暂时无法读取；未载入原话或录音。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-source-open').count(),0,'offline catalog failure clears old metadata');
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();malformShortMoreSourcePageOnce=true;await page.locator('.memory-edition-sources-open').click();await page.getByText('来源目录暂时无法读取；未载入原话或录音。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-source-open').count(),0,'a current short page with has_more is rejected and clears metadata');
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();malformSourcePageOnce=true;await page.locator('.memory-edition-sources-open').click();await page.getByText('来源目录暂时无法读取；未载入原话或录音。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-source-open').count(),0,'malformed source metadata clears previously listed rows');
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();
  let assetNote=page.locator('.memory-edition-source-open').filter({hasText:'素材留言'}).first();for(let pageNumber=1;!(await assetNote.count())&&pageNumber<6;pageNumber++){await page.getByRole('button',{name:'下一页来源',exact:true}).click();await page.locator('.memory-edition-source-open').first().waitFor();assetNote=page.locator('.memory-edition-source-open').filter({hasText:'素材留言'}).first();}assert.equal(await assetNote.count(),1,'synthetic asset note is explicitly discoverable in the edition catalog');await assetNote.click();await page.locator('.memory-edition-source-detail').waitFor();assert.match(await page.locator('.memory-edition-source-detail').innerText(),/Synthetic editor/,'asset-note detail includes its voluntary byline');await assertFocusedResult('.memory-edition-source-detail .memory-edition-source-origin','asset-note material heading');
  const editorFocusSentinel=await page.evaluateHandle(()=>{const input=document.createElement('textarea');input.className='memory-edition-form';input.setAttribute('aria-label','Synthetic private editor focus sentinel');document.body.append(input);return input;});holdSourceDetail=true;sourceReady=new Promise(resolve=>sourceArrived=resolve);sourceRelease=new Promise(resolve=>releaseSource=resolve);await assetNote.click();await sourceReady;await editorFocusSentinel.evaluate(node=>node.focus());assert(await editorFocusSentinel.evaluate(node=>node===document.activeElement),'the connected editor focus sentinel is active while source detail is delayed');releaseSource();holdSourceDetail=false;await page.waitForFunction(()=>document.querySelector('.memory-edition-source-detail .memory-edition-source-origin')&&document.activeElement?.getAttribute('aria-label')==='Synthetic private editor focus sentinel');assert(await editorFocusSentinel.evaluate(node=>node.isConnected&&node===document.activeElement),'a delayed source read does not steal focus from the connected editor');await editorFocusSentinel.evaluate(node=>node.remove());
  const captionRow=page.locator('.memory-edition-source-open').filter({hasText:'图片描述'}).first();assert.equal(await captionRow.count(),1,'synthetic edition closure includes an AI caption source');malformSourceDetailOnce=true;await captionRow.click();await page.getByText('当前无法读取此来源；已清除先前显示的材料。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-source-detail').count(),0,'malformed detail never falls back to previous material');assert.equal(await page.locator('.memory-edition-shelf > h4').count(),1,'a detail failure preserves only the separately verified manuscript');await assertFocusedResult('.memory-edition-source-status','failed source notice');
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();const captionRetry=page.locator('.memory-edition-source-open').filter({hasText:'图片描述 · AI 描述'}).first();await captionRetry.click();await page.locator('.memory-edition-source-detail').waitFor();assert.match(await page.locator('.memory-edition-source-detail').innerText(),/当前 AI 图片描述 · 需核实/);const sourceFontsZh=await enlargeSourceText150(page.locator('.memory-edition-shelf'));await page.screenshot({path:path.join(artifacts,'sources-zh-current-readable-390px-text150.png'),fullPage:true});await page.locator('.memory-edition-source-detail').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifacts,'sources-zh-detail-viewport-390px-text150.png')});await restoreSourceText(page.locator('.memory-edition-shelf'),sourceFontsZh);
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();let familyCaption=page.locator('.memory-edition-source-open').filter({hasText:'图片描述 · 家人提供'}).first();if(!(await familyCaption.count())){await page.locator('.memory-edition-source-pages button').click();await page.locator('.memory-edition-source-open').first().waitFor();familyCaption=page.locator('.memory-edition-source-open').filter({hasText:'图片描述 · 家人提供'}).first();}assert.equal(await familyCaption.count(),1,'synthetic user-edited caption remains distinguishable from AI caption');await familyCaption.click();await page.locator('.memory-edition-source-detail').waitFor();assert.match(await page.locator('.memory-edition-source-detail').innerText(),/当前由家人编辑的图片描述/);
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();let savedChapter=page.locator('.memory-edition-source-open').filter({hasText:'已保存的篇章文字'}).first();if(!(await savedChapter.count())){await page.locator('.memory-edition-source-pages button').click();await page.locator('.memory-edition-source-open').first().waitFor();savedChapter=page.locator('.memory-edition-source-open').filter({hasText:'已保存的篇章文字'}).first();}assert.equal(await savedChapter.count(),1,'catalog exposes saved chapter wording as editorial material');malformChapterSourceOnce=true;await savedChapter.click();await page.getByText('当前无法读取此来源；已清除先前显示的材料。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-source-detail').count(),0,'chapter source child identity must agree with its canonical source ID');
  await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();savedChapter=page.locator('.memory-edition-source-open').filter({hasText:'已保存的篇章文字'}).first();if(!(await savedChapter.count())){await page.locator('.memory-edition-source-pages button').click();await page.locator('.memory-edition-source-open').first().waitFor();savedChapter=page.locator('.memory-edition-source-open').filter({hasText:'已保存的篇章文字'}).first();}await savedChapter.click();await page.locator('.memory-edition-source-detail').waitFor();assert.match(await page.locator('.memory-edition-source-detail').innerText(),/当前保存的编辑文字/);assert.doesNotMatch(await page.locator('.memory-edition-source-detail').innerText(),/署名|Byline/,'saved chapter wording is not displayed as an independent family source');
  sourceChangedOnce=true;await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();let changedCaption=page.locator('.memory-edition-source-open').filter({hasText:'图片描述 · 家人提供'}).first();if(!(await changedCaption.count())){await page.getByRole('button',{name:'下一页来源',exact:true}).click();await page.locator('.memory-edition-source-open').first().waitFor();changedCaption=page.locator('.memory-edition-source-open').filter({hasText:'图片描述 · 家人提供'}).first();}await changedCaption.click();await page.getByText('来源已变化或已删除，整理文字已隐藏。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-shelf > h4').count(),0,'source_changed detail response clears the parent manuscript');assert.equal(await page.locator('.memory-edition-source-detail').count(),0,'source_changed detail response clears prior source material');await assertFocusedResult('.memory-edition-shelf-status','changed-source notice');
  await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf > h4').waitFor();await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-pages button').waitFor();sourcePageChangedOnce=true;await page.locator('.memory-edition-source-pages button').click();await page.getByText('来源已变化或已删除，整理文字已隐藏。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-shelf > h4').count(),0,'changed response on a later metadata page clears the parent manuscript');
  await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf > h4').waitFor();await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-pages button').waitFor();emptySourcePageOnce=true;await page.locator('.memory-edition-source-pages button').click();await page.getByRole('button',{name:'上一页来源',exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-source-open').count(),0,'a valid empty current metadata page is accepted');assert.equal(await page.locator('.memory-edition-shelf > h4').count(),1,'an empty current metadata page does not clear the verified manuscript');
  await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf > h4').waitFor();await page.locator('.memory-edition-read').click();await page.locator('.memory-edition-review h4').filter({hasText:'家人核对的花园回忆 <b>原样文字</b>'}).waitFor();assert.equal(await page.locator('.memory-edition-review b').count(),0,'title is text, never injected markup');assert.match(await page.locator('.memory-edition-review').innerText(),/年份仍待家人确认/);
  await page.screenshot({path:path.join(artifacts,'saved-zh-390px-text150.png'),fullPage:true});
  malformDetailOnce=true;await page.locator('.memory-edition-shelf-read').first().click();await page.getByText('暂时无法核对这个版本；整理文字已隐藏，请重新读取。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-shelf h4').count(),0,'fresh malformed shelf detail clears prior prose');
  await page.locator('.memory-edition-shelf-detail-retry').click();await page.locator('.memory-edition-shelf h4').first().waitFor();
  malformDetailOnce=true;await page.locator('.memory-edition-read').click();await page.getByText('这个版本的来源已变化或被删除，整理文字已隐藏。',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-review h4').count(),0,'malformed changed-source response cannot retain old prose');
  await page.locator('.memory-edition-read').click();await page.locator('.memory-edition-review h4').filter({hasText:'家人核对的花园回忆 <b>原样文字</b>'}).waitFor();
  await page.evaluate(async()=>{window.__community.clear();window.__scope.language='en';await window.__community.attach(document.querySelector('#community'),window.__target);});await page.getByRole('tab',{name:'Draft suggestions',exact:true}).click();await page.locator('.memory-community-form button[type=submit]').click();await page.locator('.memory-edition-open').click();await page.locator('.memory-edition-form').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'English large text does not overflow horizontally');await page.screenshot({path:path.join(artifacts,'review-en-390px-text150.png'),fullPage:true});
  await page.evaluate(async()=>{window.__community.clear();await window.__community.attach(document.querySelector('#community'),window.__target);});await page.getByRole('tab',{name:'Draft suggestions',exact:true}).click();await page.locator('.memory-community-form button[type=submit]').click();await page.locator('.memory-edition-open').waitFor();
  holdProposal=true;proposalReady=new Promise(resolve=>proposalArrived=resolve);proposalRelease=new Promise(resolve=>releaseProposal=resolve);await page.locator('.memory-edition-open').click();await proposalReady;
  const before=calls.filter(call=>call.method==='POST'&&call.path.includes('/editions?')).length;await page.evaluate(()=>{window.__scope.account='synthetic-other';window.__community.clear();});releaseProposal();holdProposal=false;await page.waitForLoadState('networkidle');assert.equal(await page.locator('.memory-edition-review').count(),0,'account change clears reviewed manuscript');assert.equal(calls.filter(call=>call.method==='POST'&&call.path.includes('/editions?')).length,before,'scope clearing never saves');
  await page.evaluate(async()=>{window.__scope.account='synthetic-owner';window.__scope.library='family-a';window.__scope.language='en';window.__community.clear();const fresh=await window.__loadBook();window.__target={...fresh,type:'memoir'};window.__baseTarget=window.__target;await window.__community.attach(document.querySelector('#community'),window.__target);});await page.locator('.memory-edition-shelf-read').first().waitFor();await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf > h4').waitFor();await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();const captionEnglish=page.locator('.memory-edition-source-open').filter({hasText:'Caption'}).first();assert.equal(await captionEnglish.count(),1,'English source catalog localizes origin and kind separately');await captionEnglish.click();await page.locator('.memory-edition-source-detail').waitFor();assert.match(await page.locator('.memory-edition-source-detail').innerText(),/Current AI caption · verify/);const sourceFontsEn=await enlargeSourceText150(page.locator('.memory-edition-shelf'));await page.screenshot({path:path.join(artifacts,'sources-en-current-readable-390px-text150.png'),fullPage:true});await page.locator('.memory-edition-source-detail').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifacts,'sources-en-detail-viewport-390px-text150.png')});await restoreSourceText(page.locator('.memory-edition-shelf'),sourceFontsEn);await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();
  holdSourceDetail=true;sourceReady=new Promise(resolve=>sourceArrived=resolve);sourceRelease=new Promise(resolve=>releaseSource=resolve);await page.locator('.memory-edition-source-open').first().click();await sourceReady;await page.evaluate(()=>{window.__scope.account='synthetic-other';window.__scope.library='family-b';window.__community.clear();});releaseSource();holdSourceDetail=false;await page.waitForLoadState('networkidle');assert.equal(await page.locator('.memory-edition-source-detail').count(),0,'late source detail cannot cross account and library changes');assert.equal(await page.locator('.memory-edition-shelf').count(),0,'account/library clear removes the whole bound shelf');
  await page.evaluate(async()=>{window.__scope.account='synthetic-owner';window.__scope.library='family-a';window.__target=window.__baseTarget;await window.__community.attach(document.querySelector('#community'),window.__target);});await page.locator('.memory-edition-shelf-read').first().waitFor();await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf > h4').waitFor();await page.locator('.memory-edition-sources-open').click();await page.locator('.memory-edition-source-open').first().waitFor();
  holdSourceDetail=true;sourceReady=new Promise(resolve=>sourceArrived=resolve);sourceRelease=new Promise(resolve=>releaseSource=resolve);await page.locator('.memory-edition-source-open').first().click();await sourceReady;await page.evaluate(async()=>{const changed={...window.__target,revision:String(Number(window.__target.revision)+1),stories:window.__target.stories.map((story,index)=>index?story:{...story,revision:String(Number(story.revision)+1)})};window.__target=changed;await window.__community.attach(document.querySelector('#community'),changed);});releaseSource();holdSourceDetail=false;await page.waitForLoadState('networkidle');assert.equal(await page.locator('.memory-edition-source-detail').count(),0,'late source detail cannot cross book and child revision changes');
  await page.evaluate(async()=>{window.__target=window.__baseTarget;await window.__community.attach(document.querySelector('#community'),window.__target);});await page.locator('.memory-edition-shelf-read').first().waitFor();await page.locator('.memory-edition-shelf-read').first().click();await page.locator('.memory-edition-shelf > h4').waitFor();await rpc({command:'scrub-source'});await page.locator('.memory-edition-shelf-refresh').click();await page.locator('.memory-edition-shelf-read').first().click();await page.getByText('Sources changed or were deleted. The manuscript is hidden.',{exact:true}).waitFor();assert.equal(await page.locator('.memory-edition-shelf h4').count(),0,'source invalidation clears prior shelf title and prose');
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log(JSON.stringify({status:'passed',save_requests:saves.length,identical_retry:true,browser_errors:errors.length,external_requests:external.length,artifacts}));
})().catch(error=>{console.error(error.stack);process.exitCode=1;}).finally(async()=>{if(page&&process.exitCode)await page.screenshot({path:path.join(artifacts,'failure.png'),fullPage:true}).catch(()=>{});if(context)await context.close();if(browser)await browser.close();if(!bridge.killed){bridge.stdin.end(JSON.stringify({command:'quit'})+'\n');bridge.kill();}});
